package dev.s7a.strata.integration.docs

import dev.s7a.strata.component.PlayerSkinSource
import dev.s7a.strata.geometry.IntSize
import dev.s7a.strata.render.DrawImage
import dev.s7a.strata.render.createDrawImage
import dev.s7a.strata.resource.ResourceId
import dev.s7a.strata.runtime.minecraft.font.MinecraftBoundedFontBackend
import dev.s7a.strata.runtime.minecraft.font.MinecraftFontBackend
import dev.s7a.strata.runtime.minecraft.font.MinecraftFontBackendFactory
import dev.s7a.strata.runtime.minecraft.font.MinecraftFontCompatibility
import dev.s7a.strata.runtime.minecraft.font.MinecraftFontLoadLimits
import dev.s7a.strata.runtime.minecraft.font.MinecraftTrueTypeFace
import dev.s7a.strata.runtime.minecraft.font.MinecraftTrueTypeSettings
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertFalse
import org.junit.jupiter.api.Assertions.assertThrows
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.io.TempDir
import java.nio.ByteBuffer
import java.nio.file.Files
import java.nio.file.Path
import java.nio.file.StandardOpenOption

/**
 * Exercises declared-input integrity, exact resource contracts, and temporary decoder ownership without native libraries.
 * Every input is generated by the test, and no game file or historical image participates in an assertion.
 */
internal class ShowcaseMinecraftAssetsTest {
    @field:TempDir
    lateinit var directory: Path

    @Test
    fun originalImageOutputsAreDetachedAndTheirInputHashesContainNoLocalPaths() {
        val fixture = ShowcaseMinecraftAssetFixture(directory)
        val factory = ProbeFactory()
        val assets = fixture.assets(factory)
        assertEquals(1, factory.opened)
        assertEquals(1, factory.closed)
        assertEquals(ShowcaseGuiAsset.entries.size, factory.decoded)
        assertEquals("Player0", assets.playerName)
        assertTrue(assets.playerSkin is PlayerSkinSource.Pixels)
        ShowcaseGuiAsset.entries.forEach { asset ->
            val image = assets.image(asset.id)
            assertEquals(asset.size, image.size)
            assertEquals(0xFF243444.toInt(), image.argbAt(0, 0))
        }
        val hashes = assets.inputHashes()
        assertTrue(hashes.keys.containsAll(listOf("client-jar", "asset-index", "version-manifest", "selection")))
        assertTrue(hashes.keys.any { key -> key.endsWith("assets/minecraft/textures/font/showcase-japanese.png") })
        assertTrue(hashes.keys.any { key -> key.endsWith("assets/minecraft/textures/gui/sprites/tooltip/frame.png.mcmeta") })
        assertTrue(hashes.values.all { hash -> Regex("[0-9a-f]{64}").matches(hash) })
        assertFalse(hashes.keys.any { key -> key.contains(':') || key.contains('\\') || key.startsWith('/') })
        Files.delete(fixture.clientJar)
        Files.delete(fixture.assetIndex)
        Files.delete(fixture.versionManifest)
        assertEquals(hashes, assets.inputHashes())
        assertEquals(IntSize(64, 64), assets.image(ShowcaseGuiAsset.PlayerSkin.id).size)
        assertThrows(IllegalArgumentException::class.java) { assets.image(ResourceId("minecraft", "textures/undeclared.png")) }
    }

    @Test
    fun identicalLogicalInputsHaveIdenticalHashesAcrossDifferentFilesystemRoots() {
        val first = ShowcaseMinecraftAssetFixture(directory.resolve("first")).assets(ProbeFactory())
        val second = ShowcaseMinecraftAssetFixture(directory.resolve("second")).assets(ProbeFactory())
        assertEquals(first.inputHashes(), second.inputHashes())
    }

    @Test
    fun clientAndIndexHashMismatchesFailBeforeOpeningTheDecoder() {
        val client = ShowcaseMinecraftAssetFixture(directory.resolve("client"))
        val clientFactory = ProbeFactory()
        Files.write(client.clientJar, byteArrayOf(1), StandardOpenOption.APPEND)
        assertThrows(IllegalArgumentException::class.java) { client.assets(clientFactory) }
        assertEquals(0, clientFactory.opened)

        val index = ShowcaseMinecraftAssetFixture(directory.resolve("index"))
        val indexFactory = ProbeFactory()
        Files.writeString(index.assetIndex, " ", StandardOpenOption.APPEND)
        assertThrows(IllegalArgumentException::class.java) { index.assets(indexFactory) }
        assertEquals(0, indexFactory.opened)
    }

    @Test
    fun aMatchingHashDoesNotPermitAnotherGameVersionOrPackFormat() {
        val manifest = ShowcaseMinecraftAssetFixture(directory.resolve("manifest"))
        Files.writeString(manifest.versionManifest, Files.readString(manifest.versionManifest).replace("26.2", "26.1"))
        assertThrows(IllegalArgumentException::class.java) { manifest.assets(ProbeFactory()) }

        val version = ShowcaseMinecraftAssetFixture(directory.resolve("version"))
        version.replaceClient("version.json", """{"id":"26.1","pack_version":{"resource_major":88,"resource_minor":0}}""".toByteArray())
        assertThrows(IllegalArgumentException::class.java) { version.assets(ProbeFactory()) }

        val pack = ShowcaseMinecraftAssetFixture(directory.resolve("pack"))
        pack.replaceClient("version.json", """{"id":"26.2","pack_version":{"resource_major":87,"resource_minor":0}}""".toByteArray())
        assertThrows(IllegalArgumentException::class.java) { pack.assets(ProbeFactory()) }
    }

    @Test
    fun anIndexedObjectMustMatchItsOwnDeclaredHash() {
        val fixture = ShowcaseMinecraftAssetFixture(directory)
        val factory = ProbeFactory()
        Files.write(fixture.objectFile("minecraft/textures/font/showcase-japanese.png"), byteArrayOf(1, 2, 3))
        assertThrows(IllegalArgumentException::class.java) { fixture.assets(factory) }
        assertEquals(0, factory.opened)
    }

    @Test
    fun missingImagesAndChangedNineSliceMetadataCloseTheTemporaryDecoder() {
        val missing = ShowcaseMinecraftAssetFixture(directory.resolve("missing"))
        val missingFactory = ProbeFactory()
        missing.removeClient("assets/minecraft/textures/gui/sprites/widget/button.png")
        assertThrows(IllegalArgumentException::class.java) { missing.assets(missingFactory) }
        assertEquals(1, missingFactory.closed)

        val metadata = ShowcaseMinecraftAssetFixture(directory.resolve("metadata"))
        val metadataFactory = ProbeFactory()
        metadata.replaceClient(
            "assets/minecraft/textures/gui/sprites/tooltip/frame.png.mcmeta",
            """{"gui":{"scaling":{"type":"nine_slice","width":100,"height":100,"border":10,"stretch_inner":false}}}""".toByteArray(),
        )
        assertThrows(IllegalArgumentException::class.java) { metadata.assets(metadataFactory) }
        assertEquals(1, metadataFactory.closed)
    }

    @Test
    fun imageCeilingsApplyBeforeDecodeAndDecodeFailuresStillCloseTheBackend() {
        val oversized = ShowcaseMinecraftAssetFixture(directory.resolve("oversized"))
        val oversizedFactory = ProbeFactory()
        oversized.replaceClient("assets/minecraft/textures/gui/menu_background.png", ShowcaseFixturePng.create(IntSize(8193, 1)) { _, _ -> -1 })
        assertThrows(IllegalArgumentException::class.java) { oversized.assets(oversizedFactory) }
        assertEquals(0, oversizedFactory.decoded)
        assertEquals(1, oversizedFactory.closed)

        val failed = ShowcaseMinecraftAssetFixture(directory.resolve("failed"))
        val failedFactory = ProbeFactory(failureAt = 3)
        assertThrows(IllegalStateException::class.java) { failed.assets(failedFactory) }
        assertEquals(3, failedFactory.decoded)
        assertEquals(1, failedFactory.closed)
    }

    @Test
    fun mutationDuringDecodeCannotPublishAProfileWithStaleInputHashes() {
        val fixture = ShowcaseMinecraftAssetFixture(directory)
        val factory = ProbeFactory(onFirstDecode = { Files.write(fixture.clientJar, byteArrayOf(2), StandardOpenOption.APPEND) })
        assertThrows(IllegalArgumentException::class.java) { fixture.assets(factory) }
        assertEquals(1, factory.closed)
    }

    private class ProbeFactory(
        private val failureAt: Int? = null,
        private val onFirstDecode: () -> Unit = {},
    ) : MinecraftFontBackendFactory {
        var opened = 0
        var decoded = 0
        var closed = 0

        override fun open(compatibility: MinecraftFontCompatibility): MinecraftFontBackend {
            opened++
            return object : MinecraftBoundedFontBackend {
                override fun decodePng(bytes: ByteArray): DrawImage = decodePng(bytes, MinecraftFontLoadLimits())

                override fun decodePng(
                    bytes: ByteArray,
                    limits: MinecraftFontLoadLimits,
                ): DrawImage {
                    decoded++
                    if (decoded == 1) onFirstDecode()
                    check(decoded != failureAt) { "Synthetic decoder failure." }
                    val header = ByteBuffer.wrap(bytes)
                    val size = IntSize(header.getInt(16), header.getInt(20))
                    limits.requireImageSize(size.width, size.height)
                    return createDrawImage(size, IntArray(size.width * size.height) { 0xFF243444.toInt() })
                }

                override fun openTrueType(
                    bytes: ByteArray,
                    settings: MinecraftTrueTypeSettings,
                ): MinecraftTrueTypeFace = error("The GUI decoder must not open a native font face.")

                override fun close() {
                    closed++
                }
            }
        }
    }
}
