package dev.s7a.strata.integration.docs

/**
 * Renders the Hangar introduction for the server and proxy runtimes with the shared screen demonstration.
 */
internal object HangarProjectMarkdown {
    /**
     * Returns Markdown with absolute links, preserving Paper and Velocity installation guidance.
     */
    fun render(): String =
        """<!-- Generated by :integration:docs:generateStrataSkill. Do not edit. -->

# Strata

Strata is a declarative UI library for Paper and Velocity plugins.
Build screens from reusable components, keep application state on the server or proxy, and test UI behavior without launching Minecraft.

${ReadmeDemoReadme.projectRegion}
## Installation

Install the Paper plugin on a Paper server, or the Velocity plugin on a Velocity proxy.
Players also need the Strata Fabric runtime matching their Minecraft version and Fabric Language Kotlin.
Use the same Strata release on the server or proxy and the client.
Vanilla clients cannot render Strata screens.

Strata provides a UI runtime for other plugins; application plugins define the screens and their behavior.

## Documentation and examples

- [Paper setup and examples](https://github.com/sya-ri/strata/blob/master/docs/guides/paper.md)
- [Velocity setup and examples](https://github.com/sya-ri/strata/blob/master/docs/guides/velocity.md)
- [Client runtime and compatibility](https://github.com/sya-ri/strata/blob/master/docs/reference/compatibility.md)
- [Component catalog](https://github.com/sya-ri/strata/blob/master/docs/reference/components.md)
- [Dokka API reference](https://gh.s7a.dev/strata/)
- [Source repository](https://github.com/sya-ri/strata)
- [Issue tracker](https://github.com/sya-ri/strata/issues)

Generative AI substantially assisted implementation, review, tests, documentation, and release-page text.
The maintainer directed the design and validates release artifacts through the public test suite.
""".replace("\r\n", "\n").replace('\r', '\n').trimEnd('\n') + "\n"
}
