package dev.s7a.strata.integration.docs

/**
 * Renders the canonical long-form Modrinth project body from checked release inputs.
 */
internal object ModrinthProjectMarkdown {
    /**
     * Renders a Modrinth project body from the shared compiled opening example.
     *
     * @param versions supported Minecraft version identifiers discovered from working runtime modules.
     * @param openExample compiled API-only Kotlin example shared with README and the public skill.
     * @return LF-normalized Markdown with one terminal newline.
     */
    internal fun render(
        versions: List<String>,
        openExample: String,
    ): String =
        """<!-- Generated by :integration:docs:generateStrataSkill. Do not edit. -->

# Strata

Strata is a declarative Minecraft UI library for Fabric Mods.
Application code builds platform-neutral `ScreenDefinition` values from reusable components, structural layouts, active modifiers, typed state, and inventory bindings; a separately installed version-matched runtime renders them with Minecraft assets and behavior.
Strata 0.1.1 adds Minecraft 1.20 support and makes no other functional change from 0.1.0.

## Highlights

- Structure screens with `Row`, `Column`, `Grid`, and intentional-overlap `Stack` instead of absolute coordinates.
- Compose 21 focused standard components, including independent `ScrollArea` and `Scrollbar`, virtual lists, slots, tabs, images, player heads, and progress controls.
- Keep events on modifiers and mutable values in caller-owned typed state.
- Bind player, container, ender-chest, furnace, active-menu, or custom slot sources without coupling UI definitions to runtime packages.
- Define purpose-specific downstream components as ordinary `UiScope` compositions or use the public `Element` and `Node` SPI when retained behavior is necessary.

## Install and open a screen

Compile ordinary Mod source against the API only, then install the runtime matching the active Minecraft version together with Fabric Language Kotlin.

```kotlin
dependencies {
    compileOnly("dev.s7a.strata:strata-api:0.1.1")
    modRuntimeOnly("dev.s7a.strata:strata-runtime-minecraft-fabric-<minecraft-version>:0.1.1")
    modRuntimeOnly("net.fabricmc:fabric-language-kotlin:<compatible-version>")
}
```

Declare `strata` as a required dependency in the consuming Mod's `fabric.mod.json`.
The following exact example is compiled against `strata-api` alone and is also used by the README and public Strata skill:

```kotlin
$openExample
```

## Supported Minecraft versions

${versions.joinToString(", ") { version -> "`$version`" }}

Minecraft 1.20 is the support floor.
Install exactly one Strata runtime matching the client version.

## Documentation and source

- [Documentation and API reference](https://gh.s7a.dev/strata/)
- [Component catalog and verified images](https://gh.s7a.dev/strata/guide/components.md)
- [Source repository](https://github.com/sya-ri/strata)
- [Issue tracker](https://github.com/sya-ri/strata/issues)
- [Public AI authoring skill](https://github.com/sya-ri/strata/tree/master/skills/strata)

Generative AI substantially assisted implementation, review, tests, documentation, and release-page text.
The maintainer directed the design and validates release artifacts through the public test suite.
""".replace("\r\n", "\n").replace('\r', '\n').trimEnd('\n') + "\n"
}
