package dev.s7a.strata.integration.docs

/**
 * Renders the canonical long-form Modrinth project body from checked release inputs.
 */
internal object ModrinthProjectMarkdown {
    /**
     * Renders a Modrinth project body from the shared compiled opening example.
     *
     * @param versions supported Minecraft version identifiers discovered from working runtime modules.
     * @param openExample compiled API-only Kotlin example shared with README and the public skill.
     * @param releaseVersion validated root project version used by every published Strata coordinate.
     * @return LF-normalized Markdown with one terminal newline.
     */
    internal fun render(
        versions: List<String>,
        openExample: String,
        releaseVersion: String,
    ): String =
        """<!-- Generated by :integration:docs:generateStrataSkill. Do not edit. -->

# Strata

Strata is a declarative UI library for Minecraft Fabric Mods.
Build screens from reusable components, keep application state in your own code, and test UI behavior without launching Minecraft.
A separately installed runtime connects those definitions to the client version and its resources.

## What you can build

- Arrange controls with layouts that measure and place their children.
- Combine text, inputs, scrolling lists, images, and Minecraft inventory bindings into application screens.
- Add sizing, appearance, focus, and input behavior through composable modifiers.
- Reuse screen definitions in headless tests and the Minecraft client.
- Compose your own components, or extend the public Element and Node contracts for retained behavior.

Browse the [component catalog](https://github.com/sya-ri/strata/blob/master/docs/reference/components.md) for images, compiled examples, and individual API links.

## Install and open a screen

Compile ordinary Mod source against the API only, then install the runtime matching the active Minecraft version together with Fabric Language Kotlin.

```kotlin
dependencies {
    compileOnly("dev.s7a.strata:strata-api:$releaseVersion")
    modRuntimeOnly("dev.s7a.strata:strata-runtime-minecraft-fabric-<minecraft-version>:$releaseVersion")
    modRuntimeOnly("net.fabricmc:fabric-language-kotlin:<compatible-version>")
}
```

Declare `strata` as a required dependency in the consuming Mod's `fabric.mod.json`.
The following exact example is compiled against `strata-api` alone and is also used by the README and public Strata skill:

```kotlin
$openExample
```

## Supported Minecraft versions

${versions.joinToString(", ") { version -> "`$version`" }}

Install exactly one Strata runtime matching the client version.
See [Minecraft compatibility](https://github.com/sya-ri/strata/blob/master/docs/reference/compatibility.md) for artifact names and Java requirements.

## Documentation and source

- [Dokka API reference](https://gh.s7a.dev/strata/)
- [Reader guides on GitHub](https://github.com/sya-ri/strata/blob/master/docs/README.md)
- [Component catalog and verified images](https://github.com/sya-ri/strata/blob/master/docs/reference/components.md)
- [Source repository](https://github.com/sya-ri/strata)
- [Issue tracker](https://github.com/sya-ri/strata/issues)
- [Public AI authoring skill](https://github.com/sya-ri/strata/tree/master/skills/strata)

Generative AI substantially assisted implementation, review, tests, documentation, and release-page text.
The maintainer directed the design and validates release artifacts through the public test suite.
""".replace("\r\n", "\n").replace('\r', '\n').trimEnd('\n') + "\n"
}
