package dev.s7a.strata.integration.docs

import dev.s7a.strata.geometry.IntOffset
import dev.s7a.strata.geometry.IntSize
import dev.s7a.strata.spi.InternalStrataRuntimeApi
import java.awt.image.BufferedImage
import java.io.ByteArrayOutputStream
import java.nio.file.Files
import java.nio.file.Path
import javax.imageio.ImageIO

/**
 * Prepares all README demo evidence from fresh compiled screens before any checked output is modified.
 * The caller owns the repository and read-only assets; processing and host disposal stay on the calling thread.
 */
@OptIn(InternalStrataRuntimeApi::class)
internal object ReadmeDemoPipeline {
    /**
     * Renders the compiled stages, complete stills, exact extracted source, a 34-second GIF, and input/output hashes.
     * The font version is supplied by the version catalog; source hashes use LF-normalized UTF-8 and binary hashes use actual bytes.
     */
    fun prepare(
        root: Path,
        assets: ReadmeDemoAssets,
        fontVersion: String,
    ): ReadmeDemoOutput {
        val files = linkedMapOf<String, ByteArray>()
        val font = ReadmeDemoAssets.font()
        val sources = ReadmeDemoStage.entries.associateWith { ReadmeDemoSource.read(root, it) }
        val frames = mutableListOf<ReadmeGifFrame>()
        ReadmeDemoStage.entries.forEach { stage ->
            val source = sources.getValue(stage)
            val previous = ReadmeDemoStage.entries.getOrNull(stage.ordinal - 1)?.let(sources::getValue)
            stage.scrollOffsets.forEachIndexed { index, offset ->
                val screen =
                    ShowcaseHeadlessRenderer.render(
                        assets.minecraft.profile,
                        stage.create(assets.players.take(stage.playerCount), assets.panel),
                        ShowcaseViewport(IntSize(256, 192), 2),
                        IntOffset(40, 80),
                        wheelDelta = offset / 9.0,
                    )
                val image = ReadmeDemoCompositor.compose(source, previous, screen, font)
                files[stillName(stage)] = png(image)
                files[screenName(stage)] = png(requireNotNull(screen.inputStream().use(ImageIO::read)))
                val delay =
                    if (index == stage.scrollOffsets.lastIndex) {
                        stage.durationCentiseconds - 30 * index
                    } else {
                        30
                    }
                frames += ReadmeGifFrame(image, delay)
            }
        }
        check(frames.sumOf { it.delayCentiseconds } == 3400) { "README demo must last exactly 34 seconds." }
        files["demo.gif"] = ReadmeGifEncoder.encode(frames)
        require(files.getValue("demo.gif").size <= 5 * 1024 * 1024) { "README demo GIF exceeds 5 MiB." }
        files["README.md"] = markdown(sources).toByteArray()
        files["render.properties"] = receipt(root, assets, fontVersion, files).toByteArray()
        return ReadmeDemoOutput(files)
    }

    /**
     * Writes prepared files below the caller-selected staging directory, creating its parents as needed.
     */
    fun write(
        directory: Path,
        output: ReadmeDemoOutput,
    ) {
        Files.createDirectories(directory)
        output.files.forEach { (name, bytes) -> Files.write(directory.resolve(name), bytes) }
    }

    /**
     * Compares complete expected bytes and the owned README region without modifying tracked files.
     * Missing or stale files fail with the exact artifact name and regeneration task.
     */
    fun check(
        root: Path,
        output: ReadmeDemoOutput,
    ) {
        val directory = root.resolve("docs/readme-demo")
        output.files.forEach { (name, bytes) ->
            val path = directory.resolve(name)
            require(Files.isRegularFile(path) && Files.readAllBytes(path).contentEquals(bytes)) {
                "Stale README demo artifact: $name. Run :integration:docs:generateReadmeDemo."
            }
        }
        val readme = Files.readString(root.resolve("README.md"))
        require(readme == ReadmeDemoReadme.replace(readme)) { "README demo region is stale. Run :integration:docs:generateReadmeDemo." }
    }

    private fun markdown(sources: Map<ReadmeDemoStage, ReadmeDemoSource>): String =
        buildString {
            appendLine("<!-- Generated by :integration:docs:generateReadmeDemo. Do not edit. -->")
            appendLine()
            appendLine("# Add components. Let the layout make room.")
            appendLine()
            appendLine("Three players first demonstrate added content, a fixed list width, and text alignment; five more then arrive one at a time before scrolling is added.")
            appendLine("Every screen is freshly rendered by Strata Headless from the compiled Kotlin example and original Minecraft assets.")
            appendLine("Overflow during the five short arrival frames is intentional: ScrollArea then contains the list, and a separately added Scrollbar shares its state.")
            appendLine("The GIF compares source revisions; it does not demonstrate hot reload or an in-game invitation service.")
            appendLine()
            appendLine("[Play the 34-second GIF](demo.gif) · [Render receipt](render.properties)")
            appendLine()
            ReadmeDemoStage.entries.forEach { stage ->
                appendLine("## ${stage.ordinal + 1}. ${stage.title}")
                appendLine()
                appendLine(stage.caption)
                appendLine()
                appendLine("![${stage.caption}](${stillName(stage)})")
                appendLine()
                appendLine("[Complete screen pixels](${screenName(stage)}) · [Compiled source](../../${ReadmeDemoSource.DIRECTORY}/${stage.sourceName}.kt)")
                appendLine()
                appendLine("<details><summary>Source shown in this frame</summary>")
                appendLine()
                appendLine("```kotlin")
                appendLine(sources.getValue(stage).lines.joinToString("\n"))
                appendLine("```")
                appendLine()
                appendLine("</details>")
                appendLine()
            }
            appendLine("## Running the example")
            appendLine()
            appendLine("The final example accepts immutable `ReadmePlayer` values with names, roles, and detached `PlayerSkinSource.Pixels` skins.")
            appendLine("Copy [the final screen](../../${ReadmeDemoSource.DIRECTORY}/ScrollPlayersExample.kt), [the player model](../../${ReadmeDemoSource.DIRECTORY}/ReadmePlayer.kt), [the screen chrome](../../${ReadmeDemoSource.DIRECTORY}/ReadmeDemoChrome.kt), [the row composition](../../${ReadmeDemoSource.DIRECTORY}/ReadmePlayerRow.kt), and [the colors](../../${ReadmeDemoSource.DIRECTORY}/ReadmeDemoColors.kt) into a Mod using Strata, then call `scrollPlayersScreen(players, panel).open()`.")
            appendLine("Supply the original Minecraft Social Interactions panel as an `ImageSource` alongside the player data; headless generation supplies detached pixels from the same asset.")
            appendLine("The `Invite` button demonstrates layout only; add an `onActivate` modifier to connect application behavior.")
            appendLine()
            appendLine("See [generation instructions](../development/documentation.md#readme-code-and-screen-demo) for fresh generation and verification.")
        }

    private fun receipt(
        root: Path,
        assets: ReadmeDemoAssets,
        fontVersion: String,
        files: Map<String, ByteArray>,
    ): String =
        buildString {
            appendLine("format=1")
            appendLine("duration.centiseconds=3400")
            appendLine("frame.count=${ReadmeDemoStage.entries.sumOf { it.scrollOffsets.size }}")
            appendLine("viewport=256x192")
            appendLine("scale=2")
            appendLine("canvas=1200x576")
            appendLine("font.version=$fontVersion")
            appendLine("font.sha256=${ShowcaseAssetIntegrity.sha256(ReadmeDemoAssets.resource("JetBrainsMono-Regular.ttf"))}")
            appendLine("font.license.sha256=${ShowcaseAssetIntegrity.sha256(ReadmeDemoAssets.resource("OFL.txt"))}")
            assets.hashes.forEach { (name, hash) -> appendLine("input.$name=$hash") }
            Files.list(root.resolve(ReadmeDemoSource.DIRECTORY)).use { paths ->
                paths.filter { Files.isRegularFile(it) }.sorted().forEach { path ->
                    appendLine("source.${path.fileName}.sha256=${ShowcaseAssetIntegrity.sha256(ReadmeDemoSource.readText(path).toByteArray())}")
                }
            }
            files.forEach { (name, bytes) -> appendLine("output.$name.sha256=${ShowcaseAssetIntegrity.sha256(bytes)}") }
        }

    private fun stillName(stage: ReadmeDemoStage): String = "${stage.ordinal + 1}-${stage.name.lowercase()}.png"

    private fun screenName(stage: ReadmeDemoStage): String = "${stage.ordinal + 1}-${stage.name.lowercase()}-screen.png"

    private fun png(image: BufferedImage): ByteArray =
        ByteArrayOutputStream().use { output ->
            check(ImageIO.write(image, "png", output)) { "The JDK PNG writer is missing." }
            output.toByteArray()
        }
}
