package dev.s7a.strata.integration.docs

/**
 * Complete prepared documentation output with no open resources or mutable runtime hosts.
 * The generating thread owns every byte array and must keep them unchanged during synchronization or checking.
 *
 * @property files relative output names and freshly generated bytes.
 */
internal data class ReadmeDemoOutput(
    val files: Map<String, ByteArray>,
)
