package dev.s7a.strata.integration.docs

import dev.s7a.strata.integration.docs.KotlinSourceSignatureInventory.OwnedDeclaration

/**
 * Renders the generated references shipped with the public Strata skill.
 */
internal object StrataSkillMarkdown {
    /**
     * Renders the complete standard component catalog from compiled overload counts and shared guidance.
     *
     * @param signatures exact source-form signatures verified against every compiled component overload.
     * @return LF-normalized Markdown with one terminal newline.
     */
    internal fun components(signatures: Map<DocumentedComponent, List<String>>): String =
        markdown(
            """<!-- Generated by :integration:docs:generateStrataSkill. Do not edit. -->

# Component catalog

Strata exposes ${signatures.size} focused standard components from `dev.s7a.strata.component`.
Every Kotlin declaration below is paired with the compiled `strata-api` overload inventory; generation fails when source and binary identities diverge or an undocumented component enters the API.
Use the [component showcase on GitHub]($COMPONENT_GUIDE_URL) for complete compiled examples and Minecraft-verified images.

${signatures.entries.joinToString("\n\n") { (component, overloads) -> component(component, overloads) }}
""",
        )

    /**
     * Renders the modifier and parent-layout-scope catalog from compiled overload counts.
     *
     * @param inventory exact compiled modifier inventory.
     * @param compiledStateAndBindings exact compiled state and binding member fingerprints.
     * @param signatures exact source-form signatures paired with the compiled inventory.
     * @return LF-normalized Markdown with one terminal newline.
     */
    internal fun modifiers(
        inventory: ModifierInventory.Result,
        compiledStateAndBindings: Map<String, List<String>>,
        signatures: KotlinSourceSignatureInventory.Result,
        stateExtensions: Map<String, List<String>> = emptyMap(),
    ): String =
        markdown(
            """<!-- Generated by :integration:docs:generateStrataSkill. Do not edit. -->

# Modifiers and layout scopes

Modifiers are active retained behavior, not a passive settings bag.
Order matters: layout and input elements wrap the behavior that follows them in the chain.
The ${inventory.modifiers.values.sum()} compiled overloads below form ${inventory.modifiers.size} top-level extension groups.

| Extension | Overloads | Category | Use |
| --- | ---: | --- | --- |
${inventory.modifiers.entries.joinToString("\n") { (name, count) -> modifierRow(name, count) }}

## Top-level modifier signatures

${inventory.modifiers.keys.joinToString("\n\n") { name -> signatureGroup(name, signatures.modifiers.getValue(name)) }}

## Parent-layout modifiers

These extensions are available only inside the layout scope that consumes their parent data.
Do not move them to a generic global helper or use them outside a direct child declaration.

| Scope extension | Overloads | Meaning |
| --- | ---: | --- |
${inventory.parentScopeModifiers.entries.joinToString("\n") { (entry, count) -> parentScopeRow(entry, count) }}

### Parent-layout signatures

${inventory.parentScopeModifiers.keys.joinToString("\n\n") { entry -> signatureGroup("${entry.scopeName}.${entry.methodName}", signatures.parentScopeModifiers.getValue(entry)) }}

$scaleToFitGuidance

## Selection guide

- Use `spacing`, `horizontalArrangement`, `verticalArrangement`, and parent alignment to describe sibling structure.
- Use `weight` only for remaining main-axis space and `align` only for a direct-child override.
- Use `padding` for local insets, and describe sibling relationships with layout spacing and alignment.
- Use `fillMaxSize().scaleToFit(contentSize)` for a fixed design surface that should shrink uniformly with the viewport while retaining the user's GUI-scale accessibility setting.
- Put images on `imageBackground` when they paint a container; use `Image` when the image is itself a logical child.
- Put reusable actions on modifiers. `Button`, `Tab`, `Checkbox`, `CycleButton`, `Slider`, and list components keep application callbacks out of their component signatures.
- Use `onActivate(enabled)` for an action shared by primary pointer and focused Enter or Space input; use `onPress` only when the action is pointer-specific.

## State and binding signatures

${StrataReactiveSkillMarkdown.extensions(signatures, stateExtensions)}

The following declarations are extracted from the public state and binding source files that compile into `strata-api`.
Use them to choose ownership and source types; application state remains authoritative.
Members marked `@InternalStrataRuntimeApi` are deliberately omitted from consumer signatures; the collapsed JVM fingerprints retain them only so binary drift still invalidates generation.

${StateBindingDocumentationCatalog.entries.joinToString("\n\n") { entry -> stateBindingGroup(entry, signatures.stateAndBindings.getValue(entry.typeName), compiledStateAndBindings.getValue(entry.typeName)) }}
""",
        )

    /**
     * Renders installation, runtime selection, supported versions, and the compiled screen-opening example.
     *
     * @param versions supported Minecraft version identifiers discovered from working runtime modules.
     * @param openExample compiled API-only Kotlin example.
     * @param releaseVersion validated root project version used by every published Strata coordinate.
     * @return LF-normalized Markdown with one terminal newline.
     */
    internal fun setup(
        versions: List<String>,
        openExample: String,
        releaseVersion: String,
    ): String =
        markdown(
            """<!-- Generated by :integration:docs:generateStrataSkill. Do not edit. -->

# Setup and screen opening

Application UI source compiles against `strata-api` only.
Install exactly one matching Strata Fabric runtime as a separate client Mod together with Fabric Language Kotlin.
Use the component catalog for available primitives and the guides for composition and resource ownership.

```kotlin
dependencies {
    compileOnly("dev.s7a.strata:strata-api:$releaseVersion")
    modRuntimeOnly("dev.s7a.strata:strata-runtime-minecraft-fabric-<minecraft-version>:$releaseVersion")
    modRuntimeOnly("net.fabricmc:fabric-language-kotlin:<compatible-version>")
}
```

Declare the runtime as a required Mod dependency so a production instance cannot start without the presenter used by `ScreenDefinition.open()`:

```json
{
  "depends": {
    "strata": ">=$releaseVersion"
  }
}
```

Do not import `runtime` packages, `MinecraftUiContext`, or a platform screen factory in ordinary UI definitions.
The definition remains owned by the caller when no runtime is installed or the client-thread preflight fails; a successful presentation transfers its one-shot payload.

## Compiled API-only example

```kotlin
$openExample
```

See [Authoring patterns](patterns.md) for state, input, and resource ownership.

## Supported Minecraft versions

${versions.joinToString("\n") { version -> "- `$version`: `strata-runtime-minecraft-fabric-$version`" }}

Minecraft 1.20 is the support floor.
Select one exact runtime matching the active game version; multiple versioned runtimes contain duplicate Strata classes.
""",
        )

    /**
     * Renders structural authoring guidance around one compiled API-only screen example.
     *
     * @param layoutExample compiled structural screen example.
     * @param releaseVersion aligned Strata version for the optional offline backend coordinate.
     * @return LF-normalized Markdown with one terminal newline.
     */
    internal fun patterns(
        layoutExample: String,
        releaseVersion: String,
        reactiveExample: String = "",
    ): String =
        markdown(
            """<!-- Generated by :integration:docs:generateStrataSkill. Do not edit. -->

# Authoring patterns

## Read the structure first

- Use `Row` for horizontal siblings, `FlowRow` for horizontal siblings that wrap at the available width, `Column` for vertical siblings, and `Grid` for repeated cells.
- `FlowRow` preserves direct-child identity when the width changes. Use `horizontalSpacing` and `verticalSpacing` for gaps, `horizontalArrangement` for each row, and `FlowRowScope.align` for a child's vertical alignment within its row; use `fillMaxWidth()` when the container should fill the available width.
- Use `Stack` only when children intentionally overlap or align against the same rectangle. It is not a generic `div` or box container.
- Do not wrap one element in a `Row` or `Column`. Put its modifier on that element or use the consuming parent's alignment API.
- Prefer layout spacing, arrangement, alignment, and weight over coordinate-shaped padding.
- Choose padding for the intended inset; express relationships between siblings with layout spacing and alignment.
- A background is paint: apply `background`, `imageBackground`, `menuBackground`, or `containerBackground` to the layout that owns the surface.

## Compiled structural example

```kotlin
$layoutExample
```

${StrataReactiveSkillMarkdown.patterns(reactiveExample)}

## State, scrolling, resources, and bindings

- Keep mutable values in caller-owned state objects and receive typed changes through modifiers. Use direct sources for immutable arguments that change automatically.
- Place `ScrollArea` and `Scrollbar` separately and link them with one `ScrollState`. A viewport may omit its scrollbar or place it away from the content.
- Use `TextAreaState` for multiline editing and link an optional `Scrollbar` to `state.scrollState`. Creating immutable descriptions does not attach the state, and descriptions may be reused after detachment; simultaneous attachment with the same caller-owned state throws `IllegalStateException`.
- Use the dynamic `VirtualList(itemCount = { ... })` overload for a loadable indexed source. Complete each prepend, append, or same-count row mutation inside its leading or trailing request handler, then call owner-thread `VirtualListState.refresh()` so the list resamples the count, rebuilds visible rows, and preserves its stable-key anchor when possible. The `Int` and `List` overloads are immutable snapshots. Use the same state for index or stable-key jumps.
- Use `ImageSource.Resource(ResourceId(...))` and image backgrounds for resource-pack-replaceable Mod assets.
- Use `TiledImageSource` for a large logical raster whose tiles load or change independently, keep navigation in `PanZoomState`, compose `panZoom(state)` for direct input, and place fixed-size markers through `TiledImageScope.atContentPosition`; pass a `StateSource<DoubleOffset>` when marker positions change independently.
- Use `PlayerSkinSource` for profile-driven heads rather than pre-rendering a skin outside the component.
- Bind `Slot` with `Slots.playerInventory`, `Slots.container`, or `Slots.activeMenu`; authoritative inventory mutation belongs to the active server menu.

The sealed `UiText` and `DrawCommand` hierarchies include `WithFont` and `SampledImage`; exhaustive visitors must handle every case.
Read the [rendering contracts](https://github.com/sya-ri/strata/blob/master/docs/development/rendering.md) when extending a backend.

${FONT_SETUP.replace(RELEASE_VERSION_PLACEHOLDER, releaseVersion)}
""",
        )

    /**
     * Renders the downstream component admission rule and one compiled custom composition.
     *
     * @param customExample compiled downstream component example.
     * @return LF-normalized Markdown with one terminal newline.
     */
    internal fun customComponents(customExample: String): String =
        markdown(
            """<!-- Generated by :integration:docs:generateStrataSkill. Do not edit. -->

# Custom components

Downstream Mods may create purpose-specific components as ordinary `UiScope` extension functions.
An energy gauge, social-entry row, advancement graph, machine controller, or application settings section belongs downstream when its meaning is specific to that product.

Admit a component to Strata's standard built-ins only when all of these are true:

- it has one focused UI responsibility;
- it has at least two natural independent use cases;
- it does not encode one screen or application-domain model;
- composition from existing primitives is insufficient.

## Compiled downstream composition

```kotlin
$customExample
```

Use public `Element` and `Node` SPI only when composition cannot provide the required retained measurement, drawing, input, semantics, or lifecycle behavior.
Read the [Element SPI contract]($ELEMENT_SPI_GUIDE_URL) before implementing a retained primitive; no central component registration is required.
""",
        )

    private val scaleToFitGuidance: String =
        """
        ## Scale-to-fit design surfaces

        `scaleToFit` requires a strictly positive `contentSize`, measures its virtual child once with that exact size, and reports `constraints.constrain(contentSize)` rather than implicitly filling a loose parent.
        Use an earlier, outer `fillMaxSize()` when the design surface should fit the complete viewport because modifier descriptions remain outermost-first:

        ```kotlin
        val modifier = Modifier.Empty
            .fillMaxSize()
            .scaleToFit(contentSize = IntSize(320, 180))
        ```

        The smaller axis ratio determines the uniform fit; `contentAlignment` positions remaining space.
        By default, `allowUpscaling = false` preserves logical size when content fits, leaving GUI density to control physical size.
        Enable upscaling when the design should also grow with the viewport.
        Earlier modifiers use viewport coordinates; later modifiers use design coordinates.
        A zero outer axis leaves the subtree unplaced.

        Custom primitives may implement `ChildTransformNode`; see the [Element SPI]($ELEMENT_SPI_GUIDE_URL#measure-and-layout) for transform composition and input mapping.
        Semantics, focus bounds, and overlay anchors use outward integer bounds; drawing clips retain fractional edges until final physical pixel coverage.
        Opaque platform draws require unit scale and exact integer translation and fail before output otherwise.
        """.trimIndent()

    private fun component(
        component: DocumentedComponent,
        overloads: List<String>,
    ): String =
        """<a id="${component.slug}"></a>

## ${component.apiMethodName}

${ComponentDocumentationCatalog.summary(component)}

- Compiled overloads: ${overloads.size}
- Modifiers: ${ComponentDocumentationCatalog.modifierGuidance(component)}
- Parent scope: ${ComponentDocumentationCatalog.parentScopeGuidance(component)}
- [Showcase image and compiled example]($COMPONENT_GUIDE_URL#${component.slug})

```kotlin
${overloads.joinToString("\n")}
```"""

    private fun signatureGroup(
        name: String,
        signatures: List<String>,
    ): String =
        """### `$name`

```kotlin
${signatures.joinToString("\n")}
```"""

    private fun stateBindingGroup(
        entry: StateBindingDocumentationCatalog.Entry,
        signatures: List<OwnedDeclaration>,
        compiledFingerprints: List<String>,
    ): String {
        val declarationsByOwner = signatures.groupBy(OwnedDeclaration::ownerPath)
        val ownerGroups =
            declarationsByOwner.entries.joinToString("\n\n") { (owner, declarations) ->
                """#### `$owner`

```kotlin
${declarations.joinToString("\n", transform = OwnedDeclaration::signature)}
```"""
            }
        return """### ${entry.typeName}

${entry.purpose}

$ownerGroups

<details><summary>Compiled JVM API fingerprints</summary>

```text
${compiledFingerprints.joinToString("\n")}
```

</details>"""
    }

    private fun modifierRow(
        name: String,
        overloadCount: Int,
    ): String {
        val entry = ModifierDocumentationCatalog.entries.getValue(name)
        return "| `$name` | $overloadCount | ${entry.category} | ${entry.purpose} |"
    }

    private fun parentScopeRow(
        entry: ModifierInventory.ParentScopeModifier,
        overloadCount: Int,
    ): String {
        val meaning =
            when (entry) {
                ModifierInventory.ParentScopeModifier.RowWeight -> "Allocates remaining horizontal space to a direct Row child."
                ModifierInventory.ParentScopeModifier.RowAlign -> "Overrides vertical alignment for a direct Row child."
                ModifierInventory.ParentScopeModifier.FlowRowAlign -> "Overrides vertical alignment for a direct FlowRow child within its measured row."
                ModifierInventory.ParentScopeModifier.ColumnWeight -> "Allocates remaining vertical space to a direct Column child."
                ModifierInventory.ParentScopeModifier.ColumnAlign -> "Overrides horizontal alignment for a direct Column child."
                ModifierInventory.ParentScopeModifier.GridAlign -> "Aligns one direct child within its Grid cell."
                ModifierInventory.ParentScopeModifier.StackAlign -> "Aligns one overlapping direct child within the Stack rectangle."
                ModifierInventory.ParentScopeModifier.TiledImageAtContentPosition -> "Anchors one fixed-size overlay child at a TiledImage content coordinate."
            }
        return "| `${entry.scopeName}.${entry.methodName}` | $overloadCount | $meaning |"
    }

    private fun markdown(value: String): String = value.replace("\r\n", "\n").replace('\r', '\n').trimEnd('\n') + "\n"

    private const val COMPONENT_GUIDE_URL = "https://github.com/sya-ri/strata/blob/master/docs/reference/components.md"
    private const val ELEMENT_SPI_GUIDE_URL = "https://github.com/sya-ri/strata/blob/master/docs/reference/element-spi.md"
    private const val TEXT_GUIDE_URL = "https://github.com/sya-ri/strata/blob/master/docs/guides/text.md"
    private const val FONT_GUIDE_URL = "https://github.com/sya-ri/strata/blob/master/docs/guides/fonts.md"
    private const val RELEASE_VERSION_PLACEHOLDER = "<generated-strata-release-version>"

    private const val FONT_SETUP: String =
        """## Unicode and resource-pack fonts

Use `font = ResourceId("example", "body")` to select `assets/example/font/body.json`, or `UiText.withFont` for reusable/composed labels.
An inner font wrapper wins over outer or component selection.
Glyph coverage follows the pack: unknown font IDs produce missing glyphs, and Strata adds no system-font, color-emoji, or ZWJ renderer.

Use `TextLayout.Multiline` for wrapping, hard breaks, or reserved text rectangles.
TextField edits one line; TextArea uses LF text and an explicit `TextAreaViewport`.
Both navigate Unicode scalars rather than grapheme clusters, count `maxLength` in UTF-16 code units, and keep preedit separate until committed.
Focus loss and terminal cleanup clear composition.
Selection, clipboard commands, and an OS candidate-window implementation are unavailable.
See [text and editing]($TEXT_GUIDE_URL) for compiled examples, input appearance, and target-specific IME support.

## Optional CPU backend for offline tools

Ordinary Fabric screens already receive the font backend; keep runtime imports out of UI definitions.
Offline hosts may use `dev.s7a.strata:strata-runtime-minecraft-fonts-lwjgl:$RELEASE_VERSION_PLACEHOLDER` with caller-supplied resources, exact target compatibility, matching libraries, and native classifiers.
The backend does not bundle LWJGL, ICU, Gson, or native binaries; incompatible native generations must run in separate processes.
Each host owns and closes its backend and bounded caches; snapshots are immutable and shareable.
Follow [Font resources]($FONT_GUIDE_URL) for setup and limits, including [numeric provider settings]($FONT_GUIDE_URL#numeric-provider-settings)."""
}
