package dev.s7a.strata.integration.docs

import dev.s7a.strata.integration.docs.KotlinSourceSignatureInventory.OwnedDeclaration

/**
 * Renders the generated references shipped with the public Strata skill.
 */
internal object StrataSkillMarkdown {
    /**
     * Renders the complete standard component catalog from compiled overload counts and shared guidance.
     *
     * @param signatures exact source-form signatures verified against every compiled component overload.
     * @return LF-normalized Markdown with one terminal newline.
     */
    internal fun components(signatures: Map<DocumentedComponent, List<String>>): String =
        markdown(
            """<!-- Generated by :integration:docs:generateStrataSkill. Do not edit. -->

# Component catalog

Strata exposes ${signatures.size} focused standard components from `dev.s7a.strata.component`.
Every Kotlin declaration below is paired with the compiled `strata-api` overload inventory; generation fails when source and binary identities diverge or an undocumented component enters the API.
Use the [rendered component showcase]($COMPONENT_GUIDE_URL) for complete compiled examples and Minecraft-verified images.

${signatures.entries.joinToString("\n\n") { (component, overloads) -> component(component, overloads) }}
""",
        )

    /**
     * Renders the modifier and parent-layout-scope catalog from compiled overload counts.
     *
     * @param inventory exact compiled modifier inventory.
     * @param compiledStateAndBindings exact compiled state and binding member fingerprints.
     * @param signatures exact source-form signatures paired with the compiled inventory.
     * @return LF-normalized Markdown with one terminal newline.
     */
    internal fun modifiers(
        inventory: ModifierInventory.Result,
        compiledStateAndBindings: Map<String, List<String>>,
        signatures: KotlinSourceSignatureInventory.Result,
    ): String =
        markdown(
            """<!-- Generated by :integration:docs:generateStrataSkill. Do not edit. -->

# Modifiers and layout scopes

Modifiers are active retained behavior, not a passive settings bag.
Order matters: layout and input elements wrap the behavior that follows them in the chain.
The ${inventory.modifiers.values.sum()} compiled overloads below form ${inventory.modifiers.size} top-level extension groups.

| Extension | Overloads | Category | Use |
| --- | ---: | --- | --- |
${inventory.modifiers.entries.joinToString("\n") { (name, count) -> modifierRow(name, count) }}

## Top-level modifier signatures

${inventory.modifiers.keys.joinToString("\n\n") { name -> signatureGroup(name, signatures.modifiers.getValue(name)) }}

## Parent-layout modifiers

These extensions are available only inside the layout scope that consumes their parent data.
Do not move them to a generic global helper or use them outside a direct child declaration.

| Scope extension | Overloads | Meaning |
| --- | ---: | --- |
${inventory.parentScopeModifiers.entries.joinToString("\n") { (entry, count) -> parentScopeRow(entry, count) }}

### Parent-layout signatures

${inventory.parentScopeModifiers.keys.joinToString("\n\n") { entry -> signatureGroup("${entry.scopeName}.${entry.methodName}", signatures.parentScopeModifiers.getValue(entry)) }}

## Selection guide

- Use `spacing`, `horizontalArrangement`, `verticalArrangement`, and parent alignment to describe sibling structure.
- Use `weight` only for remaining main-axis space and `align` only for a direct-child override.
- Use small `padding` for local insets. A value of 20 or more needs a concrete native-frame or fixed-geometry reason.
- Put images on `imageBackground` when they paint a container; use `Image` when the image is itself a logical child.
- Put reusable actions on modifiers. `Button`, `Tab`, `Checkbox`, `CycleButton`, `Slider`, and list components keep application callbacks out of their component signatures.

## State and binding signatures

The following declarations are extracted from the public state and binding source files that compile into `strata-api`.
Use them to choose ownership and source types; application state remains authoritative.
Members marked `@InternalStrataRuntimeApi` are deliberately omitted from consumer signatures; the collapsed JVM fingerprints retain them only so binary drift still invalidates generation.

${StateBindingDocumentationCatalog.entries.joinToString("\n\n") { entry -> stateBindingGroup(entry, signatures.stateAndBindings.getValue(entry.typeName), compiledStateAndBindings.getValue(entry.typeName)) }}
""",
        )

    /**
     * Renders installation, runtime selection, supported versions, and the compiled screen-opening example.
     *
     * @param versions supported Minecraft version identifiers discovered from working runtime modules.
     * @param openExample compiled API-only Kotlin example.
     * @return LF-normalized Markdown with one terminal newline.
     */
    internal fun setup(
        versions: List<String>,
        openExample: String,
    ): String =
        markdown(
            """<!-- Generated by :integration:docs:generateStrataSkill. Do not edit. -->

# Setup and screen opening

Application UI source compiles against `strata-api` only.
Install exactly one matching Strata Fabric runtime as a separate client Mod together with Fabric Language Kotlin.
Strata 0.1.1 adds Minecraft 1.20 support and makes no other functional change from 0.1.0.

```kotlin
dependencies {
    compileOnly("dev.s7a.strata:strata-api:0.1.1")
    modRuntimeOnly("dev.s7a.strata:strata-runtime-minecraft-fabric-<minecraft-version>:0.1.1")
    modRuntimeOnly("net.fabricmc:fabric-language-kotlin:<compatible-version>")
}
```

Declare the runtime as a required Mod dependency so a production instance cannot start without the presenter used by `ScreenDefinition.open()`:

```json
{
  "depends": {
    "strata": ">=0.1.1"
  }
}
```

Do not import `runtime` packages, `MinecraftUiContext`, or a platform screen factory in ordinary UI definitions.
The definition remains owned by the caller when no runtime is installed or the client-thread preflight fails; a successful presentation transfers its one-shot payload.

## Compiled API-only example

```kotlin
$openExample
```

## Supported Minecraft versions

${versions.joinToString("\n") { version -> "- `$version`: `strata-runtime-minecraft-fabric-$version`" }}

Minecraft 1.20 is the support floor.
Select one exact runtime matching the active game version; multiple versioned runtimes contain duplicate Strata classes.
""",
        )

    /**
     * Renders structural authoring guidance around one compiled API-only screen example.
     *
     * @param layoutExample compiled structural screen example.
     * @return LF-normalized Markdown with one terminal newline.
     */
    internal fun patterns(layoutExample: String): String =
        markdown(
            """<!-- Generated by :integration:docs:generateStrataSkill. Do not edit. -->

# Authoring patterns

## Read the structure first

- Use `Row` for horizontal siblings, `Column` for vertical siblings, and `Grid` for repeated cells.
- Use `Stack` only when children intentionally overlap or align against the same rectangle. It is not a generic `div` or box container.
- Do not wrap one element in a `Row` or `Column`. Put its modifier on that element or use the consuming parent's alignment API.
- Prefer layout spacing, arrangement, alignment, and weight over coordinate-shaped padding.
- Use small padding for local insets. Treat 20 or more as a review signal and retain it only for a documented native dimension or fixed panel geometry.
- A background is paint: apply `background`, `imageBackground`, `menuBackground`, or `containerBackground` to the layout that owns the surface.

## Compiled structural example

```kotlin
$layoutExample
```

## State, scrolling, resources, and bindings

- Keep mutable values in caller-owned state objects. Rebuild immutable component arguments from that state and receive typed changes through modifiers.
- Place `ScrollArea` and `Scrollbar` separately and link them with one `ScrollState`. A viewport may omit its scrollbar or place it away from the content.
- Use the dynamic `VirtualList(itemCount = { ... })` overload for a loadable indexed source. Complete each prepend, append, or same-count row mutation inside its leading or trailing request handler, then call owner-thread `VirtualListState.refresh()` so the list resamples the count, rebuilds visible rows, and preserves its stable-key anchor when possible. The `Int` and `List` overloads are immutable snapshots. Use the same state for index or stable-key jumps.
- Use `ImageSource.Resource(ResourceId(...))` and image backgrounds for resource-pack-replaceable Mod assets.
- Use `PlayerSkinSource` for profile-driven heads rather than pre-rendering a skin outside the component.
- Bind `Slot` with `Slots.playerInventory`, `Slots.container`, or `Slots.activeMenu`; authoritative inventory mutation belongs to the active server menu.
""",
        )

    /**
     * Renders the downstream component admission rule and one compiled custom composition.
     *
     * @param customExample compiled downstream component example.
     * @return LF-normalized Markdown with one terminal newline.
     */
    internal fun customComponents(customExample: String): String =
        markdown(
            """<!-- Generated by :integration:docs:generateStrataSkill. Do not edit. -->

# Custom components

Downstream Mods may create purpose-specific components as ordinary `UiScope` extension functions.
An energy gauge, social-entry row, advancement graph, machine controller, or application settings section belongs downstream when its meaning is specific to that product.

Admit a component to Strata's standard built-ins only when all of these are true:

- it has one focused UI responsibility;
- it has at least two natural independent use cases;
- it does not encode one screen or application-domain model;
- composition from existing primitives is insufficient.

## Compiled downstream composition

```kotlin
$customExample
```

Use public `Element` and `Node` SPI only when composition cannot provide the required retained measurement, drawing, input, semantics, or lifecycle behavior.
Read the [Element SPI contract]($ELEMENT_SPI_GUIDE_URL) before implementing a retained primitive; no central component registration is required.
""",
        )

    private fun component(
        component: DocumentedComponent,
        overloads: List<String>,
    ): String =
        """<a id="${component.slug}"></a>

## ${component.apiMethodName}

${ComponentDocumentationCatalog.summary(component)}

- Compiled overloads: ${overloads.size}
- Modifiers: ${ComponentDocumentationCatalog.modifierGuidance(component)}
- Parent scope: ${ComponentDocumentationCatalog.parentScopeGuidance(component)}
- [Showcase image and compiled example]($COMPONENT_GUIDE_URL#${component.slug})

```kotlin
${overloads.joinToString("\n")}
```"""

    private fun signatureGroup(
        name: String,
        signatures: List<String>,
    ): String =
        """### `$name`

```kotlin
${signatures.joinToString("\n")}
```"""

    private fun stateBindingGroup(
        entry: StateBindingDocumentationCatalog.Entry,
        signatures: List<OwnedDeclaration>,
        compiledFingerprints: List<String>,
    ): String {
        val declarationsByOwner = signatures.groupBy(OwnedDeclaration::ownerPath)
        val ownerGroups =
            declarationsByOwner.entries.joinToString("\n\n") { (owner, declarations) ->
                """#### `$owner`

```kotlin
${declarations.joinToString("\n", transform = OwnedDeclaration::signature)}
```"""
            }
        return """### ${entry.typeName}

${entry.purpose}

$ownerGroups

<details><summary>Compiled JVM API fingerprints</summary>

```text
${compiledFingerprints.joinToString("\n")}
```

</details>"""
    }

    private fun modifierRow(
        name: String,
        overloadCount: Int,
    ): String {
        val entry = ModifierDocumentationCatalog.entries.getValue(name)
        return "| `$name` | $overloadCount | ${entry.category} | ${entry.purpose} |"
    }

    private fun parentScopeRow(
        entry: ModifierInventory.ParentScopeModifier,
        overloadCount: Int,
    ): String {
        val meaning =
            when (entry) {
                ModifierInventory.ParentScopeModifier.RowWeight -> "Allocates remaining horizontal space to a direct Row child."
                ModifierInventory.ParentScopeModifier.RowAlign -> "Overrides vertical alignment for a direct Row child."
                ModifierInventory.ParentScopeModifier.ColumnWeight -> "Allocates remaining vertical space to a direct Column child."
                ModifierInventory.ParentScopeModifier.ColumnAlign -> "Overrides horizontal alignment for a direct Column child."
                ModifierInventory.ParentScopeModifier.GridAlign -> "Aligns one direct child within its Grid cell."
                ModifierInventory.ParentScopeModifier.StackAlign -> "Aligns one overlapping direct child within the Stack rectangle."
            }
        return "| `${entry.scopeName}.${entry.methodName}` | $overloadCount | $meaning |"
    }

    private fun markdown(value: String): String = value.replace("\r\n", "\n").replace('\r', '\n').trimEnd('\n') + "\n"

    private const val COMPONENT_GUIDE_URL = "https://gh.s7a.dev/strata/guide/components.md"
    private const val ELEMENT_SPI_GUIDE_URL = "https://gh.s7a.dev/strata/guide/element-spi.md"
}
