// Generated by :api:generateStateComponentOverloads. Do not edit by hand.
@file:Suppress("FunctionNaming", "ktlint:standard:function-naming", "LongParameterList", "TooManyFunctions", "UNCHECKED_CAST", "unused")

package dev.s7a.strata.component

import dev.s7a.strata.element.ElementKey
import dev.s7a.strata.geometry.IntRect
import dev.s7a.strata.geometry.IntSize
import dev.s7a.strata.modifier.Modifier
import dev.s7a.strata.resource.ResourceId
import dev.s7a.strata.state.StateSource
import dev.s7a.strata.text.TextWrap
import dev.s7a.strata.text.UiText

/**
 * Source-backed [ProgressBar] observing progress at the next frame cutoff.
 * Sources remain caller-owned; compatible nodes retain editing, focus, and scrolling state.
 * Literal arguments keep their existing contracts. Equal source values do not re-evaluate this component.
 * The complete modifier chain stays on the actual component; the wrapper delegates parent data and owns the sibling key.
 * Keep sources and dedicated editing states outside observed callbacks. Evaluation and input failures follow ordinary runtime cleanup.
 */
@JvmName("ProgressBarState4c303dc4114b_1")
public fun UiScope.ProgressBar(
    progress: StateSource<Double>,
    size: IntSize = IntSize(100, 12),
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    emitObservedComponent(listOf(progress), key) { values ->
        ProgressBar(
            progress = values[0] as Double,
            size = size,
            modifier = modifier,
            key = null,
        )
    }
}

/**
 * Source-backed [Checkbox] observing label at the next frame cutoff.
 * Sources remain caller-owned; compatible nodes retain editing, focus, and scrolling state.
 * Literal arguments keep their existing contracts. Equal source values do not re-evaluate this component.
 * The complete modifier chain stays on the actual component; the wrapper delegates parent data and owns the sibling key.
 * Keep sources and dedicated editing states outside observed callbacks. Evaluation and input failures follow ordinary runtime cleanup.
 */
@JvmName("CheckboxState3bddea62a5dc_1")
public fun UiScope.Checkbox(
    label: StateSource<UiText>,
    state: CheckboxState,
    width: Int = 150,
    enabled: Boolean = true,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    emitObservedComponent(listOf(label), key) { values ->
        Checkbox(
            label = values[0] as UiText,
            state = state,
            width = width,
            enabled = enabled,
            modifier = modifier,
            key = null,
        )
    }
}

/**
 * Source-backed [Checkbox] observing enabled at the next frame cutoff.
 * Sources remain caller-owned; compatible nodes retain editing, focus, and scrolling state.
 * Literal arguments keep their existing contracts. Equal source values do not re-evaluate this component.
 * The complete modifier chain stays on the actual component; the wrapper delegates parent data and owns the sibling key.
 * Keep sources and dedicated editing states outside observed callbacks. Evaluation and input failures follow ordinary runtime cleanup.
 */
@JvmName("CheckboxState3bddea62a5dc_2")
public fun UiScope.Checkbox(
    label: UiText,
    state: CheckboxState,
    width: Int = 150,
    enabled: StateSource<Boolean>,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    emitObservedComponent(listOf(enabled), key) { values ->
        Checkbox(
            label = label,
            state = state,
            width = width,
            enabled = values[0] as Boolean,
            modifier = modifier,
            key = null,
        )
    }
}

/**
 * Source-backed [Checkbox] observing label, enabled at the next frame cutoff.
 * Sources remain caller-owned; compatible nodes retain editing, focus, and scrolling state.
 * Literal arguments keep their existing contracts. Equal source values do not re-evaluate this component.
 * The complete modifier chain stays on the actual component; the wrapper delegates parent data and owns the sibling key.
 * Keep sources and dedicated editing states outside observed callbacks. Evaluation and input failures follow ordinary runtime cleanup.
 */
@JvmName("CheckboxState3bddea62a5dc_3")
public fun UiScope.Checkbox(
    label: StateSource<UiText>,
    state: CheckboxState,
    width: Int = 150,
    enabled: StateSource<Boolean>,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    emitObservedComponent(listOf(label, enabled), key) { values ->
        Checkbox(
            label = values[0] as UiText,
            state = state,
            width = width,
            enabled = values[1] as Boolean,
            modifier = modifier,
            key = null,
        )
    }
}

/**
 * Source-backed [CycleButton] observing enabled at the next frame cutoff.
 * Sources remain caller-owned; compatible nodes retain editing, focus, and scrolling state.
 * Literal arguments keep their existing contracts. Equal source values do not re-evaluate this component.
 * The complete modifier chain stays on the actual component; the wrapper delegates parent data and owns the sibling key.
 * Keep sources and dedicated editing states outside observed callbacks. Evaluation and input failures follow ordinary runtime cleanup.
 */
@JvmName("CycleButtonState454065400fd3_1")
public fun <T : Any> UiScope.CycleButton(
    state: CycleButtonState<T>,
    width: Int = 150,
    enabled: StateSource<Boolean>,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
    label: (T) -> UiText = { value -> UiText.Literal(state.formatKnownMember(value)) },
) {
    emitObservedComponent(listOf(enabled), key) { values ->
        CycleButton(
            state = state,
            width = width,
            enabled = values[0] as Boolean,
            modifier = modifier,
            key = null,
            label = label,
        )
    }
}

/**
 * Source-backed [CycleButton] observing label at the next frame cutoff.
 * Sources remain caller-owned; compatible nodes retain editing, focus, and scrolling state.
 * Literal arguments keep their existing contracts. Equal source values do not re-evaluate this component.
 * The complete modifier chain stays on the actual component; the wrapper delegates parent data and owns the sibling key.
 * Keep sources and dedicated editing states outside observed callbacks. Evaluation and input failures follow ordinary runtime cleanup.
 */
@JvmName("CycleButtonState454065400fd3_2")
public fun <T : Any> UiScope.CycleButton(
    state: CycleButtonState<T>,
    width: Int = 150,
    enabled: Boolean = true,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
    label: StateSource<(T) -> UiText>,
) {
    emitObservedComponent(listOf(label), key) { values ->
        CycleButton(
            state = state,
            width = width,
            enabled = enabled,
            modifier = modifier,
            key = null,
            label = values[0] as (T) -> UiText,
        )
    }
}

/**
 * Source-backed [CycleButton] observing enabled, label at the next frame cutoff.
 * Sources remain caller-owned; compatible nodes retain editing, focus, and scrolling state.
 * Literal arguments keep their existing contracts. Equal source values do not re-evaluate this component.
 * The complete modifier chain stays on the actual component; the wrapper delegates parent data and owns the sibling key.
 * Keep sources and dedicated editing states outside observed callbacks. Evaluation and input failures follow ordinary runtime cleanup.
 */
@JvmName("CycleButtonState454065400fd3_3")
public fun <T : Any> UiScope.CycleButton(
    state: CycleButtonState<T>,
    width: Int = 150,
    enabled: StateSource<Boolean>,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
    label: StateSource<(T) -> UiText>,
) {
    emitObservedComponent(listOf(enabled, label), key) { values ->
        CycleButton(
            state = state,
            width = width,
            enabled = values[0] as Boolean,
            modifier = modifier,
            key = null,
            label = values[1] as (T) -> UiText,
        )
    }
}

/**
 * Source-backed [Slider] observing label at the next frame cutoff.
 * Sources remain caller-owned; compatible nodes retain editing, focus, and scrolling state.
 * Literal arguments keep their existing contracts. Equal source values do not re-evaluate this component.
 * The complete modifier chain stays on the actual component; the wrapper delegates parent data and owns the sibling key.
 * Keep sources and dedicated editing states outside observed callbacks. Evaluation and input failures follow ordinary runtime cleanup.
 */
@JvmName("SliderStatef08abfd13498_1")
public fun UiScope.Slider(
    label: StateSource<UiText>,
    state: SliderState,
    width: Int = 150,
    enabled: Boolean = true,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    emitObservedComponent(listOf(label), key) { values ->
        Slider(
            label = values[0] as UiText,
            state = state,
            width = width,
            enabled = enabled,
            modifier = modifier,
            key = null,
        )
    }
}

/**
 * Source-backed [Slider] observing enabled at the next frame cutoff.
 * Sources remain caller-owned; compatible nodes retain editing, focus, and scrolling state.
 * Literal arguments keep their existing contracts. Equal source values do not re-evaluate this component.
 * The complete modifier chain stays on the actual component; the wrapper delegates parent data and owns the sibling key.
 * Keep sources and dedicated editing states outside observed callbacks. Evaluation and input failures follow ordinary runtime cleanup.
 */
@JvmName("SliderStatef08abfd13498_2")
public fun UiScope.Slider(
    label: UiText,
    state: SliderState,
    width: Int = 150,
    enabled: StateSource<Boolean>,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    emitObservedComponent(listOf(enabled), key) { values ->
        Slider(
            label = label,
            state = state,
            width = width,
            enabled = values[0] as Boolean,
            modifier = modifier,
            key = null,
        )
    }
}

/**
 * Source-backed [Slider] observing label, enabled at the next frame cutoff.
 * Sources remain caller-owned; compatible nodes retain editing, focus, and scrolling state.
 * Literal arguments keep their existing contracts. Equal source values do not re-evaluate this component.
 * The complete modifier chain stays on the actual component; the wrapper delegates parent data and owns the sibling key.
 * Keep sources and dedicated editing states outside observed callbacks. Evaluation and input failures follow ordinary runtime cleanup.
 */
@JvmName("SliderStatef08abfd13498_3")
public fun UiScope.Slider(
    label: StateSource<UiText>,
    state: SliderState,
    width: Int = 150,
    enabled: StateSource<Boolean>,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    emitObservedComponent(listOf(label, enabled), key) { values ->
        Slider(
            label = values[0] as UiText,
            state = state,
            width = width,
            enabled = values[1] as Boolean,
            modifier = modifier,
            key = null,
        )
    }
}

/**
 * Source-backed [Slider] observing label at the next frame cutoff.
 * Sources remain caller-owned; compatible nodes retain editing, focus, and scrolling state.
 * Literal arguments keep their existing contracts. Equal source values do not re-evaluate this component.
 * The complete modifier chain stays on the actual component; the wrapper delegates parent data and owns the sibling key.
 * Keep sources and dedicated editing states outside observed callbacks. Evaluation and input failures follow ordinary runtime cleanup.
 */
@JvmName("SliderStatecccdb0fa60d4_1")
public fun UiScope.Slider(
    label: StateSource<String>,
    state: SliderState,
    width: Int = 150,
    enabled: Boolean = true,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    emitObservedComponent(listOf(label), key) { values ->
        Slider(
            label = values[0] as String,
            state = state,
            width = width,
            enabled = enabled,
            modifier = modifier,
            key = null,
        )
    }
}

/**
 * Source-backed [Slider] observing enabled at the next frame cutoff.
 * Sources remain caller-owned; compatible nodes retain editing, focus, and scrolling state.
 * Literal arguments keep their existing contracts. Equal source values do not re-evaluate this component.
 * The complete modifier chain stays on the actual component; the wrapper delegates parent data and owns the sibling key.
 * Keep sources and dedicated editing states outside observed callbacks. Evaluation and input failures follow ordinary runtime cleanup.
 */
@JvmName("SliderStatecccdb0fa60d4_2")
public fun UiScope.Slider(
    label: String,
    state: SliderState,
    width: Int = 150,
    enabled: StateSource<Boolean>,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    emitObservedComponent(listOf(enabled), key) { values ->
        Slider(
            label = label,
            state = state,
            width = width,
            enabled = values[0] as Boolean,
            modifier = modifier,
            key = null,
        )
    }
}

/**
 * Source-backed [Slider] observing label, enabled at the next frame cutoff.
 * Sources remain caller-owned; compatible nodes retain editing, focus, and scrolling state.
 * Literal arguments keep their existing contracts. Equal source values do not re-evaluate this component.
 * The complete modifier chain stays on the actual component; the wrapper delegates parent data and owns the sibling key.
 * Keep sources and dedicated editing states outside observed callbacks. Evaluation and input failures follow ordinary runtime cleanup.
 */
@JvmName("SliderStatecccdb0fa60d4_3")
public fun UiScope.Slider(
    label: StateSource<String>,
    state: SliderState,
    width: Int = 150,
    enabled: StateSource<Boolean>,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    emitObservedComponent(listOf(label, enabled), key) { values ->
        Slider(
            label = values[0] as String,
            state = state,
            width = width,
            enabled = values[1] as Boolean,
            modifier = modifier,
            key = null,
        )
    }
}

/**
 * Source-backed [Checkbox] observing label at the next frame cutoff.
 * Sources remain caller-owned; compatible nodes retain editing, focus, and scrolling state.
 * Literal arguments keep their existing contracts. Equal source values do not re-evaluate this component.
 * The complete modifier chain stays on the actual component; the wrapper delegates parent data and owns the sibling key.
 * Keep sources and dedicated editing states outside observed callbacks. Evaluation and input failures follow ordinary runtime cleanup.
 */
@JvmName("CheckboxState1d460d77bb71_1")
public fun UiScope.Checkbox(
    label: StateSource<String>,
    state: CheckboxState,
    width: Int = 150,
    enabled: Boolean = true,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    emitObservedComponent(listOf(label), key) { values ->
        Checkbox(
            label = values[0] as String,
            state = state,
            width = width,
            enabled = enabled,
            modifier = modifier,
            key = null,
        )
    }
}

/**
 * Source-backed [Checkbox] observing enabled at the next frame cutoff.
 * Sources remain caller-owned; compatible nodes retain editing, focus, and scrolling state.
 * Literal arguments keep their existing contracts. Equal source values do not re-evaluate this component.
 * The complete modifier chain stays on the actual component; the wrapper delegates parent data and owns the sibling key.
 * Keep sources and dedicated editing states outside observed callbacks. Evaluation and input failures follow ordinary runtime cleanup.
 */
@JvmName("CheckboxState1d460d77bb71_2")
public fun UiScope.Checkbox(
    label: String,
    state: CheckboxState,
    width: Int = 150,
    enabled: StateSource<Boolean>,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    emitObservedComponent(listOf(enabled), key) { values ->
        Checkbox(
            label = label,
            state = state,
            width = width,
            enabled = values[0] as Boolean,
            modifier = modifier,
            key = null,
        )
    }
}

/**
 * Source-backed [Checkbox] observing label, enabled at the next frame cutoff.
 * Sources remain caller-owned; compatible nodes retain editing, focus, and scrolling state.
 * Literal arguments keep their existing contracts. Equal source values do not re-evaluate this component.
 * The complete modifier chain stays on the actual component; the wrapper delegates parent data and owns the sibling key.
 * Keep sources and dedicated editing states outside observed callbacks. Evaluation and input failures follow ordinary runtime cleanup.
 */
@JvmName("CheckboxState1d460d77bb71_3")
public fun UiScope.Checkbox(
    label: StateSource<String>,
    state: CheckboxState,
    width: Int = 150,
    enabled: StateSource<Boolean>,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    emitObservedComponent(listOf(label, enabled), key) { values ->
        Checkbox(
            label = values[0] as String,
            state = state,
            width = width,
            enabled = values[1] as Boolean,
            modifier = modifier,
            key = null,
        )
    }
}

/**
 * Source-backed [Image] observing source at the next frame cutoff.
 * Sources remain caller-owned; compatible nodes retain editing, focus, and scrolling state.
 * Literal arguments keep their existing contracts. Equal source values do not re-evaluate this component.
 * The complete modifier chain stays on the actual component; the wrapper delegates parent data and owns the sibling key.
 * Keep sources and dedicated editing states outside observed callbacks. Evaluation and input failures follow ordinary runtime cleanup.
 */
@JvmName("ImageState386405e1017f_1")
public fun UiScope.Image(
    source: StateSource<ImageSource>,
    size: IntSize? = null,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    emitObservedComponent(listOf(source), key) { values ->
        Image(
            source = values[0] as ImageSource,
            size = size,
            modifier = modifier,
            key = null,
        )
    }
}

/**
 * Source-backed [Image] observing source at the next frame cutoff.
 * Sources remain caller-owned; compatible nodes retain editing, focus, and scrolling state.
 * Literal arguments keep their existing contracts. Equal source values do not re-evaluate this component.
 * The complete modifier chain stays on the actual component; the wrapper delegates parent data and owns the sibling key.
 * Keep sources and dedicated editing states outside observed callbacks. Evaluation and input failures follow ordinary runtime cleanup.
 */
@JvmName("ImageState6751db0e9723_1")
public fun UiScope.Image(
    source: StateSource<ImageSource>,
    sourceRegion: IntRect,
    size: IntSize = IntSize(sourceRegion.width, sourceRegion.height),
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    emitObservedComponent(listOf(source), key) { values ->
        Image(
            source = values[0] as ImageSource,
            sourceRegion = sourceRegion,
            size = size,
            modifier = modifier,
            key = null,
        )
    }
}

/**
 * Source-backed [PlayerHead] observing source at the next frame cutoff.
 * Sources remain caller-owned; compatible nodes retain editing, focus, and scrolling state.
 * Literal arguments keep their existing contracts. Equal source values do not re-evaluate this component.
 * The complete modifier chain stays on the actual component; the wrapper delegates parent data and owns the sibling key.
 * Keep sources and dedicated editing states outside observed callbacks. Evaluation and input failures follow ordinary runtime cleanup.
 */
@JvmName("PlayerHeadState339c1e7d20b9_1")
public fun UiScope.PlayerHead(
    source: StateSource<PlayerSkinSource>,
    scale: PlayerHeadScale,
    showHat: Boolean = true,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
    loadingContent: (UiScope.() -> Unit)? = null,
    failureContent: (UiScope.() -> Unit)? = null,
) {
    emitObservedComponent(listOf(source), key) { values ->
        PlayerHead(
            source = values[0] as PlayerSkinSource,
            scale = scale,
            showHat = showHat,
            modifier = modifier,
            key = null,
            loadingContent = loadingContent,
            failureContent = failureContent,
        )
    }
}

/**
 * Source-backed [Slot] observing bind at the next frame cutoff.
 * Sources remain caller-owned; compatible nodes retain editing, focus, and scrolling state.
 * Literal arguments keep their existing contracts. Equal source values do not re-evaluate this component.
 * The complete modifier chain stays on the actual component; the wrapper delegates parent data and owns the sibling key.
 * Keep sources and dedicated editing states outside observed callbacks. Evaluation and input failures follow ordinary runtime cleanup.
 */
@JvmName("SlotStatea3c7818cbdc8_1")
public fun UiScope.Slot(
    bind: StateSource<SlotBinding?>,
    highlightable: Boolean = true,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
    content: (UiScope.() -> Unit)? = null,
) {
    emitObservedComponent(listOf(bind), key) { values ->
        Slot(
            bind = values[0] as SlotBinding?,
            highlightable = highlightable,
            modifier = modifier,
            key = null,
            content = content,
        )
    }
}

/**
 * Source-backed [Slot] observing highlightable at the next frame cutoff.
 * Sources remain caller-owned; compatible nodes retain editing, focus, and scrolling state.
 * Literal arguments keep their existing contracts. Equal source values do not re-evaluate this component.
 * The complete modifier chain stays on the actual component; the wrapper delegates parent data and owns the sibling key.
 * Keep sources and dedicated editing states outside observed callbacks. Evaluation and input failures follow ordinary runtime cleanup.
 */
@JvmName("SlotStatea3c7818cbdc8_2")
public fun UiScope.Slot(
    bind: SlotBinding? = null,
    highlightable: StateSource<Boolean>,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
    content: (UiScope.() -> Unit)? = null,
) {
    emitObservedComponent(listOf(highlightable), key) { values ->
        Slot(
            bind = bind,
            highlightable = values[0] as Boolean,
            modifier = modifier,
            key = null,
            content = content,
        )
    }
}

/**
 * Source-backed [Slot] observing bind, highlightable at the next frame cutoff.
 * Sources remain caller-owned; compatible nodes retain editing, focus, and scrolling state.
 * Literal arguments keep their existing contracts. Equal source values do not re-evaluate this component.
 * The complete modifier chain stays on the actual component; the wrapper delegates parent data and owns the sibling key.
 * Keep sources and dedicated editing states outside observed callbacks. Evaluation and input failures follow ordinary runtime cleanup.
 */
@JvmName("SlotStatea3c7818cbdc8_3")
public fun UiScope.Slot(
    bind: StateSource<SlotBinding?>,
    highlightable: StateSource<Boolean>,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
    content: (UiScope.() -> Unit)? = null,
) {
    emitObservedComponent(listOf(bind, highlightable), key) { values ->
        Slot(
            bind = values[0] as SlotBinding?,
            highlightable = values[1] as Boolean,
            modifier = modifier,
            key = null,
            content = content,
        )
    }
}

/**
 * Source-backed [TextField] observing enabled at the next frame cutoff.
 * Sources remain caller-owned; compatible nodes retain editing, focus, and scrolling state.
 * Literal arguments keep their existing contracts. Equal source values do not re-evaluate this component.
 * The complete modifier chain stays on the actual component; the wrapper delegates parent data and owns the sibling key.
 * Keep sources and dedicated editing states outside observed callbacks. Evaluation and input failures follow ordinary runtime cleanup.
 */
@JvmName("TextFieldStatebdacf61484d9_1")
public fun UiScope.TextField(
    state: TextFieldState,
    enabled: StateSource<Boolean>,
    textStyle: TextStyle = TextStyle.TextField,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    emitObservedComponent(listOf(enabled), key) { values ->
        TextField(
            state = state,
            enabled = values[0] as Boolean,
            textStyle = textStyle,
            modifier = modifier,
            key = null,
        )
    }
}

/**
 * Source-backed [TextField] observing enabled at the next frame cutoff.
 * Sources remain caller-owned; compatible nodes retain editing, focus, and scrolling state.
 * Literal arguments keep their existing contracts. Equal source values do not re-evaluate this component.
 * The complete modifier chain stays on the actual component; the wrapper delegates parent data and owns the sibling key.
 * Keep sources and dedicated editing states outside observed callbacks. Evaluation and input failures follow ordinary runtime cleanup.
 */
@JvmName("TextFieldState06eec201bfdd_1")
public fun UiScope.TextField(
    state: TextFieldState,
    size: IntSize,
    enabled: StateSource<Boolean>,
    textStyle: TextStyle = TextStyle.TextField,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    emitObservedComponent(listOf(enabled), key) { values ->
        TextField(
            state = state,
            size = size,
            enabled = values[0] as Boolean,
            textStyle = textStyle,
            modifier = modifier,
            key = null,
        )
    }
}

/**
 * Source-backed [TextField] observing enabled at the next frame cutoff.
 * Sources remain caller-owned; compatible nodes retain editing, focus, and scrolling state.
 * Literal arguments keep their existing contracts. Equal source values do not re-evaluate this component.
 * The complete modifier chain stays on the actual component; the wrapper delegates parent data and owns the sibling key.
 * Keep sources and dedicated editing states outside observed callbacks. Evaluation and input failures follow ordinary runtime cleanup.
 */
@JvmName("TextFieldStateac020717728e_1")
public fun UiScope.TextField(
    state: TextFieldState,
    font: ResourceId,
    enabled: StateSource<Boolean>,
    textStyle: TextStyle = TextStyle.TextField,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    emitObservedComponent(listOf(enabled), key) { values ->
        TextField(
            state = state,
            font = font,
            enabled = values[0] as Boolean,
            textStyle = textStyle,
            modifier = modifier,
            key = null,
        )
    }
}

/**
 * Source-backed [TextField] observing enabled at the next frame cutoff.
 * Sources remain caller-owned; compatible nodes retain editing, focus, and scrolling state.
 * Literal arguments keep their existing contracts. Equal source values do not re-evaluate this component.
 * The complete modifier chain stays on the actual component; the wrapper delegates parent data and owns the sibling key.
 * Keep sources and dedicated editing states outside observed callbacks. Evaluation and input failures follow ordinary runtime cleanup.
 */
@JvmName("TextFieldState0f2e4a0352af_1")
public fun UiScope.TextField(
    state: TextFieldState,
    size: IntSize,
    font: ResourceId,
    enabled: StateSource<Boolean>,
    textStyle: TextStyle = TextStyle.TextField,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    emitObservedComponent(listOf(enabled), key) { values ->
        TextField(
            state = state,
            size = size,
            font = font,
            enabled = values[0] as Boolean,
            textStyle = textStyle,
            modifier = modifier,
            key = null,
        )
    }
}

/**
 * Source-backed [TextArea] observing enabled at the next frame cutoff.
 * Sources remain caller-owned; compatible nodes retain editing, focus, and scrolling state.
 * Literal arguments keep their existing contracts. Equal source values do not re-evaluate this component.
 * The complete modifier chain stays on the actual component; the wrapper delegates parent data and owns the sibling key.
 * Keep sources and dedicated editing states outside observed callbacks. Evaluation and input failures follow ordinary runtime cleanup.
 */
@JvmName("TextAreaStatec0abf0512fec_1")
public fun UiScope.TextArea(
    state: TextAreaState,
    viewport: TextAreaViewport,
    enabled: StateSource<Boolean>,
    textStyle: TextStyle = TextStyle.TextField,
    wrap: TextWrap = TextWrap.Word,
    lineSpacing: Int = 0,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    emitObservedComponent(listOf(enabled), key) { values ->
        TextArea(
            state = state,
            viewport = viewport,
            enabled = values[0] as Boolean,
            textStyle = textStyle,
            wrap = wrap,
            lineSpacing = lineSpacing,
            modifier = modifier,
            key = null,
        )
    }
}

/**
 * Source-backed [TextArea] observing enabled at the next frame cutoff.
 * Sources remain caller-owned; compatible nodes retain editing, focus, and scrolling state.
 * Literal arguments keep their existing contracts. Equal source values do not re-evaluate this component.
 * The complete modifier chain stays on the actual component; the wrapper delegates parent data and owns the sibling key.
 * Keep sources and dedicated editing states outside observed callbacks. Evaluation and input failures follow ordinary runtime cleanup.
 */
@JvmName("TextAreaStatec701b9e2eaf6_1")
public fun UiScope.TextArea(
    state: TextAreaState,
    viewport: TextAreaViewport,
    font: ResourceId,
    enabled: StateSource<Boolean>,
    textStyle: TextStyle = TextStyle.TextField,
    wrap: TextWrap = TextWrap.Word,
    lineSpacing: Int = 0,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    emitObservedComponent(listOf(enabled), key) { values ->
        TextArea(
            state = state,
            viewport = viewport,
            font = font,
            enabled = values[0] as Boolean,
            textStyle = textStyle,
            wrap = wrap,
            lineSpacing = lineSpacing,
            modifier = modifier,
            key = null,
        )
    }
}

/**
 * Source-backed [Button] observing label at the next frame cutoff.
 * Sources remain caller-owned; compatible nodes retain editing, focus, and scrolling state.
 * Literal arguments keep their existing contracts. Equal source values do not re-evaluate this component.
 * The complete modifier chain stays on the actual component; the wrapper delegates parent data and owns the sibling key.
 * Keep sources and dedicated editing states outside observed callbacks. Evaluation and input failures follow ordinary runtime cleanup.
 */
@JvmName("ButtonStatecffa97b99dc2_1")
public fun UiScope.Button(
    label: StateSource<UiText>,
    width: Int = 150,
    enabled: Boolean = true,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    emitObservedComponent(listOf(label), key) { values ->
        Button(
            label = values[0] as UiText,
            width = width,
            enabled = enabled,
            modifier = modifier,
            key = null,
        )
    }
}

/**
 * Source-backed [Button] observing enabled at the next frame cutoff.
 * Sources remain caller-owned; compatible nodes retain editing, focus, and scrolling state.
 * Literal arguments keep their existing contracts. Equal source values do not re-evaluate this component.
 * The complete modifier chain stays on the actual component; the wrapper delegates parent data and owns the sibling key.
 * Keep sources and dedicated editing states outside observed callbacks. Evaluation and input failures follow ordinary runtime cleanup.
 */
@JvmName("ButtonStatecffa97b99dc2_2")
public fun UiScope.Button(
    label: UiText,
    width: Int = 150,
    enabled: StateSource<Boolean>,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    emitObservedComponent(listOf(enabled), key) { values ->
        Button(
            label = label,
            width = width,
            enabled = values[0] as Boolean,
            modifier = modifier,
            key = null,
        )
    }
}

/**
 * Source-backed [Button] observing label, enabled at the next frame cutoff.
 * Sources remain caller-owned; compatible nodes retain editing, focus, and scrolling state.
 * Literal arguments keep their existing contracts. Equal source values do not re-evaluate this component.
 * The complete modifier chain stays on the actual component; the wrapper delegates parent data and owns the sibling key.
 * Keep sources and dedicated editing states outside observed callbacks. Evaluation and input failures follow ordinary runtime cleanup.
 */
@JvmName("ButtonStatecffa97b99dc2_3")
public fun UiScope.Button(
    label: StateSource<UiText>,
    width: Int = 150,
    enabled: StateSource<Boolean>,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    emitObservedComponent(listOf(label, enabled), key) { values ->
        Button(
            label = values[0] as UiText,
            width = width,
            enabled = values[1] as Boolean,
            modifier = modifier,
            key = null,
        )
    }
}

/**
 * Source-backed [Button] observing label at the next frame cutoff.
 * Sources remain caller-owned; compatible nodes retain editing, focus, and scrolling state.
 * Literal arguments keep their existing contracts. Equal source values do not re-evaluate this component.
 * The complete modifier chain stays on the actual component; the wrapper delegates parent data and owns the sibling key.
 * Keep sources and dedicated editing states outside observed callbacks. Evaluation and input failures follow ordinary runtime cleanup.
 */
@JvmName("ButtonState6e1d7e05cd68_1")
public fun UiScope.Button(
    label: StateSource<String>,
    width: Int = 150,
    enabled: Boolean = true,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    emitObservedComponent(listOf(label), key) { values ->
        Button(
            label = values[0] as String,
            width = width,
            enabled = enabled,
            modifier = modifier,
            key = null,
        )
    }
}

/**
 * Source-backed [Button] observing enabled at the next frame cutoff.
 * Sources remain caller-owned; compatible nodes retain editing, focus, and scrolling state.
 * Literal arguments keep their existing contracts. Equal source values do not re-evaluate this component.
 * The complete modifier chain stays on the actual component; the wrapper delegates parent data and owns the sibling key.
 * Keep sources and dedicated editing states outside observed callbacks. Evaluation and input failures follow ordinary runtime cleanup.
 */
@JvmName("ButtonState6e1d7e05cd68_2")
public fun UiScope.Button(
    label: String,
    width: Int = 150,
    enabled: StateSource<Boolean>,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    emitObservedComponent(listOf(enabled), key) { values ->
        Button(
            label = label,
            width = width,
            enabled = values[0] as Boolean,
            modifier = modifier,
            key = null,
        )
    }
}

/**
 * Source-backed [Button] observing label, enabled at the next frame cutoff.
 * Sources remain caller-owned; compatible nodes retain editing, focus, and scrolling state.
 * Literal arguments keep their existing contracts. Equal source values do not re-evaluate this component.
 * The complete modifier chain stays on the actual component; the wrapper delegates parent data and owns the sibling key.
 * Keep sources and dedicated editing states outside observed callbacks. Evaluation and input failures follow ordinary runtime cleanup.
 */
@JvmName("ButtonState6e1d7e05cd68_3")
public fun UiScope.Button(
    label: StateSource<String>,
    width: Int = 150,
    enabled: StateSource<Boolean>,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    emitObservedComponent(listOf(label, enabled), key) { values ->
        Button(
            label = values[0] as String,
            width = width,
            enabled = values[1] as Boolean,
            modifier = modifier,
            key = null,
        )
    }
}

/**
 * Source-backed [Tab] observing label at the next frame cutoff.
 * Sources remain caller-owned; compatible nodes retain editing, focus, and scrolling state.
 * Literal arguments keep their existing contracts. Equal source values do not re-evaluate this component.
 * The complete modifier chain stays on the actual component; the wrapper delegates parent data and owns the sibling key.
 * Keep sources and dedicated editing states outside observed callbacks. Evaluation and input failures follow ordinary runtime cleanup.
 */
@JvmName("TabState58ed18680f25_1")
public fun UiScope.Tab(
    label: StateSource<UiText>,
    selected: Boolean,
    width: Int = 150,
    enabled: Boolean = true,
    indicator: TabSelectionIndicator = TabSelectionIndicator.Underline,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    emitObservedComponent(listOf(label), key) { values ->
        Tab(
            label = values[0] as UiText,
            selected = selected,
            width = width,
            enabled = enabled,
            indicator = indicator,
            modifier = modifier,
            key = null,
        )
    }
}

/**
 * Source-backed [Tab] observing selected at the next frame cutoff.
 * Sources remain caller-owned; compatible nodes retain editing, focus, and scrolling state.
 * Literal arguments keep their existing contracts. Equal source values do not re-evaluate this component.
 * The complete modifier chain stays on the actual component; the wrapper delegates parent data and owns the sibling key.
 * Keep sources and dedicated editing states outside observed callbacks. Evaluation and input failures follow ordinary runtime cleanup.
 */
@JvmName("TabState58ed18680f25_2")
public fun UiScope.Tab(
    label: UiText,
    selected: StateSource<Boolean>,
    width: Int = 150,
    enabled: Boolean = true,
    indicator: TabSelectionIndicator = TabSelectionIndicator.Underline,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    emitObservedComponent(listOf(selected), key) { values ->
        Tab(
            label = label,
            selected = values[0] as Boolean,
            width = width,
            enabled = enabled,
            indicator = indicator,
            modifier = modifier,
            key = null,
        )
    }
}

/**
 * Source-backed [Tab] observing label, selected at the next frame cutoff.
 * Sources remain caller-owned; compatible nodes retain editing, focus, and scrolling state.
 * Literal arguments keep their existing contracts. Equal source values do not re-evaluate this component.
 * The complete modifier chain stays on the actual component; the wrapper delegates parent data and owns the sibling key.
 * Keep sources and dedicated editing states outside observed callbacks. Evaluation and input failures follow ordinary runtime cleanup.
 */
@JvmName("TabState58ed18680f25_3")
public fun UiScope.Tab(
    label: StateSource<UiText>,
    selected: StateSource<Boolean>,
    width: Int = 150,
    enabled: Boolean = true,
    indicator: TabSelectionIndicator = TabSelectionIndicator.Underline,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    emitObservedComponent(listOf(label, selected), key) { values ->
        Tab(
            label = values[0] as UiText,
            selected = values[1] as Boolean,
            width = width,
            enabled = enabled,
            indicator = indicator,
            modifier = modifier,
            key = null,
        )
    }
}

/**
 * Source-backed [Tab] observing enabled at the next frame cutoff.
 * Sources remain caller-owned; compatible nodes retain editing, focus, and scrolling state.
 * Literal arguments keep their existing contracts. Equal source values do not re-evaluate this component.
 * The complete modifier chain stays on the actual component; the wrapper delegates parent data and owns the sibling key.
 * Keep sources and dedicated editing states outside observed callbacks. Evaluation and input failures follow ordinary runtime cleanup.
 */
@JvmName("TabState58ed18680f25_4")
public fun UiScope.Tab(
    label: UiText,
    selected: Boolean,
    width: Int = 150,
    enabled: StateSource<Boolean>,
    indicator: TabSelectionIndicator = TabSelectionIndicator.Underline,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    emitObservedComponent(listOf(enabled), key) { values ->
        Tab(
            label = label,
            selected = selected,
            width = width,
            enabled = values[0] as Boolean,
            indicator = indicator,
            modifier = modifier,
            key = null,
        )
    }
}

/**
 * Source-backed [Tab] observing label, enabled at the next frame cutoff.
 * Sources remain caller-owned; compatible nodes retain editing, focus, and scrolling state.
 * Literal arguments keep their existing contracts. Equal source values do not re-evaluate this component.
 * The complete modifier chain stays on the actual component; the wrapper delegates parent data and owns the sibling key.
 * Keep sources and dedicated editing states outside observed callbacks. Evaluation and input failures follow ordinary runtime cleanup.
 */
@JvmName("TabState58ed18680f25_5")
public fun UiScope.Tab(
    label: StateSource<UiText>,
    selected: Boolean,
    width: Int = 150,
    enabled: StateSource<Boolean>,
    indicator: TabSelectionIndicator = TabSelectionIndicator.Underline,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    emitObservedComponent(listOf(label, enabled), key) { values ->
        Tab(
            label = values[0] as UiText,
            selected = selected,
            width = width,
            enabled = values[1] as Boolean,
            indicator = indicator,
            modifier = modifier,
            key = null,
        )
    }
}

/**
 * Source-backed [Tab] observing selected, enabled at the next frame cutoff.
 * Sources remain caller-owned; compatible nodes retain editing, focus, and scrolling state.
 * Literal arguments keep their existing contracts. Equal source values do not re-evaluate this component.
 * The complete modifier chain stays on the actual component; the wrapper delegates parent data and owns the sibling key.
 * Keep sources and dedicated editing states outside observed callbacks. Evaluation and input failures follow ordinary runtime cleanup.
 */
@JvmName("TabState58ed18680f25_6")
public fun UiScope.Tab(
    label: UiText,
    selected: StateSource<Boolean>,
    width: Int = 150,
    enabled: StateSource<Boolean>,
    indicator: TabSelectionIndicator = TabSelectionIndicator.Underline,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    emitObservedComponent(listOf(selected, enabled), key) { values ->
        Tab(
            label = label,
            selected = values[0] as Boolean,
            width = width,
            enabled = values[1] as Boolean,
            indicator = indicator,
            modifier = modifier,
            key = null,
        )
    }
}

/**
 * Source-backed [Tab] observing label, selected, enabled at the next frame cutoff.
 * Sources remain caller-owned; compatible nodes retain editing, focus, and scrolling state.
 * Literal arguments keep their existing contracts. Equal source values do not re-evaluate this component.
 * The complete modifier chain stays on the actual component; the wrapper delegates parent data and owns the sibling key.
 * Keep sources and dedicated editing states outside observed callbacks. Evaluation and input failures follow ordinary runtime cleanup.
 */
@JvmName("TabState58ed18680f25_7")
public fun UiScope.Tab(
    label: StateSource<UiText>,
    selected: StateSource<Boolean>,
    width: Int = 150,
    enabled: StateSource<Boolean>,
    indicator: TabSelectionIndicator = TabSelectionIndicator.Underline,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    emitObservedComponent(listOf(label, selected, enabled), key) { values ->
        Tab(
            label = values[0] as UiText,
            selected = values[1] as Boolean,
            width = width,
            enabled = values[2] as Boolean,
            indicator = indicator,
            modifier = modifier,
            key = null,
        )
    }
}

/**
 * Source-backed [Tab] observing label at the next frame cutoff.
 * Sources remain caller-owned; compatible nodes retain editing, focus, and scrolling state.
 * Literal arguments keep their existing contracts. Equal source values do not re-evaluate this component.
 * The complete modifier chain stays on the actual component; the wrapper delegates parent data and owns the sibling key.
 * Keep sources and dedicated editing states outside observed callbacks. Evaluation and input failures follow ordinary runtime cleanup.
 */
@JvmName("TabState06dab4066e27_1")
public fun UiScope.Tab(
    label: StateSource<String>,
    selected: Boolean,
    width: Int = 150,
    enabled: Boolean = true,
    indicator: TabSelectionIndicator = TabSelectionIndicator.Underline,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    emitObservedComponent(listOf(label), key) { values ->
        Tab(
            label = values[0] as String,
            selected = selected,
            width = width,
            enabled = enabled,
            indicator = indicator,
            modifier = modifier,
            key = null,
        )
    }
}

/**
 * Source-backed [Tab] observing selected at the next frame cutoff.
 * Sources remain caller-owned; compatible nodes retain editing, focus, and scrolling state.
 * Literal arguments keep their existing contracts. Equal source values do not re-evaluate this component.
 * The complete modifier chain stays on the actual component; the wrapper delegates parent data and owns the sibling key.
 * Keep sources and dedicated editing states outside observed callbacks. Evaluation and input failures follow ordinary runtime cleanup.
 */
@JvmName("TabState06dab4066e27_2")
public fun UiScope.Tab(
    label: String,
    selected: StateSource<Boolean>,
    width: Int = 150,
    enabled: Boolean = true,
    indicator: TabSelectionIndicator = TabSelectionIndicator.Underline,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    emitObservedComponent(listOf(selected), key) { values ->
        Tab(
            label = label,
            selected = values[0] as Boolean,
            width = width,
            enabled = enabled,
            indicator = indicator,
            modifier = modifier,
            key = null,
        )
    }
}

/**
 * Source-backed [Tab] observing label, selected at the next frame cutoff.
 * Sources remain caller-owned; compatible nodes retain editing, focus, and scrolling state.
 * Literal arguments keep their existing contracts. Equal source values do not re-evaluate this component.
 * The complete modifier chain stays on the actual component; the wrapper delegates parent data and owns the sibling key.
 * Keep sources and dedicated editing states outside observed callbacks. Evaluation and input failures follow ordinary runtime cleanup.
 */
@JvmName("TabState06dab4066e27_3")
public fun UiScope.Tab(
    label: StateSource<String>,
    selected: StateSource<Boolean>,
    width: Int = 150,
    enabled: Boolean = true,
    indicator: TabSelectionIndicator = TabSelectionIndicator.Underline,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    emitObservedComponent(listOf(label, selected), key) { values ->
        Tab(
            label = values[0] as String,
            selected = values[1] as Boolean,
            width = width,
            enabled = enabled,
            indicator = indicator,
            modifier = modifier,
            key = null,
        )
    }
}

/**
 * Source-backed [Tab] observing enabled at the next frame cutoff.
 * Sources remain caller-owned; compatible nodes retain editing, focus, and scrolling state.
 * Literal arguments keep their existing contracts. Equal source values do not re-evaluate this component.
 * The complete modifier chain stays on the actual component; the wrapper delegates parent data and owns the sibling key.
 * Keep sources and dedicated editing states outside observed callbacks. Evaluation and input failures follow ordinary runtime cleanup.
 */
@JvmName("TabState06dab4066e27_4")
public fun UiScope.Tab(
    label: String,
    selected: Boolean,
    width: Int = 150,
    enabled: StateSource<Boolean>,
    indicator: TabSelectionIndicator = TabSelectionIndicator.Underline,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    emitObservedComponent(listOf(enabled), key) { values ->
        Tab(
            label = label,
            selected = selected,
            width = width,
            enabled = values[0] as Boolean,
            indicator = indicator,
            modifier = modifier,
            key = null,
        )
    }
}

/**
 * Source-backed [Tab] observing label, enabled at the next frame cutoff.
 * Sources remain caller-owned; compatible nodes retain editing, focus, and scrolling state.
 * Literal arguments keep their existing contracts. Equal source values do not re-evaluate this component.
 * The complete modifier chain stays on the actual component; the wrapper delegates parent data and owns the sibling key.
 * Keep sources and dedicated editing states outside observed callbacks. Evaluation and input failures follow ordinary runtime cleanup.
 */
@JvmName("TabState06dab4066e27_5")
public fun UiScope.Tab(
    label: StateSource<String>,
    selected: Boolean,
    width: Int = 150,
    enabled: StateSource<Boolean>,
    indicator: TabSelectionIndicator = TabSelectionIndicator.Underline,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    emitObservedComponent(listOf(label, enabled), key) { values ->
        Tab(
            label = values[0] as String,
            selected = selected,
            width = width,
            enabled = values[1] as Boolean,
            indicator = indicator,
            modifier = modifier,
            key = null,
        )
    }
}

/**
 * Source-backed [Tab] observing selected, enabled at the next frame cutoff.
 * Sources remain caller-owned; compatible nodes retain editing, focus, and scrolling state.
 * Literal arguments keep their existing contracts. Equal source values do not re-evaluate this component.
 * The complete modifier chain stays on the actual component; the wrapper delegates parent data and owns the sibling key.
 * Keep sources and dedicated editing states outside observed callbacks. Evaluation and input failures follow ordinary runtime cleanup.
 */
@JvmName("TabState06dab4066e27_6")
public fun UiScope.Tab(
    label: String,
    selected: StateSource<Boolean>,
    width: Int = 150,
    enabled: StateSource<Boolean>,
    indicator: TabSelectionIndicator = TabSelectionIndicator.Underline,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    emitObservedComponent(listOf(selected, enabled), key) { values ->
        Tab(
            label = label,
            selected = values[0] as Boolean,
            width = width,
            enabled = values[1] as Boolean,
            indicator = indicator,
            modifier = modifier,
            key = null,
        )
    }
}

/**
 * Source-backed [Tab] observing label, selected, enabled at the next frame cutoff.
 * Sources remain caller-owned; compatible nodes retain editing, focus, and scrolling state.
 * Literal arguments keep their existing contracts. Equal source values do not re-evaluate this component.
 * The complete modifier chain stays on the actual component; the wrapper delegates parent data and owns the sibling key.
 * Keep sources and dedicated editing states outside observed callbacks. Evaluation and input failures follow ordinary runtime cleanup.
 */
@JvmName("TabState06dab4066e27_7")
public fun UiScope.Tab(
    label: StateSource<String>,
    selected: StateSource<Boolean>,
    width: Int = 150,
    enabled: StateSource<Boolean>,
    indicator: TabSelectionIndicator = TabSelectionIndicator.Underline,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    emitObservedComponent(listOf(label, selected, enabled), key) { values ->
        Tab(
            label = values[0] as String,
            selected = values[1] as Boolean,
            width = width,
            enabled = values[2] as Boolean,
            indicator = indicator,
            modifier = modifier,
            key = null,
        )
    }
}

/**
 * Source-backed [TextField] observing enabled at the next frame cutoff.
 * Sources remain caller-owned; compatible nodes retain editing, focus, and scrolling state.
 * Literal arguments keep their existing contracts. Equal source values do not re-evaluate this component.
 * The complete modifier chain stays on the actual component; the wrapper delegates parent data and owns the sibling key.
 * Keep sources and dedicated editing states outside observed callbacks. Evaluation and input failures follow ordinary runtime cleanup.
 */
@JvmName("TextFieldState8ebce6a07628_1")
public fun UiScope.TextField(
    state: TextFieldState,
    appearance: TextInputAppearance,
    enabled: StateSource<Boolean>,
    textStyle: TextStyle = TextStyle.TextField,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    emitObservedComponent(listOf(enabled), key) { values ->
        TextField(
            state = state,
            appearance = appearance,
            enabled = values[0] as Boolean,
            textStyle = textStyle,
            modifier = modifier,
            key = null,
        )
    }
}

/**
 * Source-backed [TextField] observing enabled at the next frame cutoff.
 * Sources remain caller-owned; compatible nodes retain editing, focus, and scrolling state.
 * Literal arguments keep their existing contracts. Equal source values do not re-evaluate this component.
 * The complete modifier chain stays on the actual component; the wrapper delegates parent data and owns the sibling key.
 * Keep sources and dedicated editing states outside observed callbacks. Evaluation and input failures follow ordinary runtime cleanup.
 */
@JvmName("TextFieldState68d5823f42d7_1")
public fun UiScope.TextField(
    state: TextFieldState,
    appearance: TextInputAppearance,
    size: IntSize,
    enabled: StateSource<Boolean>,
    textStyle: TextStyle = TextStyle.TextField,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    emitObservedComponent(listOf(enabled), key) { values ->
        TextField(
            state = state,
            appearance = appearance,
            size = size,
            enabled = values[0] as Boolean,
            textStyle = textStyle,
            modifier = modifier,
            key = null,
        )
    }
}

/**
 * Source-backed [TextField] observing enabled at the next frame cutoff.
 * Sources remain caller-owned; compatible nodes retain editing, focus, and scrolling state.
 * Literal arguments keep their existing contracts. Equal source values do not re-evaluate this component.
 * The complete modifier chain stays on the actual component; the wrapper delegates parent data and owns the sibling key.
 * Keep sources and dedicated editing states outside observed callbacks. Evaluation and input failures follow ordinary runtime cleanup.
 */
@JvmName("TextFieldState715dafc3f527_1")
public fun UiScope.TextField(
    state: TextFieldState,
    appearance: TextInputAppearance,
    font: ResourceId,
    enabled: StateSource<Boolean>,
    textStyle: TextStyle = TextStyle.TextField,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    emitObservedComponent(listOf(enabled), key) { values ->
        TextField(
            state = state,
            appearance = appearance,
            font = font,
            enabled = values[0] as Boolean,
            textStyle = textStyle,
            modifier = modifier,
            key = null,
        )
    }
}

/**
 * Source-backed [TextField] observing enabled at the next frame cutoff.
 * Sources remain caller-owned; compatible nodes retain editing, focus, and scrolling state.
 * Literal arguments keep their existing contracts. Equal source values do not re-evaluate this component.
 * The complete modifier chain stays on the actual component; the wrapper delegates parent data and owns the sibling key.
 * Keep sources and dedicated editing states outside observed callbacks. Evaluation and input failures follow ordinary runtime cleanup.
 */
@JvmName("TextFieldStatefd7b3be167e7_1")
public fun UiScope.TextField(
    state: TextFieldState,
    appearance: TextInputAppearance,
    size: IntSize,
    font: ResourceId,
    enabled: StateSource<Boolean>,
    textStyle: TextStyle = TextStyle.TextField,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    emitObservedComponent(listOf(enabled), key) { values ->
        TextField(
            state = state,
            appearance = appearance,
            size = size,
            font = font,
            enabled = values[0] as Boolean,
            textStyle = textStyle,
            modifier = modifier,
            key = null,
        )
    }
}

/**
 * Source-backed [TextArea] observing enabled at the next frame cutoff.
 * Sources remain caller-owned; compatible nodes retain editing, focus, and scrolling state.
 * Literal arguments keep their existing contracts. Equal source values do not re-evaluate this component.
 * The complete modifier chain stays on the actual component; the wrapper delegates parent data and owns the sibling key.
 * Keep sources and dedicated editing states outside observed callbacks. Evaluation and input failures follow ordinary runtime cleanup.
 */
@JvmName("TextAreaState80c0b5b4cb37_1")
public fun UiScope.TextArea(
    state: TextAreaState,
    appearance: TextInputAppearance,
    viewport: TextAreaViewport,
    enabled: StateSource<Boolean>,
    textStyle: TextStyle = TextStyle.TextField,
    wrap: TextWrap = TextWrap.Word,
    lineSpacing: Int = 0,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    emitObservedComponent(listOf(enabled), key) { values ->
        TextArea(
            state = state,
            appearance = appearance,
            viewport = viewport,
            enabled = values[0] as Boolean,
            textStyle = textStyle,
            wrap = wrap,
            lineSpacing = lineSpacing,
            modifier = modifier,
            key = null,
        )
    }
}

/**
 * Source-backed [TextArea] observing enabled at the next frame cutoff.
 * Sources remain caller-owned; compatible nodes retain editing, focus, and scrolling state.
 * Literal arguments keep their existing contracts. Equal source values do not re-evaluate this component.
 * The complete modifier chain stays on the actual component; the wrapper delegates parent data and owns the sibling key.
 * Keep sources and dedicated editing states outside observed callbacks. Evaluation and input failures follow ordinary runtime cleanup.
 */
@JvmName("TextAreaState4da1faac4769_1")
public fun UiScope.TextArea(
    state: TextAreaState,
    appearance: TextInputAppearance,
    viewport: TextAreaViewport,
    font: ResourceId,
    enabled: StateSource<Boolean>,
    textStyle: TextStyle = TextStyle.TextField,
    wrap: TextWrap = TextWrap.Word,
    lineSpacing: Int = 0,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    emitObservedComponent(listOf(enabled), key) { values ->
        TextArea(
            state = state,
            appearance = appearance,
            viewport = viewport,
            font = font,
            enabled = values[0] as Boolean,
            textStyle = textStyle,
            wrap = wrap,
            lineSpacing = lineSpacing,
            modifier = modifier,
            key = null,
        )
    }
}

/**
 * Source-backed [Canvas] observing source at the next frame cutoff.
 * Sources remain caller-owned; compatible nodes retain editing, focus, and scrolling state.
 * Literal arguments keep their existing contracts. Equal source values do not re-evaluate this component.
 * The complete modifier chain stays on the actual component; the wrapper delegates parent data and owns the sibling key.
 * Keep sources and dedicated editing states outside observed callbacks. Evaluation and input failures follow ordinary runtime cleanup.
 */
@JvmName("CanvasState7047d39d3483_1")
public fun UiScope.Canvas(
    source: StateSource<CanvasSource>,
    size: IntSize,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    emitObservedComponent(listOf(source), key) { values ->
        Canvas(
            source = values[0] as CanvasSource,
            size = size,
            modifier = modifier,
            key = null,
        )
    }
}

/**
 * Source-backed [TiledImage] observing source at the next frame cutoff.
 * Sources remain caller-owned; compatible nodes retain editing, focus, and scrolling state.
 * Literal arguments keep their existing contracts. Equal source values do not re-evaluate this component.
 * The complete modifier chain stays on the actual component; the wrapper delegates parent data and owns the sibling key.
 * Keep sources and dedicated editing states outside observed callbacks. Evaluation and input failures follow ordinary runtime cleanup.
 */
@JvmName("TiledImageState06558dbd1f3e_1")
public fun UiScope.TiledImage(
    source: StateSource<TiledImageSource>,
    state: PanZoomState,
    size: IntSize,
    fit: PanZoomFit = PanZoomFit.Contain,
    cachePolicy: TiledImageCachePolicy = TiledImageCachePolicy.Default,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
    content: TiledImageScope.() -> Unit = {},
) {
    emitObservedComponent(listOf(source), key) { values ->
        TiledImage(
            source = values[0] as TiledImageSource,
            state = state,
            size = size,
            fit = fit,
            cachePolicy = cachePolicy,
            modifier = modifier,
            key = null,
            content = content,
        )
    }
}

/**
 * Source-backed [VirtualList] observing canLoadLeading at the next frame cutoff.
 * Sources remain caller-owned; compatible nodes retain editing, focus, and scrolling state.
 * Literal arguments keep their existing contracts. Equal source values do not re-evaluate this component.
 * The complete modifier chain stays on the actual component; the wrapper delegates parent data and owns the sibling key.
 * Keep sources and dedicated editing states outside observed callbacks. Evaluation and input failures follow ordinary runtime cleanup.
 */
@JvmName("VirtualListState7e3481099f80_1")
public fun <T : Any, K : Any> UiScope.VirtualList(
    itemCount: Int,
    itemAt: (Int) -> T,
    keyAt: (Int) -> K,
    state: VirtualListState<K>,
    viewportSize: IntSize,
    rowHeight: Int,
    indexOfKey: (K) -> Int? = { target -> (0 until itemCount).firstOrNull { index -> keyAt(index) == target } },
    scrollRate: Int = 10,
    canLoadLeading: StateSource<Boolean>,
    canLoadTrailing: Boolean = false,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
    content: UiScope.(T) -> Unit,
) {
    emitObservedComponent(listOf(canLoadLeading), key) { values ->
        VirtualList(
            itemCount = itemCount,
            itemAt = itemAt,
            keyAt = keyAt,
            state = state,
            viewportSize = viewportSize,
            rowHeight = rowHeight,
            indexOfKey = indexOfKey,
            scrollRate = scrollRate,
            canLoadLeading = values[0] as Boolean,
            canLoadTrailing = canLoadTrailing,
            modifier = modifier,
            key = null,
            content = content,
        )
    }
}

/**
 * Source-backed [VirtualList] observing canLoadTrailing at the next frame cutoff.
 * Sources remain caller-owned; compatible nodes retain editing, focus, and scrolling state.
 * Literal arguments keep their existing contracts. Equal source values do not re-evaluate this component.
 * The complete modifier chain stays on the actual component; the wrapper delegates parent data and owns the sibling key.
 * Keep sources and dedicated editing states outside observed callbacks. Evaluation and input failures follow ordinary runtime cleanup.
 */
@JvmName("VirtualListState7e3481099f80_2")
public fun <T : Any, K : Any> UiScope.VirtualList(
    itemCount: Int,
    itemAt: (Int) -> T,
    keyAt: (Int) -> K,
    state: VirtualListState<K>,
    viewportSize: IntSize,
    rowHeight: Int,
    indexOfKey: (K) -> Int? = { target -> (0 until itemCount).firstOrNull { index -> keyAt(index) == target } },
    scrollRate: Int = 10,
    canLoadLeading: Boolean = false,
    canLoadTrailing: StateSource<Boolean>,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
    content: UiScope.(T) -> Unit,
) {
    emitObservedComponent(listOf(canLoadTrailing), key) { values ->
        VirtualList(
            itemCount = itemCount,
            itemAt = itemAt,
            keyAt = keyAt,
            state = state,
            viewportSize = viewportSize,
            rowHeight = rowHeight,
            indexOfKey = indexOfKey,
            scrollRate = scrollRate,
            canLoadLeading = canLoadLeading,
            canLoadTrailing = values[0] as Boolean,
            modifier = modifier,
            key = null,
            content = content,
        )
    }
}

/**
 * Source-backed [VirtualList] observing canLoadLeading, canLoadTrailing at the next frame cutoff.
 * Sources remain caller-owned; compatible nodes retain editing, focus, and scrolling state.
 * Literal arguments keep their existing contracts. Equal source values do not re-evaluate this component.
 * The complete modifier chain stays on the actual component; the wrapper delegates parent data and owns the sibling key.
 * Keep sources and dedicated editing states outside observed callbacks. Evaluation and input failures follow ordinary runtime cleanup.
 */
@JvmName("VirtualListState7e3481099f80_3")
public fun <T : Any, K : Any> UiScope.VirtualList(
    itemCount: Int,
    itemAt: (Int) -> T,
    keyAt: (Int) -> K,
    state: VirtualListState<K>,
    viewportSize: IntSize,
    rowHeight: Int,
    indexOfKey: (K) -> Int? = { target -> (0 until itemCount).firstOrNull { index -> keyAt(index) == target } },
    scrollRate: Int = 10,
    canLoadLeading: StateSource<Boolean>,
    canLoadTrailing: StateSource<Boolean>,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
    content: UiScope.(T) -> Unit,
) {
    emitObservedComponent(listOf(canLoadLeading, canLoadTrailing), key) { values ->
        VirtualList(
            itemCount = itemCount,
            itemAt = itemAt,
            keyAt = keyAt,
            state = state,
            viewportSize = viewportSize,
            rowHeight = rowHeight,
            indexOfKey = indexOfKey,
            scrollRate = scrollRate,
            canLoadLeading = values[0] as Boolean,
            canLoadTrailing = values[1] as Boolean,
            modifier = modifier,
            key = null,
            content = content,
        )
    }
}

/**
 * Source-backed [VirtualList] observing canLoadLeading at the next frame cutoff.
 * Sources remain caller-owned; compatible nodes retain editing, focus, and scrolling state.
 * Literal arguments keep their existing contracts. Equal source values do not re-evaluate this component.
 * The complete modifier chain stays on the actual component; the wrapper delegates parent data and owns the sibling key.
 * Keep sources and dedicated editing states outside observed callbacks. Evaluation and input failures follow ordinary runtime cleanup.
 */
@JvmName("VirtualListState4013cecb450b_1")
public fun <T : Any, K : Any> UiScope.VirtualList(
    itemCount: () -> Int,
    itemAt: (Int) -> T,
    keyAt: (Int) -> K,
    state: VirtualListState<K>,
    viewportSize: IntSize,
    rowHeight: Int,
    indexOfKey: ((K) -> Int?)? = null,
    scrollRate: Int = 10,
    canLoadLeading: StateSource<Boolean>,
    canLoadTrailing: Boolean = false,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
    content: UiScope.(T) -> Unit,
) {
    emitObservedComponent(listOf(canLoadLeading), key) { values ->
        VirtualList(
            itemCount = itemCount,
            itemAt = itemAt,
            keyAt = keyAt,
            state = state,
            viewportSize = viewportSize,
            rowHeight = rowHeight,
            indexOfKey = indexOfKey,
            scrollRate = scrollRate,
            canLoadLeading = values[0] as Boolean,
            canLoadTrailing = canLoadTrailing,
            modifier = modifier,
            key = null,
            content = content,
        )
    }
}

/**
 * Source-backed [VirtualList] observing canLoadTrailing at the next frame cutoff.
 * Sources remain caller-owned; compatible nodes retain editing, focus, and scrolling state.
 * Literal arguments keep their existing contracts. Equal source values do not re-evaluate this component.
 * The complete modifier chain stays on the actual component; the wrapper delegates parent data and owns the sibling key.
 * Keep sources and dedicated editing states outside observed callbacks. Evaluation and input failures follow ordinary runtime cleanup.
 */
@JvmName("VirtualListState4013cecb450b_2")
public fun <T : Any, K : Any> UiScope.VirtualList(
    itemCount: () -> Int,
    itemAt: (Int) -> T,
    keyAt: (Int) -> K,
    state: VirtualListState<K>,
    viewportSize: IntSize,
    rowHeight: Int,
    indexOfKey: ((K) -> Int?)? = null,
    scrollRate: Int = 10,
    canLoadLeading: Boolean = false,
    canLoadTrailing: StateSource<Boolean>,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
    content: UiScope.(T) -> Unit,
) {
    emitObservedComponent(listOf(canLoadTrailing), key) { values ->
        VirtualList(
            itemCount = itemCount,
            itemAt = itemAt,
            keyAt = keyAt,
            state = state,
            viewportSize = viewportSize,
            rowHeight = rowHeight,
            indexOfKey = indexOfKey,
            scrollRate = scrollRate,
            canLoadLeading = canLoadLeading,
            canLoadTrailing = values[0] as Boolean,
            modifier = modifier,
            key = null,
            content = content,
        )
    }
}

/**
 * Source-backed [VirtualList] observing canLoadLeading, canLoadTrailing at the next frame cutoff.
 * Sources remain caller-owned; compatible nodes retain editing, focus, and scrolling state.
 * Literal arguments keep their existing contracts. Equal source values do not re-evaluate this component.
 * The complete modifier chain stays on the actual component; the wrapper delegates parent data and owns the sibling key.
 * Keep sources and dedicated editing states outside observed callbacks. Evaluation and input failures follow ordinary runtime cleanup.
 */
@JvmName("VirtualListState4013cecb450b_3")
public fun <T : Any, K : Any> UiScope.VirtualList(
    itemCount: () -> Int,
    itemAt: (Int) -> T,
    keyAt: (Int) -> K,
    state: VirtualListState<K>,
    viewportSize: IntSize,
    rowHeight: Int,
    indexOfKey: ((K) -> Int?)? = null,
    scrollRate: Int = 10,
    canLoadLeading: StateSource<Boolean>,
    canLoadTrailing: StateSource<Boolean>,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
    content: UiScope.(T) -> Unit,
) {
    emitObservedComponent(listOf(canLoadLeading, canLoadTrailing), key) { values ->
        VirtualList(
            itemCount = itemCount,
            itemAt = itemAt,
            keyAt = keyAt,
            state = state,
            viewportSize = viewportSize,
            rowHeight = rowHeight,
            indexOfKey = indexOfKey,
            scrollRate = scrollRate,
            canLoadLeading = values[0] as Boolean,
            canLoadTrailing = values[1] as Boolean,
            modifier = modifier,
            key = null,
            content = content,
        )
    }
}

/**
 * Source-backed [VirtualList] observing items at the next frame cutoff.
 * Sources remain caller-owned; compatible nodes retain editing, focus, and scrolling state.
 * Literal arguments keep their existing contracts. Equal source values do not re-evaluate this component.
 * The complete modifier chain stays on the actual component; the wrapper delegates parent data and owns the sibling key.
 * Keep sources and dedicated editing states outside observed callbacks. Evaluation and input failures follow ordinary runtime cleanup.
 */
@JvmName("VirtualListState91e435daa5f9_1")
public fun <T : Any, K : Any> UiScope.VirtualList(
    items: StateSource<List<T>>,
    keyOf: (T) -> K,
    state: VirtualListState<K>,
    viewportSize: IntSize,
    rowHeight: Int,
    scrollRate: Int = 10,
    canLoadLeading: Boolean = false,
    canLoadTrailing: Boolean = false,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
    content: UiScope.(T) -> Unit,
) {
    emitObservedComponent(listOf(items), key) { values ->
        VirtualList(
            items = values[0] as List<T>,
            keyOf = keyOf,
            state = state,
            viewportSize = viewportSize,
            rowHeight = rowHeight,
            scrollRate = scrollRate,
            canLoadLeading = canLoadLeading,
            canLoadTrailing = canLoadTrailing,
            modifier = modifier,
            key = null,
            content = content,
        )
    }
}

/**
 * Source-backed [VirtualList] observing canLoadLeading at the next frame cutoff.
 * Sources remain caller-owned; compatible nodes retain editing, focus, and scrolling state.
 * Literal arguments keep their existing contracts. Equal source values do not re-evaluate this component.
 * The complete modifier chain stays on the actual component; the wrapper delegates parent data and owns the sibling key.
 * Keep sources and dedicated editing states outside observed callbacks. Evaluation and input failures follow ordinary runtime cleanup.
 */
@JvmName("VirtualListState91e435daa5f9_2")
public fun <T : Any, K : Any> UiScope.VirtualList(
    items: List<T>,
    keyOf: (T) -> K,
    state: VirtualListState<K>,
    viewportSize: IntSize,
    rowHeight: Int,
    scrollRate: Int = 10,
    canLoadLeading: StateSource<Boolean>,
    canLoadTrailing: Boolean = false,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
    content: UiScope.(T) -> Unit,
) {
    emitObservedComponent(listOf(canLoadLeading), key) { values ->
        VirtualList(
            items = items,
            keyOf = keyOf,
            state = state,
            viewportSize = viewportSize,
            rowHeight = rowHeight,
            scrollRate = scrollRate,
            canLoadLeading = values[0] as Boolean,
            canLoadTrailing = canLoadTrailing,
            modifier = modifier,
            key = null,
            content = content,
        )
    }
}

/**
 * Source-backed [VirtualList] observing items, canLoadLeading at the next frame cutoff.
 * Sources remain caller-owned; compatible nodes retain editing, focus, and scrolling state.
 * Literal arguments keep their existing contracts. Equal source values do not re-evaluate this component.
 * The complete modifier chain stays on the actual component; the wrapper delegates parent data and owns the sibling key.
 * Keep sources and dedicated editing states outside observed callbacks. Evaluation and input failures follow ordinary runtime cleanup.
 */
@JvmName("VirtualListState91e435daa5f9_3")
public fun <T : Any, K : Any> UiScope.VirtualList(
    items: StateSource<List<T>>,
    keyOf: (T) -> K,
    state: VirtualListState<K>,
    viewportSize: IntSize,
    rowHeight: Int,
    scrollRate: Int = 10,
    canLoadLeading: StateSource<Boolean>,
    canLoadTrailing: Boolean = false,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
    content: UiScope.(T) -> Unit,
) {
    emitObservedComponent(listOf(items, canLoadLeading), key) { values ->
        VirtualList(
            items = values[0] as List<T>,
            keyOf = keyOf,
            state = state,
            viewportSize = viewportSize,
            rowHeight = rowHeight,
            scrollRate = scrollRate,
            canLoadLeading = values[1] as Boolean,
            canLoadTrailing = canLoadTrailing,
            modifier = modifier,
            key = null,
            content = content,
        )
    }
}

/**
 * Source-backed [VirtualList] observing canLoadTrailing at the next frame cutoff.
 * Sources remain caller-owned; compatible nodes retain editing, focus, and scrolling state.
 * Literal arguments keep their existing contracts. Equal source values do not re-evaluate this component.
 * The complete modifier chain stays on the actual component; the wrapper delegates parent data and owns the sibling key.
 * Keep sources and dedicated editing states outside observed callbacks. Evaluation and input failures follow ordinary runtime cleanup.
 */
@JvmName("VirtualListState91e435daa5f9_4")
public fun <T : Any, K : Any> UiScope.VirtualList(
    items: List<T>,
    keyOf: (T) -> K,
    state: VirtualListState<K>,
    viewportSize: IntSize,
    rowHeight: Int,
    scrollRate: Int = 10,
    canLoadLeading: Boolean = false,
    canLoadTrailing: StateSource<Boolean>,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
    content: UiScope.(T) -> Unit,
) {
    emitObservedComponent(listOf(canLoadTrailing), key) { values ->
        VirtualList(
            items = items,
            keyOf = keyOf,
            state = state,
            viewportSize = viewportSize,
            rowHeight = rowHeight,
            scrollRate = scrollRate,
            canLoadLeading = canLoadLeading,
            canLoadTrailing = values[0] as Boolean,
            modifier = modifier,
            key = null,
            content = content,
        )
    }
}

/**
 * Source-backed [VirtualList] observing items, canLoadTrailing at the next frame cutoff.
 * Sources remain caller-owned; compatible nodes retain editing, focus, and scrolling state.
 * Literal arguments keep their existing contracts. Equal source values do not re-evaluate this component.
 * The complete modifier chain stays on the actual component; the wrapper delegates parent data and owns the sibling key.
 * Keep sources and dedicated editing states outside observed callbacks. Evaluation and input failures follow ordinary runtime cleanup.
 */
@JvmName("VirtualListState91e435daa5f9_5")
public fun <T : Any, K : Any> UiScope.VirtualList(
    items: StateSource<List<T>>,
    keyOf: (T) -> K,
    state: VirtualListState<K>,
    viewportSize: IntSize,
    rowHeight: Int,
    scrollRate: Int = 10,
    canLoadLeading: Boolean = false,
    canLoadTrailing: StateSource<Boolean>,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
    content: UiScope.(T) -> Unit,
) {
    emitObservedComponent(listOf(items, canLoadTrailing), key) { values ->
        VirtualList(
            items = values[0] as List<T>,
            keyOf = keyOf,
            state = state,
            viewportSize = viewportSize,
            rowHeight = rowHeight,
            scrollRate = scrollRate,
            canLoadLeading = canLoadLeading,
            canLoadTrailing = values[1] as Boolean,
            modifier = modifier,
            key = null,
            content = content,
        )
    }
}

/**
 * Source-backed [VirtualList] observing canLoadLeading, canLoadTrailing at the next frame cutoff.
 * Sources remain caller-owned; compatible nodes retain editing, focus, and scrolling state.
 * Literal arguments keep their existing contracts. Equal source values do not re-evaluate this component.
 * The complete modifier chain stays on the actual component; the wrapper delegates parent data and owns the sibling key.
 * Keep sources and dedicated editing states outside observed callbacks. Evaluation and input failures follow ordinary runtime cleanup.
 */
@JvmName("VirtualListState91e435daa5f9_6")
public fun <T : Any, K : Any> UiScope.VirtualList(
    items: List<T>,
    keyOf: (T) -> K,
    state: VirtualListState<K>,
    viewportSize: IntSize,
    rowHeight: Int,
    scrollRate: Int = 10,
    canLoadLeading: StateSource<Boolean>,
    canLoadTrailing: StateSource<Boolean>,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
    content: UiScope.(T) -> Unit,
) {
    emitObservedComponent(listOf(canLoadLeading, canLoadTrailing), key) { values ->
        VirtualList(
            items = items,
            keyOf = keyOf,
            state = state,
            viewportSize = viewportSize,
            rowHeight = rowHeight,
            scrollRate = scrollRate,
            canLoadLeading = values[0] as Boolean,
            canLoadTrailing = values[1] as Boolean,
            modifier = modifier,
            key = null,
            content = content,
        )
    }
}

/**
 * Source-backed [VirtualList] observing items, canLoadLeading, canLoadTrailing at the next frame cutoff.
 * Sources remain caller-owned; compatible nodes retain editing, focus, and scrolling state.
 * Literal arguments keep their existing contracts. Equal source values do not re-evaluate this component.
 * The complete modifier chain stays on the actual component; the wrapper delegates parent data and owns the sibling key.
 * Keep sources and dedicated editing states outside observed callbacks. Evaluation and input failures follow ordinary runtime cleanup.
 */
@JvmName("VirtualListState91e435daa5f9_7")
public fun <T : Any, K : Any> UiScope.VirtualList(
    items: StateSource<List<T>>,
    keyOf: (T) -> K,
    state: VirtualListState<K>,
    viewportSize: IntSize,
    rowHeight: Int,
    scrollRate: Int = 10,
    canLoadLeading: StateSource<Boolean>,
    canLoadTrailing: StateSource<Boolean>,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
    content: UiScope.(T) -> Unit,
) {
    emitObservedComponent(listOf(items, canLoadLeading, canLoadTrailing), key) { values ->
        VirtualList(
            items = values[0] as List<T>,
            keyOf = keyOf,
            state = state,
            viewportSize = viewportSize,
            rowHeight = rowHeight,
            scrollRate = scrollRate,
            canLoadLeading = values[1] as Boolean,
            canLoadTrailing = values[2] as Boolean,
            modifier = modifier,
            key = null,
            content = content,
        )
    }
}

/**
 * Source-backed [SelectionList] observing items at the next frame cutoff.
 * Sources remain caller-owned; compatible nodes retain editing, focus, and scrolling state.
 * Literal arguments keep their existing contracts. Equal source values do not re-evaluate this component.
 * The complete modifier chain stays on the actual component; the wrapper delegates parent data and owns the sibling key.
 * Keep sources and dedicated editing states outside observed callbacks. Evaluation and input failures follow ordinary runtime cleanup.
 */
@JvmName("SelectionListState685be857e721_1")
public fun <T : Any, K : Any> UiScope.SelectionList(
    items: StateSource<List<T>>,
    keyOf: (T) -> K,
    state: SelectionListState<K>,
    viewportSize: IntSize,
    rowHeight: Int,
    canLoadLeading: Boolean = false,
    canLoadTrailing: Boolean = false,
    scrollRate: Int = 10,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
    content: UiScope.(T) -> Unit,
) {
    emitObservedComponent(listOf(items), key) { values ->
        SelectionList(
            items = values[0] as List<T>,
            keyOf = keyOf,
            state = state,
            viewportSize = viewportSize,
            rowHeight = rowHeight,
            canLoadLeading = canLoadLeading,
            canLoadTrailing = canLoadTrailing,
            scrollRate = scrollRate,
            modifier = modifier,
            key = null,
            content = content,
        )
    }
}

/**
 * Source-backed [SelectionList] observing canLoadLeading at the next frame cutoff.
 * Sources remain caller-owned; compatible nodes retain editing, focus, and scrolling state.
 * Literal arguments keep their existing contracts. Equal source values do not re-evaluate this component.
 * The complete modifier chain stays on the actual component; the wrapper delegates parent data and owns the sibling key.
 * Keep sources and dedicated editing states outside observed callbacks. Evaluation and input failures follow ordinary runtime cleanup.
 */
@JvmName("SelectionListState685be857e721_2")
public fun <T : Any, K : Any> UiScope.SelectionList(
    items: List<T>,
    keyOf: (T) -> K,
    state: SelectionListState<K>,
    viewportSize: IntSize,
    rowHeight: Int,
    canLoadLeading: StateSource<Boolean>,
    canLoadTrailing: Boolean = false,
    scrollRate: Int = 10,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
    content: UiScope.(T) -> Unit,
) {
    emitObservedComponent(listOf(canLoadLeading), key) { values ->
        SelectionList(
            items = items,
            keyOf = keyOf,
            state = state,
            viewportSize = viewportSize,
            rowHeight = rowHeight,
            canLoadLeading = values[0] as Boolean,
            canLoadTrailing = canLoadTrailing,
            scrollRate = scrollRate,
            modifier = modifier,
            key = null,
            content = content,
        )
    }
}

/**
 * Source-backed [SelectionList] observing items, canLoadLeading at the next frame cutoff.
 * Sources remain caller-owned; compatible nodes retain editing, focus, and scrolling state.
 * Literal arguments keep their existing contracts. Equal source values do not re-evaluate this component.
 * The complete modifier chain stays on the actual component; the wrapper delegates parent data and owns the sibling key.
 * Keep sources and dedicated editing states outside observed callbacks. Evaluation and input failures follow ordinary runtime cleanup.
 */
@JvmName("SelectionListState685be857e721_3")
public fun <T : Any, K : Any> UiScope.SelectionList(
    items: StateSource<List<T>>,
    keyOf: (T) -> K,
    state: SelectionListState<K>,
    viewportSize: IntSize,
    rowHeight: Int,
    canLoadLeading: StateSource<Boolean>,
    canLoadTrailing: Boolean = false,
    scrollRate: Int = 10,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
    content: UiScope.(T) -> Unit,
) {
    emitObservedComponent(listOf(items, canLoadLeading), key) { values ->
        SelectionList(
            items = values[0] as List<T>,
            keyOf = keyOf,
            state = state,
            viewportSize = viewportSize,
            rowHeight = rowHeight,
            canLoadLeading = values[1] as Boolean,
            canLoadTrailing = canLoadTrailing,
            scrollRate = scrollRate,
            modifier = modifier,
            key = null,
            content = content,
        )
    }
}

/**
 * Source-backed [SelectionList] observing canLoadTrailing at the next frame cutoff.
 * Sources remain caller-owned; compatible nodes retain editing, focus, and scrolling state.
 * Literal arguments keep their existing contracts. Equal source values do not re-evaluate this component.
 * The complete modifier chain stays on the actual component; the wrapper delegates parent data and owns the sibling key.
 * Keep sources and dedicated editing states outside observed callbacks. Evaluation and input failures follow ordinary runtime cleanup.
 */
@JvmName("SelectionListState685be857e721_4")
public fun <T : Any, K : Any> UiScope.SelectionList(
    items: List<T>,
    keyOf: (T) -> K,
    state: SelectionListState<K>,
    viewportSize: IntSize,
    rowHeight: Int,
    canLoadLeading: Boolean = false,
    canLoadTrailing: StateSource<Boolean>,
    scrollRate: Int = 10,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
    content: UiScope.(T) -> Unit,
) {
    emitObservedComponent(listOf(canLoadTrailing), key) { values ->
        SelectionList(
            items = items,
            keyOf = keyOf,
            state = state,
            viewportSize = viewportSize,
            rowHeight = rowHeight,
            canLoadLeading = canLoadLeading,
            canLoadTrailing = values[0] as Boolean,
            scrollRate = scrollRate,
            modifier = modifier,
            key = null,
            content = content,
        )
    }
}

/**
 * Source-backed [SelectionList] observing items, canLoadTrailing at the next frame cutoff.
 * Sources remain caller-owned; compatible nodes retain editing, focus, and scrolling state.
 * Literal arguments keep their existing contracts. Equal source values do not re-evaluate this component.
 * The complete modifier chain stays on the actual component; the wrapper delegates parent data and owns the sibling key.
 * Keep sources and dedicated editing states outside observed callbacks. Evaluation and input failures follow ordinary runtime cleanup.
 */
@JvmName("SelectionListState685be857e721_5")
public fun <T : Any, K : Any> UiScope.SelectionList(
    items: StateSource<List<T>>,
    keyOf: (T) -> K,
    state: SelectionListState<K>,
    viewportSize: IntSize,
    rowHeight: Int,
    canLoadLeading: Boolean = false,
    canLoadTrailing: StateSource<Boolean>,
    scrollRate: Int = 10,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
    content: UiScope.(T) -> Unit,
) {
    emitObservedComponent(listOf(items, canLoadTrailing), key) { values ->
        SelectionList(
            items = values[0] as List<T>,
            keyOf = keyOf,
            state = state,
            viewportSize = viewportSize,
            rowHeight = rowHeight,
            canLoadLeading = canLoadLeading,
            canLoadTrailing = values[1] as Boolean,
            scrollRate = scrollRate,
            modifier = modifier,
            key = null,
            content = content,
        )
    }
}

/**
 * Source-backed [SelectionList] observing canLoadLeading, canLoadTrailing at the next frame cutoff.
 * Sources remain caller-owned; compatible nodes retain editing, focus, and scrolling state.
 * Literal arguments keep their existing contracts. Equal source values do not re-evaluate this component.
 * The complete modifier chain stays on the actual component; the wrapper delegates parent data and owns the sibling key.
 * Keep sources and dedicated editing states outside observed callbacks. Evaluation and input failures follow ordinary runtime cleanup.
 */
@JvmName("SelectionListState685be857e721_6")
public fun <T : Any, K : Any> UiScope.SelectionList(
    items: List<T>,
    keyOf: (T) -> K,
    state: SelectionListState<K>,
    viewportSize: IntSize,
    rowHeight: Int,
    canLoadLeading: StateSource<Boolean>,
    canLoadTrailing: StateSource<Boolean>,
    scrollRate: Int = 10,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
    content: UiScope.(T) -> Unit,
) {
    emitObservedComponent(listOf(canLoadLeading, canLoadTrailing), key) { values ->
        SelectionList(
            items = items,
            keyOf = keyOf,
            state = state,
            viewportSize = viewportSize,
            rowHeight = rowHeight,
            canLoadLeading = values[0] as Boolean,
            canLoadTrailing = values[1] as Boolean,
            scrollRate = scrollRate,
            modifier = modifier,
            key = null,
            content = content,
        )
    }
}

/**
 * Source-backed [SelectionList] observing items, canLoadLeading, canLoadTrailing at the next frame cutoff.
 * Sources remain caller-owned; compatible nodes retain editing, focus, and scrolling state.
 * Literal arguments keep their existing contracts. Equal source values do not re-evaluate this component.
 * The complete modifier chain stays on the actual component; the wrapper delegates parent data and owns the sibling key.
 * Keep sources and dedicated editing states outside observed callbacks. Evaluation and input failures follow ordinary runtime cleanup.
 */
@JvmName("SelectionListState685be857e721_7")
public fun <T : Any, K : Any> UiScope.SelectionList(
    items: StateSource<List<T>>,
    keyOf: (T) -> K,
    state: SelectionListState<K>,
    viewportSize: IntSize,
    rowHeight: Int,
    canLoadLeading: StateSource<Boolean>,
    canLoadTrailing: StateSource<Boolean>,
    scrollRate: Int = 10,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
    content: UiScope.(T) -> Unit,
) {
    emitObservedComponent(listOf(items, canLoadLeading, canLoadTrailing), key) { values ->
        SelectionList(
            items = values[0] as List<T>,
            keyOf = keyOf,
            state = state,
            viewportSize = viewportSize,
            rowHeight = rowHeight,
            canLoadLeading = values[1] as Boolean,
            canLoadTrailing = values[2] as Boolean,
            scrollRate = scrollRate,
            modifier = modifier,
            key = null,
            content = content,
        )
    }
}
