// Generated by :api:generateObserveOverloads. Do not edit by hand.
@file:Suppress("FunctionNaming", "ktlint:standard:function-naming", "LongParameterList", "TooManyFunctions")

package dev.s7a.strata.component

import dev.s7a.strata.element.ElementKey
import dev.s7a.strata.modifier.Modifier
import dev.s7a.strata.state.StateSource

/**
 * Emits one retained region observing 1 source without evaluating content immediately.
 *
 * The owner-thread callback emits zero or one root; use Row or Column for multiple children.
 * The region is one layout child: apply parent data to its modifier. Empty content has zero natural size.
 * Source identities share subscriptions and frame snapshots; updates coalesce before parent-first evaluation.
 * Equal values skip source-driven evaluation; changed parent callbacks still refresh captures.
 * Keep editable state outside content. Do not mutate sources or retain the callback scope.
 * Removal, failure, and close release subscriptions and captured content without closing caller-owned sources.
 * @param state1 caller-owned source whose committed value is passed to content.
 * @param modifier active behavior and parent data for the region.
 * @param key optional stable sibling identity.
 * @param content deferred owner-thread callback.
 */
public fun <V1> UiScope.Observe(
    state1: StateSource<V1>,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
    content: UiScope.(V1) -> Unit,
) {
    emitObserve(listOf(state1), modifier, key) { values ->
        @Suppress("UNCHECKED_CAST")
        content(values[0] as V1)
    }
}

/**
 * Emits one retained region observing 2 sources without evaluating content immediately.
 *
 * Uses the single-source [Observe] contract; caller-owned source values are passed in declaration order.
 * Independent sources are not atomic together; publish one model when fields must change as a unit.
 */
public fun <V1, V2> UiScope.Observe(
    state1: StateSource<V1>,
    state2: StateSource<V2>,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
    content: UiScope.(V1, V2) -> Unit,
) {
    emitObserve(listOf(state1, state2), modifier, key) { values ->
        @Suppress("UNCHECKED_CAST")
        content(values[0] as V1, values[1] as V2)
    }
}

/**
 * Emits one retained region observing 3 sources without evaluating content immediately.
 *
 * Uses the single-source [Observe] contract; caller-owned source values are passed in declaration order.
 * Independent sources are not atomic together; publish one model when fields must change as a unit.
 */
public fun <V1, V2, V3> UiScope.Observe(
    state1: StateSource<V1>,
    state2: StateSource<V2>,
    state3: StateSource<V3>,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
    content: UiScope.(V1, V2, V3) -> Unit,
) {
    emitObserve(listOf(state1, state2, state3), modifier, key) { values ->
        @Suppress("UNCHECKED_CAST")
        content(values[0] as V1, values[1] as V2, values[2] as V3)
    }
}

/**
 * Emits one retained region observing 4 sources without evaluating content immediately.
 *
 * Uses the single-source [Observe] contract; caller-owned source values are passed in declaration order.
 * Independent sources are not atomic together; publish one model when fields must change as a unit.
 */
public fun <V1, V2, V3, V4> UiScope.Observe(
    state1: StateSource<V1>,
    state2: StateSource<V2>,
    state3: StateSource<V3>,
    state4: StateSource<V4>,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
    content: UiScope.(V1, V2, V3, V4) -> Unit,
) {
    emitObserve(listOf(state1, state2, state3, state4), modifier, key) { values ->
        @Suppress("UNCHECKED_CAST")
        content(values[0] as V1, values[1] as V2, values[2] as V3, values[3] as V4)
    }
}

/**
 * Emits one retained region observing 5 sources without evaluating content immediately.
 *
 * Uses the single-source [Observe] contract; caller-owned source values are passed in declaration order.
 * Independent sources are not atomic together; publish one model when fields must change as a unit.
 */
public fun <V1, V2, V3, V4, V5> UiScope.Observe(
    state1: StateSource<V1>,
    state2: StateSource<V2>,
    state3: StateSource<V3>,
    state4: StateSource<V4>,
    state5: StateSource<V5>,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
    content: UiScope.(V1, V2, V3, V4, V5) -> Unit,
) {
    emitObserve(listOf(state1, state2, state3, state4, state5), modifier, key) { values ->
        @Suppress("UNCHECKED_CAST")
        content(values[0] as V1, values[1] as V2, values[2] as V3, values[3] as V4, values[4] as V5)
    }
}

/**
 * Emits one retained region observing 6 sources without evaluating content immediately.
 *
 * Uses the single-source [Observe] contract; caller-owned source values are passed in declaration order.
 * Independent sources are not atomic together; publish one model when fields must change as a unit.
 */
public fun <V1, V2, V3, V4, V5, V6> UiScope.Observe(
    state1: StateSource<V1>,
    state2: StateSource<V2>,
    state3: StateSource<V3>,
    state4: StateSource<V4>,
    state5: StateSource<V5>,
    state6: StateSource<V6>,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
    content: UiScope.(V1, V2, V3, V4, V5, V6) -> Unit,
) {
    emitObserve(listOf(state1, state2, state3, state4, state5, state6), modifier, key) { values ->
        @Suppress("UNCHECKED_CAST")
        content(values[0] as V1, values[1] as V2, values[2] as V3, values[3] as V4, values[4] as V5, values[5] as V6)
    }
}

/**
 * Emits one retained region observing 7 sources without evaluating content immediately.
 *
 * Uses the single-source [Observe] contract; caller-owned source values are passed in declaration order.
 * Independent sources are not atomic together; publish one model when fields must change as a unit.
 */
public fun <V1, V2, V3, V4, V5, V6, V7> UiScope.Observe(
    state1: StateSource<V1>,
    state2: StateSource<V2>,
    state3: StateSource<V3>,
    state4: StateSource<V4>,
    state5: StateSource<V5>,
    state6: StateSource<V6>,
    state7: StateSource<V7>,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
    content: UiScope.(V1, V2, V3, V4, V5, V6, V7) -> Unit,
) {
    emitObserve(listOf(state1, state2, state3, state4, state5, state6, state7), modifier, key) { values ->
        @Suppress("UNCHECKED_CAST")
        content(values[0] as V1, values[1] as V2, values[2] as V3, values[3] as V4, values[4] as V5, values[5] as V6, values[6] as V7)
    }
}

/**
 * Emits one retained region observing 8 sources without evaluating content immediately.
 *
 * Uses the single-source [Observe] contract; caller-owned source values are passed in declaration order.
 * Independent sources are not atomic together; publish one model when fields must change as a unit.
 */
public fun <V1, V2, V3, V4, V5, V6, V7, V8> UiScope.Observe(
    state1: StateSource<V1>,
    state2: StateSource<V2>,
    state3: StateSource<V3>,
    state4: StateSource<V4>,
    state5: StateSource<V5>,
    state6: StateSource<V6>,
    state7: StateSource<V7>,
    state8: StateSource<V8>,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
    content: UiScope.(V1, V2, V3, V4, V5, V6, V7, V8) -> Unit,
) {
    emitObserve(listOf(state1, state2, state3, state4, state5, state6, state7, state8), modifier, key) { values ->
        @Suppress("UNCHECKED_CAST")
        content(values[0] as V1, values[1] as V2, values[2] as V3, values[3] as V4, values[4] as V5, values[5] as V6, values[6] as V7, values[7] as V8)
    }
}

/**
 * Emits one retained region observing 9 sources without evaluating content immediately.
 *
 * Uses the single-source [Observe] contract; caller-owned source values are passed in declaration order.
 * Independent sources are not atomic together; publish one model when fields must change as a unit.
 */
public fun <V1, V2, V3, V4, V5, V6, V7, V8, V9> UiScope.Observe(
    state1: StateSource<V1>,
    state2: StateSource<V2>,
    state3: StateSource<V3>,
    state4: StateSource<V4>,
    state5: StateSource<V5>,
    state6: StateSource<V6>,
    state7: StateSource<V7>,
    state8: StateSource<V8>,
    state9: StateSource<V9>,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
    content: UiScope.(V1, V2, V3, V4, V5, V6, V7, V8, V9) -> Unit,
) {
    emitObserve(listOf(state1, state2, state3, state4, state5, state6, state7, state8, state9), modifier, key) { values ->
        @Suppress("UNCHECKED_CAST")
        content(values[0] as V1, values[1] as V2, values[2] as V3, values[3] as V4, values[4] as V5, values[5] as V6, values[6] as V7, values[7] as V8, values[8] as V9)
    }
}

/**
 * Emits one retained region observing 10 sources without evaluating content immediately.
 *
 * Uses the single-source [Observe] contract; caller-owned source values are passed in declaration order.
 * Independent sources are not atomic together; publish one model when fields must change as a unit.
 */
public fun <V1, V2, V3, V4, V5, V6, V7, V8, V9, V10> UiScope.Observe(
    state1: StateSource<V1>,
    state2: StateSource<V2>,
    state3: StateSource<V3>,
    state4: StateSource<V4>,
    state5: StateSource<V5>,
    state6: StateSource<V6>,
    state7: StateSource<V7>,
    state8: StateSource<V8>,
    state9: StateSource<V9>,
    state10: StateSource<V10>,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
    content: UiScope.(V1, V2, V3, V4, V5, V6, V7, V8, V9, V10) -> Unit,
) {
    emitObserve(listOf(state1, state2, state3, state4, state5, state6, state7, state8, state9, state10), modifier, key) { values ->
        @Suppress("UNCHECKED_CAST")
        content(values[0] as V1, values[1] as V2, values[2] as V3, values[3] as V4, values[4] as V5, values[5] as V6, values[6] as V7, values[7] as V8, values[8] as V9, values[9] as V10)
    }
}

/**
 * Emits one retained region observing 11 sources without evaluating content immediately.
 *
 * Uses the single-source [Observe] contract; caller-owned source values are passed in declaration order.
 * Independent sources are not atomic together; publish one model when fields must change as a unit.
 */
public fun <V1, V2, V3, V4, V5, V6, V7, V8, V9, V10, V11> UiScope.Observe(
    state1: StateSource<V1>,
    state2: StateSource<V2>,
    state3: StateSource<V3>,
    state4: StateSource<V4>,
    state5: StateSource<V5>,
    state6: StateSource<V6>,
    state7: StateSource<V7>,
    state8: StateSource<V8>,
    state9: StateSource<V9>,
    state10: StateSource<V10>,
    state11: StateSource<V11>,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
    content: UiScope.(V1, V2, V3, V4, V5, V6, V7, V8, V9, V10, V11) -> Unit,
) {
    emitObserve(listOf(state1, state2, state3, state4, state5, state6, state7, state8, state9, state10, state11), modifier, key) { values ->
        @Suppress("UNCHECKED_CAST")
        content(values[0] as V1, values[1] as V2, values[2] as V3, values[3] as V4, values[4] as V5, values[5] as V6, values[6] as V7, values[7] as V8, values[8] as V9, values[9] as V10, values[10] as V11)
    }
}

/**
 * Emits one retained region observing 12 sources without evaluating content immediately.
 *
 * Uses the single-source [Observe] contract; caller-owned source values are passed in declaration order.
 * Independent sources are not atomic together; publish one model when fields must change as a unit.
 */
public fun <V1, V2, V3, V4, V5, V6, V7, V8, V9, V10, V11, V12> UiScope.Observe(
    state1: StateSource<V1>,
    state2: StateSource<V2>,
    state3: StateSource<V3>,
    state4: StateSource<V4>,
    state5: StateSource<V5>,
    state6: StateSource<V6>,
    state7: StateSource<V7>,
    state8: StateSource<V8>,
    state9: StateSource<V9>,
    state10: StateSource<V10>,
    state11: StateSource<V11>,
    state12: StateSource<V12>,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
    content: UiScope.(V1, V2, V3, V4, V5, V6, V7, V8, V9, V10, V11, V12) -> Unit,
) {
    emitObserve(listOf(state1, state2, state3, state4, state5, state6, state7, state8, state9, state10, state11, state12), modifier, key) { values ->
        @Suppress("UNCHECKED_CAST")
        content(values[0] as V1, values[1] as V2, values[2] as V3, values[3] as V4, values[4] as V5, values[5] as V6, values[6] as V7, values[7] as V8, values[8] as V9, values[9] as V10, values[10] as V11, values[11] as V12)
    }
}

/**
 * Emits one retained region observing 13 sources without evaluating content immediately.
 *
 * Uses the single-source [Observe] contract; caller-owned source values are passed in declaration order.
 * Independent sources are not atomic together; publish one model when fields must change as a unit.
 */
public fun <V1, V2, V3, V4, V5, V6, V7, V8, V9, V10, V11, V12, V13> UiScope.Observe(
    state1: StateSource<V1>,
    state2: StateSource<V2>,
    state3: StateSource<V3>,
    state4: StateSource<V4>,
    state5: StateSource<V5>,
    state6: StateSource<V6>,
    state7: StateSource<V7>,
    state8: StateSource<V8>,
    state9: StateSource<V9>,
    state10: StateSource<V10>,
    state11: StateSource<V11>,
    state12: StateSource<V12>,
    state13: StateSource<V13>,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
    content: UiScope.(V1, V2, V3, V4, V5, V6, V7, V8, V9, V10, V11, V12, V13) -> Unit,
) {
    emitObserve(listOf(state1, state2, state3, state4, state5, state6, state7, state8, state9, state10, state11, state12, state13), modifier, key) { values ->
        @Suppress("UNCHECKED_CAST")
        content(values[0] as V1, values[1] as V2, values[2] as V3, values[3] as V4, values[4] as V5, values[5] as V6, values[6] as V7, values[7] as V8, values[8] as V9, values[9] as V10, values[10] as V11, values[11] as V12, values[12] as V13)
    }
}

/**
 * Emits one retained region observing 14 sources without evaluating content immediately.
 *
 * Uses the single-source [Observe] contract; caller-owned source values are passed in declaration order.
 * Independent sources are not atomic together; publish one model when fields must change as a unit.
 */
public fun <V1, V2, V3, V4, V5, V6, V7, V8, V9, V10, V11, V12, V13, V14> UiScope.Observe(
    state1: StateSource<V1>,
    state2: StateSource<V2>,
    state3: StateSource<V3>,
    state4: StateSource<V4>,
    state5: StateSource<V5>,
    state6: StateSource<V6>,
    state7: StateSource<V7>,
    state8: StateSource<V8>,
    state9: StateSource<V9>,
    state10: StateSource<V10>,
    state11: StateSource<V11>,
    state12: StateSource<V12>,
    state13: StateSource<V13>,
    state14: StateSource<V14>,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
    content: UiScope.(V1, V2, V3, V4, V5, V6, V7, V8, V9, V10, V11, V12, V13, V14) -> Unit,
) {
    emitObserve(listOf(state1, state2, state3, state4, state5, state6, state7, state8, state9, state10, state11, state12, state13, state14), modifier, key) { values ->
        @Suppress("UNCHECKED_CAST")
        content(values[0] as V1, values[1] as V2, values[2] as V3, values[3] as V4, values[4] as V5, values[5] as V6, values[6] as V7, values[7] as V8, values[8] as V9, values[9] as V10, values[10] as V11, values[11] as V12, values[12] as V13, values[13] as V14)
    }
}

/**
 * Emits one retained region observing 15 sources without evaluating content immediately.
 *
 * Uses the single-source [Observe] contract; caller-owned source values are passed in declaration order.
 * Independent sources are not atomic together; publish one model when fields must change as a unit.
 */
public fun <V1, V2, V3, V4, V5, V6, V7, V8, V9, V10, V11, V12, V13, V14, V15> UiScope.Observe(
    state1: StateSource<V1>,
    state2: StateSource<V2>,
    state3: StateSource<V3>,
    state4: StateSource<V4>,
    state5: StateSource<V5>,
    state6: StateSource<V6>,
    state7: StateSource<V7>,
    state8: StateSource<V8>,
    state9: StateSource<V9>,
    state10: StateSource<V10>,
    state11: StateSource<V11>,
    state12: StateSource<V12>,
    state13: StateSource<V13>,
    state14: StateSource<V14>,
    state15: StateSource<V15>,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
    content: UiScope.(V1, V2, V3, V4, V5, V6, V7, V8, V9, V10, V11, V12, V13, V14, V15) -> Unit,
) {
    emitObserve(listOf(state1, state2, state3, state4, state5, state6, state7, state8, state9, state10, state11, state12, state13, state14, state15), modifier, key) { values ->
        @Suppress("UNCHECKED_CAST")
        content(values[0] as V1, values[1] as V2, values[2] as V3, values[3] as V4, values[4] as V5, values[5] as V6, values[6] as V7, values[7] as V8, values[8] as V9, values[9] as V10, values[10] as V11, values[11] as V12, values[12] as V13, values[13] as V14, values[14] as V15)
    }
}

/**
 * Emits one retained region observing 16 sources without evaluating content immediately.
 *
 * Uses the single-source [Observe] contract; caller-owned source values are passed in declaration order.
 * Independent sources are not atomic together; publish one model when fields must change as a unit.
 */
public fun <V1, V2, V3, V4, V5, V6, V7, V8, V9, V10, V11, V12, V13, V14, V15, V16> UiScope.Observe(
    state1: StateSource<V1>,
    state2: StateSource<V2>,
    state3: StateSource<V3>,
    state4: StateSource<V4>,
    state5: StateSource<V5>,
    state6: StateSource<V6>,
    state7: StateSource<V7>,
    state8: StateSource<V8>,
    state9: StateSource<V9>,
    state10: StateSource<V10>,
    state11: StateSource<V11>,
    state12: StateSource<V12>,
    state13: StateSource<V13>,
    state14: StateSource<V14>,
    state15: StateSource<V15>,
    state16: StateSource<V16>,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
    content: UiScope.(V1, V2, V3, V4, V5, V6, V7, V8, V9, V10, V11, V12, V13, V14, V15, V16) -> Unit,
) {
    emitObserve(listOf(state1, state2, state3, state4, state5, state6, state7, state8, state9, state10, state11, state12, state13, state14, state15, state16), modifier, key) { values ->
        @Suppress("UNCHECKED_CAST")
        content(values[0] as V1, values[1] as V2, values[2] as V3, values[3] as V4, values[4] as V5, values[5] as V6, values[6] as V7, values[7] as V8, values[8] as V9, values[9] as V10, values[10] as V11, values[11] as V12, values[12] as V13, values[13] as V14, values[14] as V15, values[15] as V16)
    }
}

/**
 * Emits one retained region observing 17 sources without evaluating content immediately.
 *
 * Uses the single-source [Observe] contract; caller-owned source values are passed in declaration order.
 * Independent sources are not atomic together; publish one model when fields must change as a unit.
 */
public fun <V1, V2, V3, V4, V5, V6, V7, V8, V9, V10, V11, V12, V13, V14, V15, V16, V17> UiScope.Observe(
    state1: StateSource<V1>,
    state2: StateSource<V2>,
    state3: StateSource<V3>,
    state4: StateSource<V4>,
    state5: StateSource<V5>,
    state6: StateSource<V6>,
    state7: StateSource<V7>,
    state8: StateSource<V8>,
    state9: StateSource<V9>,
    state10: StateSource<V10>,
    state11: StateSource<V11>,
    state12: StateSource<V12>,
    state13: StateSource<V13>,
    state14: StateSource<V14>,
    state15: StateSource<V15>,
    state16: StateSource<V16>,
    state17: StateSource<V17>,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
    content: UiScope.(V1, V2, V3, V4, V5, V6, V7, V8, V9, V10, V11, V12, V13, V14, V15, V16, V17) -> Unit,
) {
    emitObserve(listOf(state1, state2, state3, state4, state5, state6, state7, state8, state9, state10, state11, state12, state13, state14, state15, state16, state17), modifier, key) { values ->
        @Suppress("UNCHECKED_CAST")
        content(values[0] as V1, values[1] as V2, values[2] as V3, values[3] as V4, values[4] as V5, values[5] as V6, values[6] as V7, values[7] as V8, values[8] as V9, values[9] as V10, values[10] as V11, values[11] as V12, values[12] as V13, values[13] as V14, values[14] as V15, values[15] as V16, values[16] as V17)
    }
}

/**
 * Emits one retained region observing 18 sources without evaluating content immediately.
 *
 * Uses the single-source [Observe] contract; caller-owned source values are passed in declaration order.
 * Independent sources are not atomic together; publish one model when fields must change as a unit.
 */
public fun <V1, V2, V3, V4, V5, V6, V7, V8, V9, V10, V11, V12, V13, V14, V15, V16, V17, V18> UiScope.Observe(
    state1: StateSource<V1>,
    state2: StateSource<V2>,
    state3: StateSource<V3>,
    state4: StateSource<V4>,
    state5: StateSource<V5>,
    state6: StateSource<V6>,
    state7: StateSource<V7>,
    state8: StateSource<V8>,
    state9: StateSource<V9>,
    state10: StateSource<V10>,
    state11: StateSource<V11>,
    state12: StateSource<V12>,
    state13: StateSource<V13>,
    state14: StateSource<V14>,
    state15: StateSource<V15>,
    state16: StateSource<V16>,
    state17: StateSource<V17>,
    state18: StateSource<V18>,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
    content: UiScope.(V1, V2, V3, V4, V5, V6, V7, V8, V9, V10, V11, V12, V13, V14, V15, V16, V17, V18) -> Unit,
) {
    emitObserve(listOf(state1, state2, state3, state4, state5, state6, state7, state8, state9, state10, state11, state12, state13, state14, state15, state16, state17, state18), modifier, key) { values ->
        @Suppress("UNCHECKED_CAST")
        content(values[0] as V1, values[1] as V2, values[2] as V3, values[3] as V4, values[4] as V5, values[5] as V6, values[6] as V7, values[7] as V8, values[8] as V9, values[9] as V10, values[10] as V11, values[11] as V12, values[12] as V13, values[13] as V14, values[14] as V15, values[15] as V16, values[16] as V17, values[17] as V18)
    }
}

/**
 * Emits one retained region observing 19 sources without evaluating content immediately.
 *
 * Uses the single-source [Observe] contract; caller-owned source values are passed in declaration order.
 * Independent sources are not atomic together; publish one model when fields must change as a unit.
 */
public fun <V1, V2, V3, V4, V5, V6, V7, V8, V9, V10, V11, V12, V13, V14, V15, V16, V17, V18, V19> UiScope.Observe(
    state1: StateSource<V1>,
    state2: StateSource<V2>,
    state3: StateSource<V3>,
    state4: StateSource<V4>,
    state5: StateSource<V5>,
    state6: StateSource<V6>,
    state7: StateSource<V7>,
    state8: StateSource<V8>,
    state9: StateSource<V9>,
    state10: StateSource<V10>,
    state11: StateSource<V11>,
    state12: StateSource<V12>,
    state13: StateSource<V13>,
    state14: StateSource<V14>,
    state15: StateSource<V15>,
    state16: StateSource<V16>,
    state17: StateSource<V17>,
    state18: StateSource<V18>,
    state19: StateSource<V19>,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
    content: UiScope.(V1, V2, V3, V4, V5, V6, V7, V8, V9, V10, V11, V12, V13, V14, V15, V16, V17, V18, V19) -> Unit,
) {
    emitObserve(listOf(state1, state2, state3, state4, state5, state6, state7, state8, state9, state10, state11, state12, state13, state14, state15, state16, state17, state18, state19), modifier, key) { values ->
        @Suppress("UNCHECKED_CAST")
        content(values[0] as V1, values[1] as V2, values[2] as V3, values[3] as V4, values[4] as V5, values[5] as V6, values[6] as V7, values[7] as V8, values[8] as V9, values[9] as V10, values[10] as V11, values[11] as V12, values[12] as V13, values[13] as V14, values[14] as V15, values[15] as V16, values[16] as V17, values[17] as V18, values[18] as V19)
    }
}

/**
 * Emits one retained region observing 20 sources without evaluating content immediately.
 *
 * Uses the single-source [Observe] contract; caller-owned source values are passed in declaration order.
 * Independent sources are not atomic together; publish one model when fields must change as a unit.
 */
public fun <V1, V2, V3, V4, V5, V6, V7, V8, V9, V10, V11, V12, V13, V14, V15, V16, V17, V18, V19, V20> UiScope.Observe(
    state1: StateSource<V1>,
    state2: StateSource<V2>,
    state3: StateSource<V3>,
    state4: StateSource<V4>,
    state5: StateSource<V5>,
    state6: StateSource<V6>,
    state7: StateSource<V7>,
    state8: StateSource<V8>,
    state9: StateSource<V9>,
    state10: StateSource<V10>,
    state11: StateSource<V11>,
    state12: StateSource<V12>,
    state13: StateSource<V13>,
    state14: StateSource<V14>,
    state15: StateSource<V15>,
    state16: StateSource<V16>,
    state17: StateSource<V17>,
    state18: StateSource<V18>,
    state19: StateSource<V19>,
    state20: StateSource<V20>,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
    content: UiScope.(V1, V2, V3, V4, V5, V6, V7, V8, V9, V10, V11, V12, V13, V14, V15, V16, V17, V18, V19, V20) -> Unit,
) {
    emitObserve(listOf(state1, state2, state3, state4, state5, state6, state7, state8, state9, state10, state11, state12, state13, state14, state15, state16, state17, state18, state19, state20), modifier, key) { values ->
        @Suppress("UNCHECKED_CAST")
        content(values[0] as V1, values[1] as V2, values[2] as V3, values[3] as V4, values[4] as V5, values[5] as V6, values[6] as V7, values[7] as V8, values[8] as V9, values[9] as V10, values[10] as V11, values[11] as V12, values[12] as V13, values[13] as V14, values[14] as V15, values[15] as V16, values[16] as V17, values[17] as V18, values[18] as V19, values[19] as V20)
    }
}

/**
 * Emits one retained region observing 21 sources without evaluating content immediately.
 *
 * Uses the single-source [Observe] contract; caller-owned source values are passed in declaration order.
 * Independent sources are not atomic together; publish one model when fields must change as a unit.
 */
public fun <V1, V2, V3, V4, V5, V6, V7, V8, V9, V10, V11, V12, V13, V14, V15, V16, V17, V18, V19, V20, V21> UiScope.Observe(
    state1: StateSource<V1>,
    state2: StateSource<V2>,
    state3: StateSource<V3>,
    state4: StateSource<V4>,
    state5: StateSource<V5>,
    state6: StateSource<V6>,
    state7: StateSource<V7>,
    state8: StateSource<V8>,
    state9: StateSource<V9>,
    state10: StateSource<V10>,
    state11: StateSource<V11>,
    state12: StateSource<V12>,
    state13: StateSource<V13>,
    state14: StateSource<V14>,
    state15: StateSource<V15>,
    state16: StateSource<V16>,
    state17: StateSource<V17>,
    state18: StateSource<V18>,
    state19: StateSource<V19>,
    state20: StateSource<V20>,
    state21: StateSource<V21>,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
    content: UiScope.(V1, V2, V3, V4, V5, V6, V7, V8, V9, V10, V11, V12, V13, V14, V15, V16, V17, V18, V19, V20, V21) -> Unit,
) {
    emitObserve(listOf(state1, state2, state3, state4, state5, state6, state7, state8, state9, state10, state11, state12, state13, state14, state15, state16, state17, state18, state19, state20, state21), modifier, key) { values ->
        @Suppress("UNCHECKED_CAST")
        content(values[0] as V1, values[1] as V2, values[2] as V3, values[3] as V4, values[4] as V5, values[5] as V6, values[6] as V7, values[7] as V8, values[8] as V9, values[9] as V10, values[10] as V11, values[11] as V12, values[12] as V13, values[13] as V14, values[14] as V15, values[15] as V16, values[16] as V17, values[17] as V18, values[18] as V19, values[19] as V20, values[20] as V21)
    }
}

/**
 * Emits one retained region observing 22 sources without evaluating content immediately.
 *
 * Uses the single-source [Observe] contract; caller-owned source values are passed in declaration order.
 * Independent sources are not atomic together; publish one model when fields must change as a unit.
 */
public fun <V1, V2, V3, V4, V5, V6, V7, V8, V9, V10, V11, V12, V13, V14, V15, V16, V17, V18, V19, V20, V21, V22> UiScope.Observe(
    state1: StateSource<V1>,
    state2: StateSource<V2>,
    state3: StateSource<V3>,
    state4: StateSource<V4>,
    state5: StateSource<V5>,
    state6: StateSource<V6>,
    state7: StateSource<V7>,
    state8: StateSource<V8>,
    state9: StateSource<V9>,
    state10: StateSource<V10>,
    state11: StateSource<V11>,
    state12: StateSource<V12>,
    state13: StateSource<V13>,
    state14: StateSource<V14>,
    state15: StateSource<V15>,
    state16: StateSource<V16>,
    state17: StateSource<V17>,
    state18: StateSource<V18>,
    state19: StateSource<V19>,
    state20: StateSource<V20>,
    state21: StateSource<V21>,
    state22: StateSource<V22>,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
    content: UiScope.(V1, V2, V3, V4, V5, V6, V7, V8, V9, V10, V11, V12, V13, V14, V15, V16, V17, V18, V19, V20, V21, V22) -> Unit,
) {
    emitObserve(listOf(state1, state2, state3, state4, state5, state6, state7, state8, state9, state10, state11, state12, state13, state14, state15, state16, state17, state18, state19, state20, state21, state22), modifier, key) { values ->
        @Suppress("UNCHECKED_CAST")
        content(values[0] as V1, values[1] as V2, values[2] as V3, values[3] as V4, values[4] as V5, values[5] as V6, values[6] as V7, values[7] as V8, values[8] as V9, values[9] as V10, values[10] as V11, values[11] as V12, values[12] as V13, values[13] as V14, values[14] as V15, values[15] as V16, values[16] as V17, values[17] as V18, values[18] as V19, values[19] as V20, values[20] as V21, values[21] as V22)
    }
}
