[versions]
kotlin = "2.4.10"
java-baseline = "17"
java-minecraft = "25"
java-minecraft121 = "21"
detekt = "2.0.0-alpha.6"
junit = "6.1.3"
kotlinter = "5.7.0"
kover = "0.9.9"
jmh-gradle = "0.7.3"
benchmark-harness = "1.37"
vanniktech-maven-publish = "0.37.0"
dokka = "2.2.0"
kotlinx-coroutines = "1.11.0"
minecraft262 = "26.2"
minecraft261 = "26.1"
minecraft121 = "1.21"
minecraft1211 = "1.21.1"
minecraft1212 = "1.21.2"
minecraft1213 = "1.21.3"
minecraft1214 = "1.21.4"
minecraft1215 = "1.21.5"
minecraft1216 = "1.21.6"
minecraft1217 = "1.21.7"
minecraft1218 = "1.21.8"
minecraft12111 = "1.21.11"
minecraft12110 = "1.21.10"
minecraft1219 = "1.21.9"
minecraft120 = "1.20"
minecraft1201 = "1.20.1"
minecraft1202 = "1.20.2"
minecraft1203 = "1.20.3"
minecraft1204 = "1.20.4"
minecraft1205 = "1.20.5"
minecraft1206 = "1.20.6"
fabric-loader = "0.19.3"
fabric-language-kotlin = "1.13.13+kotlin.2.4.10"
fabric-loom = "1.17.19"
fabric-api262 = "0.158.0+26.2"
fabric-api261 = "0.145.1+26.1"
fabric-api121 = "0.102.0+1.21"
fabric-api1211 = "0.116.15+1.21.1"
fabric-api1212 = "0.106.1+1.21.2"
fabric-api1213 = "0.114.1+1.21.3"
fabric-api1214 = "0.119.4+1.21.4"
fabric-api1215 = "0.128.2+1.21.5"
fabric-api1216 = "0.128.2+1.21.6"
fabric-api1217 = "0.129.0+1.21.7"
fabric-api1218 = "0.136.1+1.21.8"
fabric-api12111 = "0.141.6+1.21.11"
fabric-api12110 = "0.138.4+1.21.10"
fabric-api1219 = "0.134.1+1.21.9"
fabric-api120 = "0.83.0+1.20"
fabric-api1201 = "0.92.11+1.20.1"
fabric-api1202 = "0.91.6+1.20.2"
fabric-api1203 = "0.91.1+1.20.3"
fabric-api1204 = "0.97.3+1.20.4"
fabric-api1205 = "0.97.8+1.20.5"
fabric-api1206 = "0.100.8+1.20.6"

[libraries]
detekt-api = { module = "dev.detekt:detekt-api", version.ref = "detekt" }
detekt-test = { module = "dev.detekt:detekt-test", version.ref = "detekt" }
detekt-test-utils = { module = "dev.detekt:detekt-test-utils", version.ref = "detekt" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
minecraft262 = { module = "com.mojang:minecraft", version.ref = "minecraft262" }
minecraft261 = { module = "com.mojang:minecraft", version.ref = "minecraft261" }
minecraft121 = { module = "com.mojang:minecraft", version.ref = "minecraft121" }
minecraft1211 = { module = "com.mojang:minecraft", version.ref = "minecraft1211" }
minecraft1212 = { module = "com.mojang:minecraft", version.ref = "minecraft1212" }
minecraft1213 = { module = "com.mojang:minecraft", version.ref = "minecraft1213" }
minecraft1214 = { module = "com.mojang:minecraft", version.ref = "minecraft1214" }
minecraft1215 = { module = "com.mojang:minecraft", version.ref = "minecraft1215" }
minecraft1216 = { module = "com.mojang:minecraft", version.ref = "minecraft1216" }
minecraft1217 = { module = "com.mojang:minecraft", version.ref = "minecraft1217" }
minecraft1218 = { module = "com.mojang:minecraft", version.ref = "minecraft1218" }
minecraft12111 = { module = "com.mojang:minecraft", version.ref = "minecraft12111" }
minecraft12110 = { module = "com.mojang:minecraft", version.ref = "minecraft12110" }
minecraft1219 = { module = "com.mojang:minecraft", version.ref = "minecraft1219" }
minecraft120 = { module = "com.mojang:minecraft", version.ref = "minecraft120" }
minecraft1201 = { module = "com.mojang:minecraft", version.ref = "minecraft1201" }
minecraft1202 = { module = "com.mojang:minecraft", version.ref = "minecraft1202" }
minecraft1203 = { module = "com.mojang:minecraft", version.ref = "minecraft1203" }
minecraft1204 = { module = "com.mojang:minecraft", version.ref = "minecraft1204" }
minecraft1205 = { module = "com.mojang:minecraft", version.ref = "minecraft1205" }
minecraft1206 = { module = "com.mojang:minecraft", version.ref = "minecraft1206" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-language-kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabric-language-kotlin" }
fabric-api262 = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api262" }
fabric-api261 = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api261" }
fabric-api121 = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api121" }
fabric-api1211 = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api1211" }
fabric-api1212 = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api1212" }
fabric-api1213 = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api1213" }
fabric-api1214 = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api1214" }
fabric-api1215 = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api1215" }
fabric-api1216 = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api1216" }
fabric-api1217 = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api1217" }
fabric-api1218 = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api1218" }
fabric-api12111 = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api12111" }
fabric-api12110 = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api12110" }
fabric-api1219 = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api1219" }
fabric-api120 = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api120" }
fabric-api1201 = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api1201" }
fabric-api1202 = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api1202" }
fabric-api1203 = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api1203" }
fabric-api1204 = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api1204" }
fabric-api1205 = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api1205" }
fabric-api1206 = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api1206" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
jmh = { id = "me.champeau.jmh", version.ref = "jmh-gradle" }
detekt = { id = "dev.detekt", version.ref = "detekt" }
kotlinter = { id = "org.jmailen.kotlinter", version.ref = "kotlinter" }
vanniktechMavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "vanniktech-maven-publish" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
dokkaJavadocPlugin = { id = "org.jetbrains.dokka-javadoc", version.ref = "dokka" }
fabricLoom = { id = "net.fabricmc.fabric-loom", version.ref = "fabric-loom" }
fabricLoomRemap = { id = "net.fabricmc.fabric-loom-remap", version.ref = "fabric-loom" }
