// Generated by :api:generateStateComponentOverloads. Do not edit by hand.
@file:Suppress("FunctionNaming", "ktlint:standard:function-naming", "LongParameterList", "TooManyFunctions", "UNCHECKED_CAST", "unused")

package dev.s7a.strata.component

import dev.s7a.strata.element.ElementKey
import dev.s7a.strata.geometry.IntRect
import dev.s7a.strata.geometry.IntSize
import dev.s7a.strata.modifier.Modifier
import dev.s7a.strata.resource.ResourceId
import dev.s7a.strata.state.StateSource
import dev.s7a.strata.text.TextWrap
import dev.s7a.strata.text.UiText

private fun UiScope.compileProgressBar4c303dc4114b_1(
    progress: StateSource<Double>,
    size: IntSize = IntSize(100, 12),
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    ProgressBar(
        progress = progress,
        size = size,
        modifier = modifier,
        key = key,
    )
}

private fun UiScope.compileCheckbox3bddea62a5dc_1(
    label: StateSource<UiText>,
    state: CheckboxState,
    width: Int = 150,
    enabled: Boolean = true,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    Checkbox(
        label = label,
        state = state,
        width = width,
        enabled = enabled,
        modifier = modifier,
        key = key,
    )
}

private fun UiScope.compileCheckbox3bddea62a5dc_2(
    label: UiText,
    state: CheckboxState,
    width: Int = 150,
    enabled: StateSource<Boolean>,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    Checkbox(
        label = label,
        state = state,
        width = width,
        enabled = enabled,
        modifier = modifier,
        key = key,
    )
}

private fun UiScope.compileCheckbox3bddea62a5dc_3(
    label: StateSource<UiText>,
    state: CheckboxState,
    width: Int = 150,
    enabled: StateSource<Boolean>,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    Checkbox(
        label = label,
        state = state,
        width = width,
        enabled = enabled,
        modifier = modifier,
        key = key,
    )
}

private fun <T : Any> UiScope.compileCycleButton454065400fd3_1(
    state: CycleButtonState<T>,
    width: Int = 150,
    enabled: StateSource<Boolean>,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
    label: (T) -> UiText = { value -> UiText.Literal(state.formatKnownMember(value)) },
) {
    CycleButton(
        state = state,
        width = width,
        enabled = enabled,
        modifier = modifier,
        key = key,
        label = label,
    )
}

private fun <T : Any> UiScope.compileCycleButton454065400fd3_2(
    state: CycleButtonState<T>,
    width: Int = 150,
    enabled: Boolean = true,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
    label: StateSource<(T) -> UiText>,
) {
    CycleButton(
        state = state,
        width = width,
        enabled = enabled,
        modifier = modifier,
        key = key,
        label = label,
    )
}

private fun <T : Any> UiScope.compileCycleButton454065400fd3_3(
    state: CycleButtonState<T>,
    width: Int = 150,
    enabled: StateSource<Boolean>,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
    label: StateSource<(T) -> UiText>,
) {
    CycleButton(
        state = state,
        width = width,
        enabled = enabled,
        modifier = modifier,
        key = key,
        label = label,
    )
}

private fun UiScope.compileSliderf08abfd13498_1(
    label: StateSource<UiText>,
    state: SliderState,
    width: Int = 150,
    enabled: Boolean = true,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    Slider(
        label = label,
        state = state,
        width = width,
        enabled = enabled,
        modifier = modifier,
        key = key,
    )
}

private fun UiScope.compileSliderf08abfd13498_2(
    label: UiText,
    state: SliderState,
    width: Int = 150,
    enabled: StateSource<Boolean>,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    Slider(
        label = label,
        state = state,
        width = width,
        enabled = enabled,
        modifier = modifier,
        key = key,
    )
}

private fun UiScope.compileSliderf08abfd13498_3(
    label: StateSource<UiText>,
    state: SliderState,
    width: Int = 150,
    enabled: StateSource<Boolean>,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    Slider(
        label = label,
        state = state,
        width = width,
        enabled = enabled,
        modifier = modifier,
        key = key,
    )
}

private fun UiScope.compileSlidercccdb0fa60d4_1(
    label: StateSource<String>,
    state: SliderState,
    width: Int = 150,
    enabled: Boolean = true,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    Slider(
        label = label,
        state = state,
        width = width,
        enabled = enabled,
        modifier = modifier,
        key = key,
    )
}

private fun UiScope.compileSlidercccdb0fa60d4_2(
    label: String,
    state: SliderState,
    width: Int = 150,
    enabled: StateSource<Boolean>,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    Slider(
        label = label,
        state = state,
        width = width,
        enabled = enabled,
        modifier = modifier,
        key = key,
    )
}

private fun UiScope.compileSlidercccdb0fa60d4_3(
    label: StateSource<String>,
    state: SliderState,
    width: Int = 150,
    enabled: StateSource<Boolean>,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    Slider(
        label = label,
        state = state,
        width = width,
        enabled = enabled,
        modifier = modifier,
        key = key,
    )
}

private fun UiScope.compileCheckbox1d460d77bb71_1(
    label: StateSource<String>,
    state: CheckboxState,
    width: Int = 150,
    enabled: Boolean = true,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    Checkbox(
        label = label,
        state = state,
        width = width,
        enabled = enabled,
        modifier = modifier,
        key = key,
    )
}

private fun UiScope.compileCheckbox1d460d77bb71_2(
    label: String,
    state: CheckboxState,
    width: Int = 150,
    enabled: StateSource<Boolean>,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    Checkbox(
        label = label,
        state = state,
        width = width,
        enabled = enabled,
        modifier = modifier,
        key = key,
    )
}

private fun UiScope.compileCheckbox1d460d77bb71_3(
    label: StateSource<String>,
    state: CheckboxState,
    width: Int = 150,
    enabled: StateSource<Boolean>,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    Checkbox(
        label = label,
        state = state,
        width = width,
        enabled = enabled,
        modifier = modifier,
        key = key,
    )
}

private fun UiScope.compileImage386405e1017f_1(
    source: StateSource<ImageSource>,
    size: IntSize? = null,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    Image(
        source = source,
        size = size,
        modifier = modifier,
        key = key,
    )
}

private fun UiScope.compileImage6751db0e9723_1(
    source: StateSource<ImageSource>,
    sourceRegion: IntRect,
    size: IntSize = IntSize(sourceRegion.width, sourceRegion.height),
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    Image(
        source = source,
        sourceRegion = sourceRegion,
        size = size,
        modifier = modifier,
        key = key,
    )
}

private fun UiScope.compilePlayerHead339c1e7d20b9_1(
    source: StateSource<PlayerSkinSource>,
    scale: PlayerHeadScale,
    showHat: Boolean = true,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
    loadingContent: (UiScope.() -> Unit)? = null,
    failureContent: (UiScope.() -> Unit)? = null,
) {
    PlayerHead(
        source = source,
        scale = scale,
        showHat = showHat,
        modifier = modifier,
        key = key,
        loadingContent = loadingContent,
        failureContent = failureContent,
    )
}

private fun UiScope.compileSlota3c7818cbdc8_1(
    bind: StateSource<SlotBinding?>,
    highlightable: Boolean = true,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
    content: (UiScope.() -> Unit)? = null,
) {
    Slot(
        bind = bind,
        highlightable = highlightable,
        modifier = modifier,
        key = key,
        content = content,
    )
}

private fun UiScope.compileSlota3c7818cbdc8_2(
    bind: SlotBinding? = null,
    highlightable: StateSource<Boolean>,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
    content: (UiScope.() -> Unit)? = null,
) {
    Slot(
        bind = bind,
        highlightable = highlightable,
        modifier = modifier,
        key = key,
        content = content,
    )
}

private fun UiScope.compileSlota3c7818cbdc8_3(
    bind: StateSource<SlotBinding?>,
    highlightable: StateSource<Boolean>,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
    content: (UiScope.() -> Unit)? = null,
) {
    Slot(
        bind = bind,
        highlightable = highlightable,
        modifier = modifier,
        key = key,
        content = content,
    )
}

private fun UiScope.compileTextFieldbdacf61484d9_1(
    state: TextFieldState,
    enabled: StateSource<Boolean>,
    textStyle: TextStyle = TextStyle.TextField,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    TextField(
        state = state,
        enabled = enabled,
        textStyle = textStyle,
        modifier = modifier,
        key = key,
    )
}

private fun UiScope.compileTextField06eec201bfdd_1(
    state: TextFieldState,
    size: IntSize,
    enabled: StateSource<Boolean>,
    textStyle: TextStyle = TextStyle.TextField,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    TextField(
        state = state,
        size = size,
        enabled = enabled,
        textStyle = textStyle,
        modifier = modifier,
        key = key,
    )
}

private fun UiScope.compileTextFieldac020717728e_1(
    state: TextFieldState,
    font: ResourceId,
    enabled: StateSource<Boolean>,
    textStyle: TextStyle = TextStyle.TextField,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    TextField(
        state = state,
        font = font,
        enabled = enabled,
        textStyle = textStyle,
        modifier = modifier,
        key = key,
    )
}

private fun UiScope.compileTextField0f2e4a0352af_1(
    state: TextFieldState,
    size: IntSize,
    font: ResourceId,
    enabled: StateSource<Boolean>,
    textStyle: TextStyle = TextStyle.TextField,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    TextField(
        state = state,
        size = size,
        font = font,
        enabled = enabled,
        textStyle = textStyle,
        modifier = modifier,
        key = key,
    )
}

private fun UiScope.compileTextAreac0abf0512fec_1(
    state: TextAreaState,
    viewport: TextAreaViewport,
    enabled: StateSource<Boolean>,
    textStyle: TextStyle = TextStyle.TextField,
    wrap: TextWrap = TextWrap.Word,
    lineSpacing: Int = 0,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    TextArea(
        state = state,
        viewport = viewport,
        enabled = enabled,
        textStyle = textStyle,
        wrap = wrap,
        lineSpacing = lineSpacing,
        modifier = modifier,
        key = key,
    )
}

private fun UiScope.compileTextAreac701b9e2eaf6_1(
    state: TextAreaState,
    viewport: TextAreaViewport,
    font: ResourceId,
    enabled: StateSource<Boolean>,
    textStyle: TextStyle = TextStyle.TextField,
    wrap: TextWrap = TextWrap.Word,
    lineSpacing: Int = 0,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    TextArea(
        state = state,
        viewport = viewport,
        font = font,
        enabled = enabled,
        textStyle = textStyle,
        wrap = wrap,
        lineSpacing = lineSpacing,
        modifier = modifier,
        key = key,
    )
}

private fun UiScope.compileButtoncffa97b99dc2_1(
    label: StateSource<UiText>,
    width: Int = 150,
    enabled: Boolean = true,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    Button(
        label = label,
        width = width,
        enabled = enabled,
        modifier = modifier,
        key = key,
    )
}

private fun UiScope.compileButtoncffa97b99dc2_2(
    label: UiText,
    width: Int = 150,
    enabled: StateSource<Boolean>,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    Button(
        label = label,
        width = width,
        enabled = enabled,
        modifier = modifier,
        key = key,
    )
}

private fun UiScope.compileButtoncffa97b99dc2_3(
    label: StateSource<UiText>,
    width: Int = 150,
    enabled: StateSource<Boolean>,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    Button(
        label = label,
        width = width,
        enabled = enabled,
        modifier = modifier,
        key = key,
    )
}

private fun UiScope.compileButton6e1d7e05cd68_1(
    label: StateSource<String>,
    width: Int = 150,
    enabled: Boolean = true,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    Button(
        label = label,
        width = width,
        enabled = enabled,
        modifier = modifier,
        key = key,
    )
}

private fun UiScope.compileButton6e1d7e05cd68_2(
    label: String,
    width: Int = 150,
    enabled: StateSource<Boolean>,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    Button(
        label = label,
        width = width,
        enabled = enabled,
        modifier = modifier,
        key = key,
    )
}

private fun UiScope.compileButton6e1d7e05cd68_3(
    label: StateSource<String>,
    width: Int = 150,
    enabled: StateSource<Boolean>,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    Button(
        label = label,
        width = width,
        enabled = enabled,
        modifier = modifier,
        key = key,
    )
}

private fun UiScope.compileTab58ed18680f25_1(
    label: StateSource<UiText>,
    selected: Boolean,
    width: Int = 150,
    enabled: Boolean = true,
    indicator: TabSelectionIndicator = TabSelectionIndicator.Underline,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    Tab(
        label = label,
        selected = selected,
        width = width,
        enabled = enabled,
        indicator = indicator,
        modifier = modifier,
        key = key,
    )
}

private fun UiScope.compileTab58ed18680f25_2(
    label: UiText,
    selected: StateSource<Boolean>,
    width: Int = 150,
    enabled: Boolean = true,
    indicator: TabSelectionIndicator = TabSelectionIndicator.Underline,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    Tab(
        label = label,
        selected = selected,
        width = width,
        enabled = enabled,
        indicator = indicator,
        modifier = modifier,
        key = key,
    )
}

private fun UiScope.compileTab58ed18680f25_3(
    label: StateSource<UiText>,
    selected: StateSource<Boolean>,
    width: Int = 150,
    enabled: Boolean = true,
    indicator: TabSelectionIndicator = TabSelectionIndicator.Underline,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    Tab(
        label = label,
        selected = selected,
        width = width,
        enabled = enabled,
        indicator = indicator,
        modifier = modifier,
        key = key,
    )
}

private fun UiScope.compileTab58ed18680f25_4(
    label: UiText,
    selected: Boolean,
    width: Int = 150,
    enabled: StateSource<Boolean>,
    indicator: TabSelectionIndicator = TabSelectionIndicator.Underline,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    Tab(
        label = label,
        selected = selected,
        width = width,
        enabled = enabled,
        indicator = indicator,
        modifier = modifier,
        key = key,
    )
}

private fun UiScope.compileTab58ed18680f25_5(
    label: StateSource<UiText>,
    selected: Boolean,
    width: Int = 150,
    enabled: StateSource<Boolean>,
    indicator: TabSelectionIndicator = TabSelectionIndicator.Underline,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    Tab(
        label = label,
        selected = selected,
        width = width,
        enabled = enabled,
        indicator = indicator,
        modifier = modifier,
        key = key,
    )
}

private fun UiScope.compileTab58ed18680f25_6(
    label: UiText,
    selected: StateSource<Boolean>,
    width: Int = 150,
    enabled: StateSource<Boolean>,
    indicator: TabSelectionIndicator = TabSelectionIndicator.Underline,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    Tab(
        label = label,
        selected = selected,
        width = width,
        enabled = enabled,
        indicator = indicator,
        modifier = modifier,
        key = key,
    )
}

private fun UiScope.compileTab58ed18680f25_7(
    label: StateSource<UiText>,
    selected: StateSource<Boolean>,
    width: Int = 150,
    enabled: StateSource<Boolean>,
    indicator: TabSelectionIndicator = TabSelectionIndicator.Underline,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    Tab(
        label = label,
        selected = selected,
        width = width,
        enabled = enabled,
        indicator = indicator,
        modifier = modifier,
        key = key,
    )
}

private fun UiScope.compileTab06dab4066e27_1(
    label: StateSource<String>,
    selected: Boolean,
    width: Int = 150,
    enabled: Boolean = true,
    indicator: TabSelectionIndicator = TabSelectionIndicator.Underline,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    Tab(
        label = label,
        selected = selected,
        width = width,
        enabled = enabled,
        indicator = indicator,
        modifier = modifier,
        key = key,
    )
}

private fun UiScope.compileTab06dab4066e27_2(
    label: String,
    selected: StateSource<Boolean>,
    width: Int = 150,
    enabled: Boolean = true,
    indicator: TabSelectionIndicator = TabSelectionIndicator.Underline,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    Tab(
        label = label,
        selected = selected,
        width = width,
        enabled = enabled,
        indicator = indicator,
        modifier = modifier,
        key = key,
    )
}

private fun UiScope.compileTab06dab4066e27_3(
    label: StateSource<String>,
    selected: StateSource<Boolean>,
    width: Int = 150,
    enabled: Boolean = true,
    indicator: TabSelectionIndicator = TabSelectionIndicator.Underline,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    Tab(
        label = label,
        selected = selected,
        width = width,
        enabled = enabled,
        indicator = indicator,
        modifier = modifier,
        key = key,
    )
}

private fun UiScope.compileTab06dab4066e27_4(
    label: String,
    selected: Boolean,
    width: Int = 150,
    enabled: StateSource<Boolean>,
    indicator: TabSelectionIndicator = TabSelectionIndicator.Underline,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    Tab(
        label = label,
        selected = selected,
        width = width,
        enabled = enabled,
        indicator = indicator,
        modifier = modifier,
        key = key,
    )
}

private fun UiScope.compileTab06dab4066e27_5(
    label: StateSource<String>,
    selected: Boolean,
    width: Int = 150,
    enabled: StateSource<Boolean>,
    indicator: TabSelectionIndicator = TabSelectionIndicator.Underline,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    Tab(
        label = label,
        selected = selected,
        width = width,
        enabled = enabled,
        indicator = indicator,
        modifier = modifier,
        key = key,
    )
}

private fun UiScope.compileTab06dab4066e27_6(
    label: String,
    selected: StateSource<Boolean>,
    width: Int = 150,
    enabled: StateSource<Boolean>,
    indicator: TabSelectionIndicator = TabSelectionIndicator.Underline,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    Tab(
        label = label,
        selected = selected,
        width = width,
        enabled = enabled,
        indicator = indicator,
        modifier = modifier,
        key = key,
    )
}

private fun UiScope.compileTab06dab4066e27_7(
    label: StateSource<String>,
    selected: StateSource<Boolean>,
    width: Int = 150,
    enabled: StateSource<Boolean>,
    indicator: TabSelectionIndicator = TabSelectionIndicator.Underline,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    Tab(
        label = label,
        selected = selected,
        width = width,
        enabled = enabled,
        indicator = indicator,
        modifier = modifier,
        key = key,
    )
}

private fun UiScope.compileTextField8ebce6a07628_1(
    state: TextFieldState,
    appearance: TextInputAppearance,
    enabled: StateSource<Boolean>,
    textStyle: TextStyle = TextStyle.TextField,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    TextField(
        state = state,
        appearance = appearance,
        enabled = enabled,
        textStyle = textStyle,
        modifier = modifier,
        key = key,
    )
}

private fun UiScope.compileTextField68d5823f42d7_1(
    state: TextFieldState,
    appearance: TextInputAppearance,
    size: IntSize,
    enabled: StateSource<Boolean>,
    textStyle: TextStyle = TextStyle.TextField,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    TextField(
        state = state,
        appearance = appearance,
        size = size,
        enabled = enabled,
        textStyle = textStyle,
        modifier = modifier,
        key = key,
    )
}

private fun UiScope.compileTextField715dafc3f527_1(
    state: TextFieldState,
    appearance: TextInputAppearance,
    font: ResourceId,
    enabled: StateSource<Boolean>,
    textStyle: TextStyle = TextStyle.TextField,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    TextField(
        state = state,
        appearance = appearance,
        font = font,
        enabled = enabled,
        textStyle = textStyle,
        modifier = modifier,
        key = key,
    )
}

private fun UiScope.compileTextFieldfd7b3be167e7_1(
    state: TextFieldState,
    appearance: TextInputAppearance,
    size: IntSize,
    font: ResourceId,
    enabled: StateSource<Boolean>,
    textStyle: TextStyle = TextStyle.TextField,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    TextField(
        state = state,
        appearance = appearance,
        size = size,
        font = font,
        enabled = enabled,
        textStyle = textStyle,
        modifier = modifier,
        key = key,
    )
}

private fun UiScope.compileTextArea80c0b5b4cb37_1(
    state: TextAreaState,
    appearance: TextInputAppearance,
    viewport: TextAreaViewport,
    enabled: StateSource<Boolean>,
    textStyle: TextStyle = TextStyle.TextField,
    wrap: TextWrap = TextWrap.Word,
    lineSpacing: Int = 0,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    TextArea(
        state = state,
        appearance = appearance,
        viewport = viewport,
        enabled = enabled,
        textStyle = textStyle,
        wrap = wrap,
        lineSpacing = lineSpacing,
        modifier = modifier,
        key = key,
    )
}

private fun UiScope.compileTextArea4da1faac4769_1(
    state: TextAreaState,
    appearance: TextInputAppearance,
    viewport: TextAreaViewport,
    font: ResourceId,
    enabled: StateSource<Boolean>,
    textStyle: TextStyle = TextStyle.TextField,
    wrap: TextWrap = TextWrap.Word,
    lineSpacing: Int = 0,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    TextArea(
        state = state,
        appearance = appearance,
        viewport = viewport,
        font = font,
        enabled = enabled,
        textStyle = textStyle,
        wrap = wrap,
        lineSpacing = lineSpacing,
        modifier = modifier,
        key = key,
    )
}

private fun UiScope.compileCanvas7047d39d3483_1(
    source: StateSource<CanvasSource>,
    size: IntSize,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
) {
    Canvas(
        source = source,
        size = size,
        modifier = modifier,
        key = key,
    )
}

private fun UiScope.compileTiledImage06558dbd1f3e_1(
    source: StateSource<TiledImageSource>,
    state: PanZoomState,
    size: IntSize,
    fit: PanZoomFit = PanZoomFit.Contain,
    cachePolicy: TiledImageCachePolicy = TiledImageCachePolicy.Default,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
    content: TiledImageScope.() -> Unit = {},
) {
    TiledImage(
        source = source,
        state = state,
        size = size,
        fit = fit,
        cachePolicy = cachePolicy,
        modifier = modifier,
        key = key,
        content = content,
    )
}

private fun <T : Any, K : Any> UiScope.compileVirtualList7e3481099f80_1(
    itemCount: Int,
    itemAt: (Int) -> T,
    keyAt: (Int) -> K,
    state: VirtualListState<K>,
    viewportSize: IntSize,
    rowHeight: Int,
    indexOfKey: (K) -> Int? = { target -> (0 until itemCount).firstOrNull { index -> keyAt(index) == target } },
    scrollRate: Int = 10,
    canLoadLeading: StateSource<Boolean>,
    canLoadTrailing: Boolean = false,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
    content: UiScope.(T) -> Unit,
) {
    VirtualList(
        itemCount = itemCount,
        itemAt = itemAt,
        keyAt = keyAt,
        state = state,
        viewportSize = viewportSize,
        rowHeight = rowHeight,
        indexOfKey = indexOfKey,
        scrollRate = scrollRate,
        canLoadLeading = canLoadLeading,
        canLoadTrailing = canLoadTrailing,
        modifier = modifier,
        key = key,
        content = content,
    )
}

private fun <T : Any, K : Any> UiScope.compileVirtualList7e3481099f80_2(
    itemCount: Int,
    itemAt: (Int) -> T,
    keyAt: (Int) -> K,
    state: VirtualListState<K>,
    viewportSize: IntSize,
    rowHeight: Int,
    indexOfKey: (K) -> Int? = { target -> (0 until itemCount).firstOrNull { index -> keyAt(index) == target } },
    scrollRate: Int = 10,
    canLoadLeading: Boolean = false,
    canLoadTrailing: StateSource<Boolean>,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
    content: UiScope.(T) -> Unit,
) {
    VirtualList(
        itemCount = itemCount,
        itemAt = itemAt,
        keyAt = keyAt,
        state = state,
        viewportSize = viewportSize,
        rowHeight = rowHeight,
        indexOfKey = indexOfKey,
        scrollRate = scrollRate,
        canLoadLeading = canLoadLeading,
        canLoadTrailing = canLoadTrailing,
        modifier = modifier,
        key = key,
        content = content,
    )
}

private fun <T : Any, K : Any> UiScope.compileVirtualList7e3481099f80_3(
    itemCount: Int,
    itemAt: (Int) -> T,
    keyAt: (Int) -> K,
    state: VirtualListState<K>,
    viewportSize: IntSize,
    rowHeight: Int,
    indexOfKey: (K) -> Int? = { target -> (0 until itemCount).firstOrNull { index -> keyAt(index) == target } },
    scrollRate: Int = 10,
    canLoadLeading: StateSource<Boolean>,
    canLoadTrailing: StateSource<Boolean>,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
    content: UiScope.(T) -> Unit,
) {
    VirtualList(
        itemCount = itemCount,
        itemAt = itemAt,
        keyAt = keyAt,
        state = state,
        viewportSize = viewportSize,
        rowHeight = rowHeight,
        indexOfKey = indexOfKey,
        scrollRate = scrollRate,
        canLoadLeading = canLoadLeading,
        canLoadTrailing = canLoadTrailing,
        modifier = modifier,
        key = key,
        content = content,
    )
}

private fun <T : Any, K : Any> UiScope.compileVirtualList4013cecb450b_1(
    itemCount: () -> Int,
    itemAt: (Int) -> T,
    keyAt: (Int) -> K,
    state: VirtualListState<K>,
    viewportSize: IntSize,
    rowHeight: Int,
    indexOfKey: ((K) -> Int?)? = null,
    scrollRate: Int = 10,
    canLoadLeading: StateSource<Boolean>,
    canLoadTrailing: Boolean = false,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
    content: UiScope.(T) -> Unit,
) {
    VirtualList(
        itemCount = itemCount,
        itemAt = itemAt,
        keyAt = keyAt,
        state = state,
        viewportSize = viewportSize,
        rowHeight = rowHeight,
        indexOfKey = indexOfKey,
        scrollRate = scrollRate,
        canLoadLeading = canLoadLeading,
        canLoadTrailing = canLoadTrailing,
        modifier = modifier,
        key = key,
        content = content,
    )
}

private fun <T : Any, K : Any> UiScope.compileVirtualList4013cecb450b_2(
    itemCount: () -> Int,
    itemAt: (Int) -> T,
    keyAt: (Int) -> K,
    state: VirtualListState<K>,
    viewportSize: IntSize,
    rowHeight: Int,
    indexOfKey: ((K) -> Int?)? = null,
    scrollRate: Int = 10,
    canLoadLeading: Boolean = false,
    canLoadTrailing: StateSource<Boolean>,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
    content: UiScope.(T) -> Unit,
) {
    VirtualList(
        itemCount = itemCount,
        itemAt = itemAt,
        keyAt = keyAt,
        state = state,
        viewportSize = viewportSize,
        rowHeight = rowHeight,
        indexOfKey = indexOfKey,
        scrollRate = scrollRate,
        canLoadLeading = canLoadLeading,
        canLoadTrailing = canLoadTrailing,
        modifier = modifier,
        key = key,
        content = content,
    )
}

private fun <T : Any, K : Any> UiScope.compileVirtualList4013cecb450b_3(
    itemCount: () -> Int,
    itemAt: (Int) -> T,
    keyAt: (Int) -> K,
    state: VirtualListState<K>,
    viewportSize: IntSize,
    rowHeight: Int,
    indexOfKey: ((K) -> Int?)? = null,
    scrollRate: Int = 10,
    canLoadLeading: StateSource<Boolean>,
    canLoadTrailing: StateSource<Boolean>,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
    content: UiScope.(T) -> Unit,
) {
    VirtualList(
        itemCount = itemCount,
        itemAt = itemAt,
        keyAt = keyAt,
        state = state,
        viewportSize = viewportSize,
        rowHeight = rowHeight,
        indexOfKey = indexOfKey,
        scrollRate = scrollRate,
        canLoadLeading = canLoadLeading,
        canLoadTrailing = canLoadTrailing,
        modifier = modifier,
        key = key,
        content = content,
    )
}

private fun <T : Any, K : Any> UiScope.compileVirtualList91e435daa5f9_1(
    items: StateSource<List<T>>,
    keyOf: (T) -> K,
    state: VirtualListState<K>,
    viewportSize: IntSize,
    rowHeight: Int,
    scrollRate: Int = 10,
    canLoadLeading: Boolean = false,
    canLoadTrailing: Boolean = false,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
    content: UiScope.(T) -> Unit,
) {
    VirtualList(
        items = items,
        keyOf = keyOf,
        state = state,
        viewportSize = viewportSize,
        rowHeight = rowHeight,
        scrollRate = scrollRate,
        canLoadLeading = canLoadLeading,
        canLoadTrailing = canLoadTrailing,
        modifier = modifier,
        key = key,
        content = content,
    )
}

private fun <T : Any, K : Any> UiScope.compileVirtualList91e435daa5f9_2(
    items: List<T>,
    keyOf: (T) -> K,
    state: VirtualListState<K>,
    viewportSize: IntSize,
    rowHeight: Int,
    scrollRate: Int = 10,
    canLoadLeading: StateSource<Boolean>,
    canLoadTrailing: Boolean = false,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
    content: UiScope.(T) -> Unit,
) {
    VirtualList(
        items = items,
        keyOf = keyOf,
        state = state,
        viewportSize = viewportSize,
        rowHeight = rowHeight,
        scrollRate = scrollRate,
        canLoadLeading = canLoadLeading,
        canLoadTrailing = canLoadTrailing,
        modifier = modifier,
        key = key,
        content = content,
    )
}

private fun <T : Any, K : Any> UiScope.compileVirtualList91e435daa5f9_3(
    items: StateSource<List<T>>,
    keyOf: (T) -> K,
    state: VirtualListState<K>,
    viewportSize: IntSize,
    rowHeight: Int,
    scrollRate: Int = 10,
    canLoadLeading: StateSource<Boolean>,
    canLoadTrailing: Boolean = false,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
    content: UiScope.(T) -> Unit,
) {
    VirtualList(
        items = items,
        keyOf = keyOf,
        state = state,
        viewportSize = viewportSize,
        rowHeight = rowHeight,
        scrollRate = scrollRate,
        canLoadLeading = canLoadLeading,
        canLoadTrailing = canLoadTrailing,
        modifier = modifier,
        key = key,
        content = content,
    )
}

private fun <T : Any, K : Any> UiScope.compileVirtualList91e435daa5f9_4(
    items: List<T>,
    keyOf: (T) -> K,
    state: VirtualListState<K>,
    viewportSize: IntSize,
    rowHeight: Int,
    scrollRate: Int = 10,
    canLoadLeading: Boolean = false,
    canLoadTrailing: StateSource<Boolean>,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
    content: UiScope.(T) -> Unit,
) {
    VirtualList(
        items = items,
        keyOf = keyOf,
        state = state,
        viewportSize = viewportSize,
        rowHeight = rowHeight,
        scrollRate = scrollRate,
        canLoadLeading = canLoadLeading,
        canLoadTrailing = canLoadTrailing,
        modifier = modifier,
        key = key,
        content = content,
    )
}

private fun <T : Any, K : Any> UiScope.compileVirtualList91e435daa5f9_5(
    items: StateSource<List<T>>,
    keyOf: (T) -> K,
    state: VirtualListState<K>,
    viewportSize: IntSize,
    rowHeight: Int,
    scrollRate: Int = 10,
    canLoadLeading: Boolean = false,
    canLoadTrailing: StateSource<Boolean>,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
    content: UiScope.(T) -> Unit,
) {
    VirtualList(
        items = items,
        keyOf = keyOf,
        state = state,
        viewportSize = viewportSize,
        rowHeight = rowHeight,
        scrollRate = scrollRate,
        canLoadLeading = canLoadLeading,
        canLoadTrailing = canLoadTrailing,
        modifier = modifier,
        key = key,
        content = content,
    )
}

private fun <T : Any, K : Any> UiScope.compileVirtualList91e435daa5f9_6(
    items: List<T>,
    keyOf: (T) -> K,
    state: VirtualListState<K>,
    viewportSize: IntSize,
    rowHeight: Int,
    scrollRate: Int = 10,
    canLoadLeading: StateSource<Boolean>,
    canLoadTrailing: StateSource<Boolean>,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
    content: UiScope.(T) -> Unit,
) {
    VirtualList(
        items = items,
        keyOf = keyOf,
        state = state,
        viewportSize = viewportSize,
        rowHeight = rowHeight,
        scrollRate = scrollRate,
        canLoadLeading = canLoadLeading,
        canLoadTrailing = canLoadTrailing,
        modifier = modifier,
        key = key,
        content = content,
    )
}

private fun <T : Any, K : Any> UiScope.compileVirtualList91e435daa5f9_7(
    items: StateSource<List<T>>,
    keyOf: (T) -> K,
    state: VirtualListState<K>,
    viewportSize: IntSize,
    rowHeight: Int,
    scrollRate: Int = 10,
    canLoadLeading: StateSource<Boolean>,
    canLoadTrailing: StateSource<Boolean>,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
    content: UiScope.(T) -> Unit,
) {
    VirtualList(
        items = items,
        keyOf = keyOf,
        state = state,
        viewportSize = viewportSize,
        rowHeight = rowHeight,
        scrollRate = scrollRate,
        canLoadLeading = canLoadLeading,
        canLoadTrailing = canLoadTrailing,
        modifier = modifier,
        key = key,
        content = content,
    )
}

private fun <T : Any, K : Any> UiScope.compileSelectionList685be857e721_1(
    items: StateSource<List<T>>,
    keyOf: (T) -> K,
    state: SelectionListState<K>,
    viewportSize: IntSize,
    rowHeight: Int,
    canLoadLeading: Boolean = false,
    canLoadTrailing: Boolean = false,
    scrollRate: Int = 10,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
    content: UiScope.(T) -> Unit,
) {
    SelectionList(
        items = items,
        keyOf = keyOf,
        state = state,
        viewportSize = viewportSize,
        rowHeight = rowHeight,
        canLoadLeading = canLoadLeading,
        canLoadTrailing = canLoadTrailing,
        scrollRate = scrollRate,
        modifier = modifier,
        key = key,
        content = content,
    )
}

private fun <T : Any, K : Any> UiScope.compileSelectionList685be857e721_2(
    items: List<T>,
    keyOf: (T) -> K,
    state: SelectionListState<K>,
    viewportSize: IntSize,
    rowHeight: Int,
    canLoadLeading: StateSource<Boolean>,
    canLoadTrailing: Boolean = false,
    scrollRate: Int = 10,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
    content: UiScope.(T) -> Unit,
) {
    SelectionList(
        items = items,
        keyOf = keyOf,
        state = state,
        viewportSize = viewportSize,
        rowHeight = rowHeight,
        canLoadLeading = canLoadLeading,
        canLoadTrailing = canLoadTrailing,
        scrollRate = scrollRate,
        modifier = modifier,
        key = key,
        content = content,
    )
}

private fun <T : Any, K : Any> UiScope.compileSelectionList685be857e721_3(
    items: StateSource<List<T>>,
    keyOf: (T) -> K,
    state: SelectionListState<K>,
    viewportSize: IntSize,
    rowHeight: Int,
    canLoadLeading: StateSource<Boolean>,
    canLoadTrailing: Boolean = false,
    scrollRate: Int = 10,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
    content: UiScope.(T) -> Unit,
) {
    SelectionList(
        items = items,
        keyOf = keyOf,
        state = state,
        viewportSize = viewportSize,
        rowHeight = rowHeight,
        canLoadLeading = canLoadLeading,
        canLoadTrailing = canLoadTrailing,
        scrollRate = scrollRate,
        modifier = modifier,
        key = key,
        content = content,
    )
}

private fun <T : Any, K : Any> UiScope.compileSelectionList685be857e721_4(
    items: List<T>,
    keyOf: (T) -> K,
    state: SelectionListState<K>,
    viewportSize: IntSize,
    rowHeight: Int,
    canLoadLeading: Boolean = false,
    canLoadTrailing: StateSource<Boolean>,
    scrollRate: Int = 10,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
    content: UiScope.(T) -> Unit,
) {
    SelectionList(
        items = items,
        keyOf = keyOf,
        state = state,
        viewportSize = viewportSize,
        rowHeight = rowHeight,
        canLoadLeading = canLoadLeading,
        canLoadTrailing = canLoadTrailing,
        scrollRate = scrollRate,
        modifier = modifier,
        key = key,
        content = content,
    )
}

private fun <T : Any, K : Any> UiScope.compileSelectionList685be857e721_5(
    items: StateSource<List<T>>,
    keyOf: (T) -> K,
    state: SelectionListState<K>,
    viewportSize: IntSize,
    rowHeight: Int,
    canLoadLeading: Boolean = false,
    canLoadTrailing: StateSource<Boolean>,
    scrollRate: Int = 10,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
    content: UiScope.(T) -> Unit,
) {
    SelectionList(
        items = items,
        keyOf = keyOf,
        state = state,
        viewportSize = viewportSize,
        rowHeight = rowHeight,
        canLoadLeading = canLoadLeading,
        canLoadTrailing = canLoadTrailing,
        scrollRate = scrollRate,
        modifier = modifier,
        key = key,
        content = content,
    )
}

private fun <T : Any, K : Any> UiScope.compileSelectionList685be857e721_6(
    items: List<T>,
    keyOf: (T) -> K,
    state: SelectionListState<K>,
    viewportSize: IntSize,
    rowHeight: Int,
    canLoadLeading: StateSource<Boolean>,
    canLoadTrailing: StateSource<Boolean>,
    scrollRate: Int = 10,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
    content: UiScope.(T) -> Unit,
) {
    SelectionList(
        items = items,
        keyOf = keyOf,
        state = state,
        viewportSize = viewportSize,
        rowHeight = rowHeight,
        canLoadLeading = canLoadLeading,
        canLoadTrailing = canLoadTrailing,
        scrollRate = scrollRate,
        modifier = modifier,
        key = key,
        content = content,
    )
}

private fun <T : Any, K : Any> UiScope.compileSelectionList685be857e721_7(
    items: StateSource<List<T>>,
    keyOf: (T) -> K,
    state: SelectionListState<K>,
    viewportSize: IntSize,
    rowHeight: Int,
    canLoadLeading: StateSource<Boolean>,
    canLoadTrailing: StateSource<Boolean>,
    scrollRate: Int = 10,
    modifier: Modifier = Modifier.Empty,
    key: ElementKey<*>? = null,
    content: UiScope.(T) -> Unit,
) {
    SelectionList(
        items = items,
        keyOf = keyOf,
        state = state,
        viewportSize = viewportSize,
        rowHeight = rowHeight,
        canLoadLeading = canLoadLeading,
        canLoadTrailing = canLoadTrailing,
        scrollRate = scrollRate,
        modifier = modifier,
        key = key,
        content = content,
    )
}
