kotlin {
    sourceSets {
        commonTest.dependencies { implementation(libs.kotlin.test) }
        jvmTest.dependencies {
            implementation(libs.junit.jupiter)
            runtimeOnly(libs.junit.platform.launcher)
        }
    }
}

apply(from = "state-components.gradle.kts")

fun observeOverloads(): String = buildString {
    appendLine("// Generated by :api:generateObserveOverloads. Do not edit by hand.")
    appendLine("@file:Suppress(\"FunctionNaming\", \"ktlint:standard:function-naming\", \"LongParameterList\", \"TooManyFunctions\")")
    appendLine()
    appendLine("package dev.s7a.strata.component")
    appendLine()
    appendLine("import dev.s7a.strata.element.ElementKey")
    appendLine("import dev.s7a.strata.modifier.Modifier")
    appendLine("import dev.s7a.strata.state.StateSource")
    for (arity in 1..22) {
        val indices = 1..arity
        val types = indices.joinToString(", ") { "V$it" }
        val sources = indices.joinToString(", ") { "state$it" }
        val values = indices.joinToString(", ") { "values[${it - 1}] as V$it" }
        appendLine()
        appendLine("/**")
        appendLine(" * Emits one retained region observing $arity source${if (arity == 1) "" else "s"} without evaluating content immediately.")
        appendLine(" *")
        if (arity == 1) {
            appendLine(" * The owner-thread callback emits zero or one root; use Row or Column for multiple children.")
            appendLine(" * The region is one layout child: apply parent data to its modifier. Empty content has zero natural size.")
            appendLine(" * Source identities share subscriptions and frame snapshots; updates coalesce before parent-first evaluation.")
            appendLine(" * Equal values skip source-driven evaluation; changed parent callbacks still refresh captures.")
            appendLine(" * Keep editable state outside content. Do not mutate sources or retain the callback scope.")
            appendLine(" * Removal, failure, and close release subscriptions and captured content without closing caller-owned sources.")
            appendLine(" * @param state1 caller-owned source whose committed value is passed to content.")
            appendLine(" * @param modifier active behavior and parent data for the region.")
            appendLine(" * @param key optional stable sibling identity.")
            appendLine(" * @param content deferred owner-thread callback.")
        } else {
            appendLine(" * Uses the single-source [Observe] contract; caller-owned source values are passed in declaration order.")
            appendLine(" * Independent sources are not atomic together; publish one model when fields must change as a unit.")
        }
        appendLine(" */")
        appendLine("public fun <$types> UiScope.Observe(")
        indices.forEach { appendLine("    state$it: StateSource<V$it>,") }
        appendLine("    modifier: Modifier = Modifier.Empty,")
        appendLine("    key: ElementKey<*>? = null,")
        appendLine("    content: UiScope.($types) -> Unit,")
        appendLine(") {")
        appendLine("    emitObserve(listOf($sources), modifier, key) { values ->")
        appendLine("        @Suppress(\"UNCHECKED_CAST\")")
        appendLine("        content($values)")
        appendLine("    }")
        appendLine("}")
    }
}

val observeSource = layout.projectDirectory.file("src/main/kotlin/dev/s7a/strata/component/ObserveComponents.kt")
tasks.register("generateObserveOverloads") {
    group = "generation"
    description = "Regenerates the checked-in typed Observe overloads from one template."
    inputs.file(layout.projectDirectory.file("build.gradle.kts"))
    outputs.file(observeSource)
    doLast { observeSource.asFile.writeText(observeOverloads(), Charsets.UTF_8) }
}
val checkObserveOverloads = tasks.register("checkObserveOverloads") {
    group = "verification"
    description = "Verifies all generated Observe overloads without rewriting source files."
    inputs.file(observeSource)
    inputs.file(layout.projectDirectory.file("build.gradle.kts"))
    doLast {
        check(observeSource.asFile.readText().replace("\r\n", "\n") == observeOverloads()) {
            "Observe overloads are stale. Run :api:generateObserveOverloads."
        }
    }
}
tasks.named("check") { dependsOn(checkObserveOverloads) }
tasks.matching { it.name != "generateObserveOverloads" }.configureEach {
    mustRunAfter("generateObserveOverloads")
}
