kotlin {
    sourceSets {
        commonTest.dependencies { implementation(libs.kotlin.test) }
        jvmTest.dependencies {
            implementation(libs.junit.jupiter)
            runtimeOnly(libs.junit.platform.launcher)
        }
    }
}

apply(from = "state-components.gradle.kts")

fun observeOverloads(): String = buildString {
    appendLine("// Generated by :api:generateObserveOverloads. Do not edit by hand.")
    appendLine("@file:Suppress(\"FunctionNaming\", \"ktlint:standard:function-naming\", \"LongParameterList\", \"TooManyFunctions\")")
    appendLine()
    appendLine("package dev.s7a.strata.component")
    appendLine()
    appendLine("import dev.s7a.strata.element.ElementKey")
    appendLine("import dev.s7a.strata.modifier.Modifier")
    appendLine("import dev.s7a.strata.state.StateSource")
    for (arity in 1..22) {
        val indices = 1..arity
        val types = indices.joinToString(", ") { "V$it" }
        val sources = indices.joinToString(", ") { "state$it" }
        val values = indices.joinToString(", ") { "values[${it - 1}] as V$it" }
        appendLine()
        appendLine("/**")
        appendLine(" * Emits one retained region observing $arity source${if (arity == 1) "" else "s"} without evaluating content immediately.")
        appendLine(" *")
        appendLine(" * The owner-thread callback emits zero or one root; use Row or Column to arrange multiple children.")
        appendLine(" * Source identities share frame snapshots and subscriptions in one tree. Updates coalesce before parent-first evaluation.")
        appendLine(" * The region is one parent-layout child; apply parent data to its modifier. An empty region has zero natural size.")
        appendLine(" * Keep editable state outside content. Content must not mutate sources or retain its callback-lifetime scope.")
        appendLine(" * Subscriptions and captured content are released when the region leaves its tree or the tree fails or closes.")
        indices.forEach { appendLine(" * @param state$it caller-owned source whose value becomes callback argument $it.") }
        appendLine(" * @param modifier active behavior on this region, including parent data for its containing layout.")
        appendLine(" * @param key optional stable identity among the parent region's direct children.")
        appendLine(" * @param content deferred owner-thread callback receiving the frame-committed values in declaration order.")
        appendLine(" */")
        appendLine("public fun <$types> UiScope.Observe(")
        indices.forEach { appendLine("    state$it: StateSource<V$it>,") }
        appendLine("    modifier: Modifier = Modifier.Empty,")
        appendLine("    key: ElementKey<*>? = null,")
        appendLine("    content: UiScope.($types) -> Unit,")
        appendLine(") {")
        appendLine("    emitObserve(listOf($sources), modifier, key) { values ->")
        appendLine("        @Suppress(\"UNCHECKED_CAST\")")
        appendLine("        content($values)")
        appendLine("    }")
        appendLine("}")
    }
}

val observeSource = layout.projectDirectory.file("src/main/kotlin/dev/s7a/strata/component/ObserveComponents.kt")
tasks.register("generateObserveOverloads") {
    group = "generation"
    description = "Regenerates the checked-in typed Observe overloads from one template."
    inputs.file(layout.projectDirectory.file("build.gradle.kts"))
    outputs.file(observeSource)
    doLast { observeSource.asFile.writeText(observeOverloads(), Charsets.UTF_8) }
}
val checkObserveOverloads = tasks.register("checkObserveOverloads") {
    group = "verification"
    description = "Verifies all generated Observe overloads without rewriting source files."
    inputs.file(observeSource)
    inputs.file(layout.projectDirectory.file("build.gradle.kts"))
    doLast {
        check(observeSource.asFile.readText().replace("\r\n", "\n") == observeOverloads()) {
            "Observe overloads are stale. Run :api:generateObserveOverloads."
        }
    }
}
tasks.named("check") { dependsOn(checkObserveOverloads) }
tasks.matching { it.name != "generateObserveOverloads" }.configureEach {
    mustRunAfter("generateObserveOverloads")
}
